// Code generated by ent, DO NOT EDIT.

package contributionroom

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the contributionroom type in the database.
	Label = "contribution_room"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldOwnerUserID holds the string denoting the owner_user_id field in the database.
	FieldOwnerUserID = "owner_user_id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldConsumerRateMultiplier holds the string denoting the consumer_rate_multiplier field in the database.
	FieldConsumerRateMultiplier = "consumer_rate_multiplier"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldVisibility holds the string denoting the visibility field in the database.
	FieldVisibility = "visibility"
	// EdgeOwner holds the string denoting the owner edge name in mutations.
	EdgeOwner = "owner"
	// EdgeAccounts holds the string denoting the accounts edge name in mutations.
	EdgeAccounts = "accounts"
	// EdgePreferences holds the string denoting the preferences edge name in mutations.
	EdgePreferences = "preferences"
	// Table holds the table name of the contributionroom in the database.
	Table = "contribution_rooms"
	// OwnerTable is the table that holds the owner relation/edge.
	OwnerTable = "contribution_rooms"
	// OwnerInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	OwnerInverseTable = "users"
	// OwnerColumn is the table column denoting the owner relation/edge.
	OwnerColumn = "owner_user_id"
	// AccountsTable is the table that holds the accounts relation/edge.
	AccountsTable = "contribution_room_accounts"
	// AccountsInverseTable is the table name for the ContributionRoomAccount entity.
	// It exists in this package in order to avoid circular dependency with the "contributionroomaccount" package.
	AccountsInverseTable = "contribution_room_accounts"
	// AccountsColumn is the table column denoting the accounts relation/edge.
	AccountsColumn = "room_id"
	// PreferencesTable is the table that holds the preferences relation/edge.
	PreferencesTable = "user_contribution_room_preferences"
	// PreferencesInverseTable is the table name for the UserContributionRoomPreference entity.
	// It exists in this package in order to avoid circular dependency with the "usercontributionroompreference" package.
	PreferencesInverseTable = "user_contribution_room_preferences"
	// PreferencesColumn is the table column denoting the preferences relation/edge.
	PreferencesColumn = "room_id"
)

// Columns holds all SQL columns for contributionroom fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldOwnerUserID,
	FieldName,
	FieldConsumerRateMultiplier,
	FieldStatus,
	FieldVisibility,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultConsumerRateMultiplier holds the default value on creation for the "consumer_rate_multiplier" field.
	DefaultConsumerRateMultiplier float64
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// DefaultVisibility holds the default value on creation for the "visibility" field.
	DefaultVisibility string
	// VisibilityValidator is a validator for the "visibility" field. It is called by the builders before save.
	VisibilityValidator func(string) error
)

// OrderOption defines the ordering options for the ContributionRoom queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByOwnerUserID orders the results by the owner_user_id field.
func ByOwnerUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOwnerUserID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByConsumerRateMultiplier orders the results by the consumer_rate_multiplier field.
func ByConsumerRateMultiplier(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldConsumerRateMultiplier, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByVisibility orders the results by the visibility field.
func ByVisibility(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVisibility, opts...).ToFunc()
}

// ByOwnerField orders the results by owner field.
func ByOwnerField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newOwnerStep(), sql.OrderByField(field, opts...))
	}
}

// ByAccountsCount orders the results by accounts count.
func ByAccountsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newAccountsStep(), opts...)
	}
}

// ByAccounts orders the results by accounts terms.
func ByAccounts(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAccountsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByPreferencesCount orders the results by preferences count.
func ByPreferencesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newPreferencesStep(), opts...)
	}
}

// ByPreferences orders the results by preferences terms.
func ByPreferences(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPreferencesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newOwnerStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(OwnerInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, OwnerTable, OwnerColumn),
	)
}
func newAccountsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AccountsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, AccountsTable, AccountsColumn),
	)
}
func newPreferencesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PreferencesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, PreferencesTable, PreferencesColumn),
	)
}
