// Code generated by ent, DO NOT EDIT.

package contributionroom

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.ContributionRoom {
	return predicate.ContributionRoom(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.ContributionRoom {
	return predicate.ContributionRoom(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.ContributionRoom {
	return predicate.ContributionRoom(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.ContributionRoom {
	return predicate.ContributionRoom(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.ContributionRoom {
	return predicate.ContributionRoom(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.ContributionRoom {
	return predicate.ContributionRoom(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.ContributionRoom {
	return predicate.ContributionRoom(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.ContributionRoom {
	return predicate.ContributionRoom(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.ContributionRoom {
	return predicate.ContributionRoom(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ContributionRoom {
	return predicate.ContributionRoom(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ContributionRoom {
	return predicate.ContributionRoom(sql.FieldEQ(FieldUpdatedAt, v))
}

// OwnerUserID applies equality check predicate on the "owner_user_id" field. It's identical to OwnerUserIDEQ.
func OwnerUserID(v int64) predicate.ContributionRoom {
	return predicate.ContributionRoom(sql.FieldEQ(FieldOwnerUserID, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.ContributionRoom {
	return predicate.ContributionRoom(sql.FieldEQ(FieldName, v))
}

// ConsumerRateMultiplier applies equality check predicate on the "consumer_rate_multiplier" field. It's identical to ConsumerRateMultiplierEQ.
func ConsumerRateMultiplier(v float64) predicate.ContributionRoom {
	return predicate.ContributionRoom(sql.FieldEQ(FieldConsumerRateMultiplier, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.ContributionRoom {
	return predicate.ContributionRoom(sql.FieldEQ(FieldStatus, v))
}

// Visibility applies equality check predicate on the "visibility" field. It's identical to VisibilityEQ.
func Visibility(v string) predicate.ContributionRoom {
	return predicate.ContributionRoom(sql.FieldEQ(FieldVisibility, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ContributionRoom {
	return predicate.ContributionRoom(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ContributionRoom {
	return predicate.ContributionRoom(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ContributionRoom {
	return predicate.ContributionRoom(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ContributionRoom {
	return predicate.ContributionRoom(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ContributionRoom {
	return predicate.ContributionRoom(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ContributionRoom {
	return predicate.ContributionRoom(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ContributionRoom {
	return predicate.ContributionRoom(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ContributionRoom {
	return predicate.ContributionRoom(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ContributionRoom {
	return predicate.ContributionRoom(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ContributionRoom {
	return predicate.ContributionRoom(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ContributionRoom {
	return predicate.ContributionRoom(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ContributionRoom {
	return predicate.ContributionRoom(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ContributionRoom {
	return predicate.ContributionRoom(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ContributionRoom {
	return predicate.ContributionRoom(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ContributionRoom {
	return predicate.ContributionRoom(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ContributionRoom {
	return predicate.ContributionRoom(sql.FieldLTE(FieldUpdatedAt, v))
}

// OwnerUserIDEQ applies the EQ predicate on the "owner_user_id" field.
func OwnerUserIDEQ(v int64) predicate.ContributionRoom {
	return predicate.ContributionRoom(sql.FieldEQ(FieldOwnerUserID, v))
}

// OwnerUserIDNEQ applies the NEQ predicate on the "owner_user_id" field.
func OwnerUserIDNEQ(v int64) predicate.ContributionRoom {
	return predicate.ContributionRoom(sql.FieldNEQ(FieldOwnerUserID, v))
}

// OwnerUserIDIn applies the In predicate on the "owner_user_id" field.
func OwnerUserIDIn(vs ...int64) predicate.ContributionRoom {
	return predicate.ContributionRoom(sql.FieldIn(FieldOwnerUserID, vs...))
}

// OwnerUserIDNotIn applies the NotIn predicate on the "owner_user_id" field.
func OwnerUserIDNotIn(vs ...int64) predicate.ContributionRoom {
	return predicate.ContributionRoom(sql.FieldNotIn(FieldOwnerUserID, vs...))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.ContributionRoom {
	return predicate.ContributionRoom(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.ContributionRoom {
	return predicate.ContributionRoom(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.ContributionRoom {
	return predicate.ContributionRoom(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.ContributionRoom {
	return predicate.ContributionRoom(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.ContributionRoom {
	return predicate.ContributionRoom(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.ContributionRoom {
	return predicate.ContributionRoom(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.ContributionRoom {
	return predicate.ContributionRoom(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.ContributionRoom {
	return predicate.ContributionRoom(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.ContributionRoom {
	return predicate.ContributionRoom(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.ContributionRoom {
	return predicate.ContributionRoom(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.ContributionRoom {
	return predicate.ContributionRoom(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.ContributionRoom {
	return predicate.ContributionRoom(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.ContributionRoom {
	return predicate.ContributionRoom(sql.FieldContainsFold(FieldName, v))
}

// ConsumerRateMultiplierEQ applies the EQ predicate on the "consumer_rate_multiplier" field.
func ConsumerRateMultiplierEQ(v float64) predicate.ContributionRoom {
	return predicate.ContributionRoom(sql.FieldEQ(FieldConsumerRateMultiplier, v))
}

// ConsumerRateMultiplierNEQ applies the NEQ predicate on the "consumer_rate_multiplier" field.
func ConsumerRateMultiplierNEQ(v float64) predicate.ContributionRoom {
	return predicate.ContributionRoom(sql.FieldNEQ(FieldConsumerRateMultiplier, v))
}

// ConsumerRateMultiplierIn applies the In predicate on the "consumer_rate_multiplier" field.
func ConsumerRateMultiplierIn(vs ...float64) predicate.ContributionRoom {
	return predicate.ContributionRoom(sql.FieldIn(FieldConsumerRateMultiplier, vs...))
}

// ConsumerRateMultiplierNotIn applies the NotIn predicate on the "consumer_rate_multiplier" field.
func ConsumerRateMultiplierNotIn(vs ...float64) predicate.ContributionRoom {
	return predicate.ContributionRoom(sql.FieldNotIn(FieldConsumerRateMultiplier, vs...))
}

// ConsumerRateMultiplierGT applies the GT predicate on the "consumer_rate_multiplier" field.
func ConsumerRateMultiplierGT(v float64) predicate.ContributionRoom {
	return predicate.ContributionRoom(sql.FieldGT(FieldConsumerRateMultiplier, v))
}

// ConsumerRateMultiplierGTE applies the GTE predicate on the "consumer_rate_multiplier" field.
func ConsumerRateMultiplierGTE(v float64) predicate.ContributionRoom {
	return predicate.ContributionRoom(sql.FieldGTE(FieldConsumerRateMultiplier, v))
}

// ConsumerRateMultiplierLT applies the LT predicate on the "consumer_rate_multiplier" field.
func ConsumerRateMultiplierLT(v float64) predicate.ContributionRoom {
	return predicate.ContributionRoom(sql.FieldLT(FieldConsumerRateMultiplier, v))
}

// ConsumerRateMultiplierLTE applies the LTE predicate on the "consumer_rate_multiplier" field.
func ConsumerRateMultiplierLTE(v float64) predicate.ContributionRoom {
	return predicate.ContributionRoom(sql.FieldLTE(FieldConsumerRateMultiplier, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.ContributionRoom {
	return predicate.ContributionRoom(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.ContributionRoom {
	return predicate.ContributionRoom(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.ContributionRoom {
	return predicate.ContributionRoom(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.ContributionRoom {
	return predicate.ContributionRoom(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.ContributionRoom {
	return predicate.ContributionRoom(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.ContributionRoom {
	return predicate.ContributionRoom(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.ContributionRoom {
	return predicate.ContributionRoom(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.ContributionRoom {
	return predicate.ContributionRoom(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.ContributionRoom {
	return predicate.ContributionRoom(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.ContributionRoom {
	return predicate.ContributionRoom(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.ContributionRoom {
	return predicate.ContributionRoom(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.ContributionRoom {
	return predicate.ContributionRoom(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.ContributionRoom {
	return predicate.ContributionRoom(sql.FieldContainsFold(FieldStatus, v))
}

// VisibilityEQ applies the EQ predicate on the "visibility" field.
func VisibilityEQ(v string) predicate.ContributionRoom {
	return predicate.ContributionRoom(sql.FieldEQ(FieldVisibility, v))
}

// VisibilityNEQ applies the NEQ predicate on the "visibility" field.
func VisibilityNEQ(v string) predicate.ContributionRoom {
	return predicate.ContributionRoom(sql.FieldNEQ(FieldVisibility, v))
}

// VisibilityIn applies the In predicate on the "visibility" field.
func VisibilityIn(vs ...string) predicate.ContributionRoom {
	return predicate.ContributionRoom(sql.FieldIn(FieldVisibility, vs...))
}

// VisibilityNotIn applies the NotIn predicate on the "visibility" field.
func VisibilityNotIn(vs ...string) predicate.ContributionRoom {
	return predicate.ContributionRoom(sql.FieldNotIn(FieldVisibility, vs...))
}

// VisibilityGT applies the GT predicate on the "visibility" field.
func VisibilityGT(v string) predicate.ContributionRoom {
	return predicate.ContributionRoom(sql.FieldGT(FieldVisibility, v))
}

// VisibilityGTE applies the GTE predicate on the "visibility" field.
func VisibilityGTE(v string) predicate.ContributionRoom {
	return predicate.ContributionRoom(sql.FieldGTE(FieldVisibility, v))
}

// VisibilityLT applies the LT predicate on the "visibility" field.
func VisibilityLT(v string) predicate.ContributionRoom {
	return predicate.ContributionRoom(sql.FieldLT(FieldVisibility, v))
}

// VisibilityLTE applies the LTE predicate on the "visibility" field.
func VisibilityLTE(v string) predicate.ContributionRoom {
	return predicate.ContributionRoom(sql.FieldLTE(FieldVisibility, v))
}

// VisibilityContains applies the Contains predicate on the "visibility" field.
func VisibilityContains(v string) predicate.ContributionRoom {
	return predicate.ContributionRoom(sql.FieldContains(FieldVisibility, v))
}

// VisibilityHasPrefix applies the HasPrefix predicate on the "visibility" field.
func VisibilityHasPrefix(v string) predicate.ContributionRoom {
	return predicate.ContributionRoom(sql.FieldHasPrefix(FieldVisibility, v))
}

// VisibilityHasSuffix applies the HasSuffix predicate on the "visibility" field.
func VisibilityHasSuffix(v string) predicate.ContributionRoom {
	return predicate.ContributionRoom(sql.FieldHasSuffix(FieldVisibility, v))
}

// VisibilityEqualFold applies the EqualFold predicate on the "visibility" field.
func VisibilityEqualFold(v string) predicate.ContributionRoom {
	return predicate.ContributionRoom(sql.FieldEqualFold(FieldVisibility, v))
}

// VisibilityContainsFold applies the ContainsFold predicate on the "visibility" field.
func VisibilityContainsFold(v string) predicate.ContributionRoom {
	return predicate.ContributionRoom(sql.FieldContainsFold(FieldVisibility, v))
}

// HasOwner applies the HasEdge predicate on the "owner" edge.
func HasOwner() predicate.ContributionRoom {
	return predicate.ContributionRoom(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, OwnerTable, OwnerColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasOwnerWith applies the HasEdge predicate on the "owner" edge with a given conditions (other predicates).
func HasOwnerWith(preds ...predicate.User) predicate.ContributionRoom {
	return predicate.ContributionRoom(func(s *sql.Selector) {
		step := newOwnerStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAccounts applies the HasEdge predicate on the "accounts" edge.
func HasAccounts() predicate.ContributionRoom {
	return predicate.ContributionRoom(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, AccountsTable, AccountsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAccountsWith applies the HasEdge predicate on the "accounts" edge with a given conditions (other predicates).
func HasAccountsWith(preds ...predicate.ContributionRoomAccount) predicate.ContributionRoom {
	return predicate.ContributionRoom(func(s *sql.Selector) {
		step := newAccountsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasPreferences applies the HasEdge predicate on the "preferences" edge.
func HasPreferences() predicate.ContributionRoom {
	return predicate.ContributionRoom(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, PreferencesTable, PreferencesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPreferencesWith applies the HasEdge predicate on the "preferences" edge with a given conditions (other predicates).
func HasPreferencesWith(preds ...predicate.UserContributionRoomPreference) predicate.ContributionRoom {
	return predicate.ContributionRoom(func(s *sql.Selector) {
		step := newPreferencesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ContributionRoom) predicate.ContributionRoom {
	return predicate.ContributionRoom(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ContributionRoom) predicate.ContributionRoom {
	return predicate.ContributionRoom(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ContributionRoom) predicate.ContributionRoom {
	return predicate.ContributionRoom(sql.NotPredicates(p))
}
