// 主从节点通信协议（docs/MASTER_RELAY_NODES.md 第 7 节，开发计划 2.3）。
//
// 连接按优先级分开（控制 / 事件 / 扣费 / 审核 / 日志），每类连接只调用对应的
// service。业务消息由后续工作包逐步加入：
//   - 新增 RPC 只加不改；
//   - 事件流的信封用 oneof，字段号按下面的保留区间分配，老版本收到不认识的类型
//     会忽略，不会出错。
//
// 生成：internal/relay/proto/generate.sh（不要手改生成代码）。

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.36.2
// source: sub2api/relay/v1/relay.proto

package relayv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 对端类型，与 transport.PeerClass 一一对应。
type PeerClass int32

const (
	PeerClass_PEER_CLASS_UNSPECIFIED PeerClass = 0
	// 没有出示证书（只能注册）。
	PeerClass_PEER_CLASS_ANONYMOUS PeerClass = 1
	// 用从节点长期密钥自签的证书（待激活、证书过期后的恢复）。
	PeerClass_PEER_CLASS_LONG_TERM PeerClass = 2
	// 主节点签发的主从通信证书（已激活节点的正常通信）。
	PeerClass_PEER_CLASS_ISSUED PeerClass = 3
)

// Enum value maps for PeerClass.
var (
	PeerClass_name = map[int32]string{
		0: "PEER_CLASS_UNSPECIFIED",
		1: "PEER_CLASS_ANONYMOUS",
		2: "PEER_CLASS_LONG_TERM",
		3: "PEER_CLASS_ISSUED",
	}
	PeerClass_value = map[string]int32{
		"PEER_CLASS_UNSPECIFIED": 0,
		"PEER_CLASS_ANONYMOUS":   1,
		"PEER_CLASS_LONG_TERM":   2,
		"PEER_CLASS_ISSUED":      3,
	}
)

func (x PeerClass) Enum() *PeerClass {
	p := new(PeerClass)
	*p = x
	return p
}

func (x PeerClass) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PeerClass) Descriptor() protoreflect.EnumDescriptor {
	return file_sub2api_relay_v1_relay_proto_enumTypes[0].Descriptor()
}

func (PeerClass) Type() protoreflect.EnumType {
	return &file_sub2api_relay_v1_relay_proto_enumTypes[0]
}

func (x PeerClass) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PeerClass.Descriptor instead.
func (PeerClass) EnumDescriptor() ([]byte, []int) {
	return file_sub2api_relay_v1_relay_proto_rawDescGZIP(), []int{0}
}

// 节点状态，与 relay_nodes.status 对应。
type NodeStatus int32

const (
	NodeStatus_NODE_STATUS_UNSPECIFIED NodeStatus = 0
	// 这把长期密钥没有注册过（或已被清除）。
	NodeStatus_NODE_STATUS_UNKNOWN  NodeStatus = 1
	NodeStatus_NODE_STATUS_PENDING  NodeStatus = 2
	NodeStatus_NODE_STATUS_ACTIVE   NodeStatus = 3
	NodeStatus_NODE_STATUS_DRAINING NodeStatus = 4
	NodeStatus_NODE_STATUS_DISABLED NodeStatus = 5
	NodeStatus_NODE_STATUS_REJECTED NodeStatus = 6
)

// Enum value maps for NodeStatus.
var (
	NodeStatus_name = map[int32]string{
		0: "NODE_STATUS_UNSPECIFIED",
		1: "NODE_STATUS_UNKNOWN",
		2: "NODE_STATUS_PENDING",
		3: "NODE_STATUS_ACTIVE",
		4: "NODE_STATUS_DRAINING",
		5: "NODE_STATUS_DISABLED",
		6: "NODE_STATUS_REJECTED",
	}
	NodeStatus_value = map[string]int32{
		"NODE_STATUS_UNSPECIFIED": 0,
		"NODE_STATUS_UNKNOWN":     1,
		"NODE_STATUS_PENDING":     2,
		"NODE_STATUS_ACTIVE":      3,
		"NODE_STATUS_DRAINING":    4,
		"NODE_STATUS_DISABLED":    5,
		"NODE_STATUS_REJECTED":    6,
	}
)

func (x NodeStatus) Enum() *NodeStatus {
	p := new(NodeStatus)
	*p = x
	return p
}

func (x NodeStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NodeStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_sub2api_relay_v1_relay_proto_enumTypes[1].Descriptor()
}

func (NodeStatus) Type() protoreflect.EnumType {
	return &file_sub2api_relay_v1_relay_proto_enumTypes[1]
}

func (x NodeStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NodeStatus.Descriptor instead.
func (NodeStatus) EnumDescriptor() ([]byte, []int) {
	return file_sub2api_relay_v1_relay_proto_rawDescGZIP(), []int{1}
}

type ProtocolVersion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Major         uint32                 `protobuf:"varint,1,opt,name=major,proto3" json:"major,omitempty"`
	Minor         uint32                 `protobuf:"varint,2,opt,name=minor,proto3" json:"minor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtocolVersion) Reset() {
	*x = ProtocolVersion{}
	mi := &file_sub2api_relay_v1_relay_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtocolVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtocolVersion) ProtoMessage() {}

func (x *ProtocolVersion) ProtoReflect() protoreflect.Message {
	mi := &file_sub2api_relay_v1_relay_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtocolVersion.ProtoReflect.Descriptor instead.
func (*ProtocolVersion) Descriptor() ([]byte, []int) {
	return file_sub2api_relay_v1_relay_proto_rawDescGZIP(), []int{0}
}

func (x *ProtocolVersion) GetMajor() uint32 {
	if x != nil {
		return x.Major
	}
	return 0
}

func (x *ProtocolVersion) GetMinor() uint32 {
	if x != nil {
		return x.Minor
	}
	return 0
}

type HelloRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Version        *ProtocolVersion       `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	ProgramVersion string                 `protobuf:"bytes,2,opt,name=program_version,json=programVersion,proto3" json:"program_version,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HelloRequest) Reset() {
	*x = HelloRequest{}
	mi := &file_sub2api_relay_v1_relay_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloRequest) ProtoMessage() {}

func (x *HelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sub2api_relay_v1_relay_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloRequest.ProtoReflect.Descriptor instead.
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return file_sub2api_relay_v1_relay_proto_rawDescGZIP(), []int{1}
}

func (x *HelloRequest) GetVersion() *ProtocolVersion {
	if x != nil {
		return x.Version
	}
	return nil
}

func (x *HelloRequest) GetProgramVersion() string {
	if x != nil {
		return x.ProgramVersion
	}
	return ""
}

type HelloResponse struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	MasterEpoch  string                 `protobuf:"bytes,1,opt,name=master_epoch,json=masterEpoch,proto3" json:"master_epoch,omitempty"`
	MinSupported *ProtocolVersion       `protobuf:"bytes,2,opt,name=min_supported,json=minSupported,proto3" json:"min_supported,omitempty"`
	Current      *ProtocolVersion       `protobuf:"bytes,3,opt,name=current,proto3" json:"current,omitempty"`
	PeerClass    PeerClass              `protobuf:"varint,4,opt,name=peer_class,json=peerClass,proto3,enum=sub2api.relay.v1.PeerClass" json:"peer_class,omitempty"`
	// 签发证书的对端：证书里的节点 ID。其他类型为 0。
	NodeId int64 `protobuf:"varint,5,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	// 主节点当前时间（Unix 毫秒），用于测时钟偏差（设计 7.4）。
	MasterTimeUnixMs int64 `protobuf:"varint,6,opt,name=master_time_unix_ms,json=masterTimeUnixMs,proto3" json:"master_time_unix_ms,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *HelloResponse) Reset() {
	*x = HelloResponse{}
	mi := &file_sub2api_relay_v1_relay_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloResponse) ProtoMessage() {}

func (x *HelloResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sub2api_relay_v1_relay_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloResponse.ProtoReflect.Descriptor instead.
func (*HelloResponse) Descriptor() ([]byte, []int) {
	return file_sub2api_relay_v1_relay_proto_rawDescGZIP(), []int{2}
}

func (x *HelloResponse) GetMasterEpoch() string {
	if x != nil {
		return x.MasterEpoch
	}
	return ""
}

func (x *HelloResponse) GetMinSupported() *ProtocolVersion {
	if x != nil {
		return x.MinSupported
	}
	return nil
}

func (x *HelloResponse) GetCurrent() *ProtocolVersion {
	if x != nil {
		return x.Current
	}
	return nil
}

func (x *HelloResponse) GetPeerClass() PeerClass {
	if x != nil {
		return x.PeerClass
	}
	return PeerClass_PEER_CLASS_UNSPECIFIED
}

func (x *HelloResponse) GetNodeId() int64 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *HelloResponse) GetMasterTimeUnixMs() int64 {
	if x != nil {
		return x.MasterTimeUnixMs
	}
	return 0
}

type RegisterRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Hostname       string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	ProgramVersion string                 `protobuf:"bytes,2,opt,name=program_version,json=programVersion,proto3" json:"program_version,omitempty"`
	SystemInfo     map[string]string      `protobuf:"bytes,3,rep,name=system_info,json=systemInfo,proto3" json:"system_info,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	DisplayName    string                 `protobuf:"bytes,4,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_sub2api_relay_v1_relay_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sub2api_relay_v1_relay_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_sub2api_relay_v1_relay_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *RegisterRequest) GetProgramVersion() string {
	if x != nil {
		return x.ProgramVersion
	}
	return ""
}

func (x *RegisterRequest) GetSystemInfo() map[string]string {
	if x != nil {
		return x.SystemInfo
	}
	return nil
}

func (x *RegisterRequest) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

type RegisterResponse struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Status NodeStatus             `protobuf:"varint,1,opt,name=status,proto3,enum=sub2api.relay.v1.NodeStatus" json:"status,omitempty"`
	// 主节点算出的长期密钥指纹，从节点把它和本机打印的对一下。
	KeyFingerprint string `protobuf:"bytes,2,opt,name=key_fingerprint,json=keyFingerprint,proto3" json:"key_fingerprint,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_sub2api_relay_v1_relay_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sub2api_relay_v1_relay_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_sub2api_relay_v1_relay_proto_rawDescGZIP(), []int{4}
}

func (x *RegisterResponse) GetStatus() NodeStatus {
	if x != nil {
		return x.Status
	}
	return NodeStatus_NODE_STATUS_UNSPECIFIED
}

func (x *RegisterResponse) GetKeyFingerprint() string {
	if x != nil {
		return x.KeyFingerprint
	}
	return ""
}

type NodeStatusRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ProgramVersion string                 `protobuf:"bytes,1,opt,name=program_version,json=programVersion,proto3" json:"program_version,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *NodeStatusRequest) Reset() {
	*x = NodeStatusRequest{}
	mi := &file_sub2api_relay_v1_relay_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeStatusRequest) ProtoMessage() {}

func (x *NodeStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sub2api_relay_v1_relay_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeStatusRequest.ProtoReflect.Descriptor instead.
func (*NodeStatusRequest) Descriptor() ([]byte, []int) {
	return file_sub2api_relay_v1_relay_proto_rawDescGZIP(), []int{5}
}

func (x *NodeStatusRequest) GetProgramVersion() string {
	if x != nil {
		return x.ProgramVersion
	}
	return ""
}

type NodeStatusResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Status              NodeStatus             `protobuf:"varint,1,opt,name=status,proto3,enum=sub2api.relay.v1.NodeStatus" json:"status,omitempty"`
	HeartbeatIntervalMs int64                  `protobuf:"varint,2,opt,name=heartbeat_interval_ms,json=heartbeatIntervalMs,proto3" json:"heartbeat_interval_ms,omitempty"`
	KeyFingerprint      string                 `protobuf:"bytes,3,opt,name=key_fingerprint,json=keyFingerprint,proto3" json:"key_fingerprint,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *NodeStatusResponse) Reset() {
	*x = NodeStatusResponse{}
	mi := &file_sub2api_relay_v1_relay_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeStatusResponse) ProtoMessage() {}

func (x *NodeStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sub2api_relay_v1_relay_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeStatusResponse.ProtoReflect.Descriptor instead.
func (*NodeStatusResponse) Descriptor() ([]byte, []int) {
	return file_sub2api_relay_v1_relay_proto_rawDescGZIP(), []int{6}
}

func (x *NodeStatusResponse) GetStatus() NodeStatus {
	if x != nil {
		return x.Status
	}
	return NodeStatus_NODE_STATUS_UNSPECIFIED
}

func (x *NodeStatusResponse) GetHeartbeatIntervalMs() int64 {
	if x != nil {
		return x.HeartbeatIntervalMs
	}
	return 0
}

func (x *NodeStatusResponse) GetKeyFingerprint() string {
	if x != nil {
		return x.KeyFingerprint
	}
	return ""
}

type CertificateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 新的 TLS 公钥（PKIX DER，Ed25519）。私钥只在从节点本机。
	TlsPublicKey []byte `protobuf:"bytes,1,opt,name=tls_public_key,json=tlsPublicKey,proto3" json:"tls_public_key,omitempty"`
	// 新的加密公钥（X25519，32 字节），用于上游凭据的二次加密（设计 7.1 第 4 条）。
	EncryptionPublicKey []byte `protobuf:"bytes,2,opt,name=encryption_public_key,json=encryptionPublicKey,proto3" json:"encryption_public_key,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CertificateRequest) Reset() {
	*x = CertificateRequest{}
	mi := &file_sub2api_relay_v1_relay_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CertificateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CertificateRequest) ProtoMessage() {}

func (x *CertificateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sub2api_relay_v1_relay_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CertificateRequest.ProtoReflect.Descriptor instead.
func (*CertificateRequest) Descriptor() ([]byte, []int) {
	return file_sub2api_relay_v1_relay_proto_rawDescGZIP(), []int{7}
}

func (x *CertificateRequest) GetTlsPublicKey() []byte {
	if x != nil {
		return x.TlsPublicKey
	}
	return nil
}

func (x *CertificateRequest) GetEncryptionPublicKey() []byte {
	if x != nil {
		return x.EncryptionPublicKey
	}
	return nil
}

type CertificateResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 签发的证书（DER）。
	Certificate    []byte `protobuf:"bytes,1,opt,name=certificate,proto3" json:"certificate,omitempty"`
	NotAfterUnixMs int64  `protobuf:"varint,2,opt,name=not_after_unix_ms,json=notAfterUnixMs,proto3" json:"not_after_unix_ms,omitempty"`
	NodeId         int64  `protobuf:"varint,3,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CertificateResponse) Reset() {
	*x = CertificateResponse{}
	mi := &file_sub2api_relay_v1_relay_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CertificateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CertificateResponse) ProtoMessage() {}

func (x *CertificateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sub2api_relay_v1_relay_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CertificateResponse.ProtoReflect.Descriptor instead.
func (*CertificateResponse) Descriptor() ([]byte, []int) {
	return file_sub2api_relay_v1_relay_proto_rawDescGZIP(), []int{8}
}

func (x *CertificateResponse) GetCertificate() []byte {
	if x != nil {
		return x.Certificate
	}
	return nil
}

func (x *CertificateResponse) GetNotAfterUnixMs() int64 {
	if x != nil {
		return x.NotAfterUnixMs
	}
	return 0
}

func (x *CertificateResponse) GetNodeId() int64 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_sub2api_relay_v1_relay_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sub2api_relay_v1_relay_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_sub2api_relay_v1_relay_proto_rawDescGZIP(), []int{9}
}

func (x *PingRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type PingResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Payload          []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	MasterTimeUnixMs int64                  `protobuf:"varint,2,opt,name=master_time_unix_ms,json=masterTimeUnixMs,proto3" json:"master_time_unix_ms,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_sub2api_relay_v1_relay_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sub2api_relay_v1_relay_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_sub2api_relay_v1_relay_proto_rawDescGZIP(), []int{10}
}

func (x *PingResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *PingResponse) GetMasterTimeUnixMs() int64 {
	if x != nil {
		return x.MasterTimeUnixMs
	}
	return 0
}

// 从节点 → 主节点的事件信封。
// 字段号：1~9 信封本身；10~99 从节点上报的事件；100~199 对主节点指令的回执；
// 200 起留给以后。
type NodeEnvelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Seq   uint64                 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	// Types that are valid to be assigned to Body:
	//
	//	*NodeEnvelope_Ping
	Body          isNodeEnvelope_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeEnvelope) Reset() {
	*x = NodeEnvelope{}
	mi := &file_sub2api_relay_v1_relay_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeEnvelope) ProtoMessage() {}

func (x *NodeEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_sub2api_relay_v1_relay_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeEnvelope.ProtoReflect.Descriptor instead.
func (*NodeEnvelope) Descriptor() ([]byte, []int) {
	return file_sub2api_relay_v1_relay_proto_rawDescGZIP(), []int{11}
}

func (x *NodeEnvelope) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *NodeEnvelope) GetBody() isNodeEnvelope_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *NodeEnvelope) GetPing() *EventPing {
	if x != nil {
		if x, ok := x.Body.(*NodeEnvelope_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

type isNodeEnvelope_Body interface {
	isNodeEnvelope_Body()
}

type NodeEnvelope_Ping struct {
	Ping *EventPing `protobuf:"bytes,10,opt,name=ping,proto3,oneof"`
}

func (*NodeEnvelope_Ping) isNodeEnvelope_Body() {}

type FetchConfigRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 从节点手里的版本；与当前一致时只回 unchanged。
	KnownVersion  string `protobuf:"bytes,1,opt,name=known_version,json=knownVersion,proto3" json:"known_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchConfigRequest) Reset() {
	*x = FetchConfigRequest{}
	mi := &file_sub2api_relay_v1_relay_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchConfigRequest) ProtoMessage() {}

func (x *FetchConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sub2api_relay_v1_relay_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchConfigRequest.ProtoReflect.Descriptor instead.
func (*FetchConfigRequest) Descriptor() ([]byte, []int) {
	return file_sub2api_relay_v1_relay_proto_rawDescGZIP(), []int{12}
}

func (x *FetchConfigRequest) GetKnownVersion() string {
	if x != nil {
		return x.KnownVersion
	}
	return ""
}

// 配置快照（设计 6 第二类、11.3）。版本是内容哈希：内容相同版本就相同，
// 主节点重启后也一致；从节点只比较是否相等。
type ConfigSnapshot struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Version   string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Unchanged bool                   `protobuf:"varint,2,opt,name=unchanged,proto3" json:"unchanged,omitempty"`
	// 按白名单下发的系统设置。白名单外的设置在从节点上读到空值；不含任何密钥。
	Settings map[string]string `protobuf:"bytes,3,rep,name=settings,proto3" json:"settings,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// 其他配置分段（错误透传规则、TLS 指纹等，内容为 JSON），由主节点按需登记。
	Sections map[string][]byte `protobuf:"bytes,4,rep,name=sections,proto3" json:"sections,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// 本节点配置与主从分流通用配置（JSON）。
	NodeConfig []byte `protobuf:"bytes,5,opt,name=node_config,json=nodeConfig,proto3" json:"node_config,omitempty"`
	// 主从通信根证书指纹（含轮换中的新根），从节点据此更新固定的指纹。
	RootFingerprints []string `protobuf:"bytes,6,rep,name=root_fingerprints,json=rootFingerprints,proto3" json:"root_fingerprints,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ConfigSnapshot) Reset() {
	*x = ConfigSnapshot{}
	mi := &file_sub2api_relay_v1_relay_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigSnapshot) ProtoMessage() {}

func (x *ConfigSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_sub2api_relay_v1_relay_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigSnapshot.ProtoReflect.Descriptor instead.
func (*ConfigSnapshot) Descriptor() ([]byte, []int) {
	return file_sub2api_relay_v1_relay_proto_rawDescGZIP(), []int{13}
}

func (x *ConfigSnapshot) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ConfigSnapshot) GetUnchanged() bool {
	if x != nil {
		return x.Unchanged
	}
	return false
}

func (x *ConfigSnapshot) GetSettings() map[string]string {
	if x != nil {
		return x.Settings
	}
	return nil
}

func (x *ConfigSnapshot) GetSections() map[string][]byte {
	if x != nil {
		return x.Sections
	}
	return nil
}

func (x *ConfigSnapshot) GetNodeConfig() []byte {
	if x != nil {
		return x.NodeConfig
	}
	return nil
}

func (x *ConfigSnapshot) GetRootFingerprints() []string {
	if x != nil {
		return x.RootFingerprints
	}
	return nil
}

// 配置变了，从节点拉取新版本。
type ConfigChanged struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigChanged) Reset() {
	*x = ConfigChanged{}
	mi := &file_sub2api_relay_v1_relay_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigChanged) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigChanged) ProtoMessage() {}

func (x *ConfigChanged) ProtoReflect() protoreflect.Message {
	mi := &file_sub2api_relay_v1_relay_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigChanged.ProtoReflect.Descriptor instead.
func (*ConfigChanged) Descriptor() ([]byte, []int) {
	return file_sub2api_relay_v1_relay_proto_rawDescGZIP(), []int{14}
}

func (x *ConfigChanged) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// 缓存作废（设计 6 第三类）。收到后从节点清掉对应缓存，下一个请求重新向主节点查询。
type Invalidation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// API Key 鉴权缓存键：原始 Key 的 SHA-256（十六进制）。新建 Key 也会发，
	// 用来清掉"查不到"的负缓存。
	ApiKeyHashes  []string `protobuf:"bytes,1,rep,name=api_key_hashes,json=apiKeyHashes,proto3" json:"api_key_hashes,omitempty"`
	UserIds       []int64  `protobuf:"varint,2,rep,packed,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	GroupIds      []int64  `protobuf:"varint,3,rep,packed,name=group_ids,json=groupIds,proto3" json:"group_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Invalidation) Reset() {
	*x = Invalidation{}
	mi := &file_sub2api_relay_v1_relay_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Invalidation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Invalidation) ProtoMessage() {}

func (x *Invalidation) ProtoReflect() protoreflect.Message {
	mi := &file_sub2api_relay_v1_relay_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Invalidation.ProtoReflect.Descriptor instead.
func (*Invalidation) Descriptor() ([]byte, []int) {
	return file_sub2api_relay_v1_relay_proto_rawDescGZIP(), []int{15}
}

func (x *Invalidation) GetApiKeyHashes() []string {
	if x != nil {
		return x.ApiKeyHashes
	}
	return nil
}

func (x *Invalidation) GetUserIds() []int64 {
	if x != nil {
		return x.UserIds
	}
	return nil
}

func (x *Invalidation) GetGroupIds() []int64 {
	if x != nil {
		return x.GroupIds
	}
	return nil
}

// 主节点 → 从节点的事件信封。
// 字段号：1~9 信封本身；10~99 主节点指令；100~199 对从节点事件的回执；200 起留给以后。
type MasterEnvelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Seq   uint64                 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	// Types that are valid to be assigned to Body:
	//
	//	*MasterEnvelope_Ping
	//	*MasterEnvelope_ConfigChanged
	//	*MasterEnvelope_Invalidation
	Body          isMasterEnvelope_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MasterEnvelope) Reset() {
	*x = MasterEnvelope{}
	mi := &file_sub2api_relay_v1_relay_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MasterEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MasterEnvelope) ProtoMessage() {}

func (x *MasterEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_sub2api_relay_v1_relay_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MasterEnvelope.ProtoReflect.Descriptor instead.
func (*MasterEnvelope) Descriptor() ([]byte, []int) {
	return file_sub2api_relay_v1_relay_proto_rawDescGZIP(), []int{16}
}

func (x *MasterEnvelope) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *MasterEnvelope) GetBody() isMasterEnvelope_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *MasterEnvelope) GetPing() *EventPing {
	if x != nil {
		if x, ok := x.Body.(*MasterEnvelope_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

func (x *MasterEnvelope) GetConfigChanged() *ConfigChanged {
	if x != nil {
		if x, ok := x.Body.(*MasterEnvelope_ConfigChanged); ok {
			return x.ConfigChanged
		}
	}
	return nil
}

func (x *MasterEnvelope) GetInvalidation() *Invalidation {
	if x != nil {
		if x, ok := x.Body.(*MasterEnvelope_Invalidation); ok {
			return x.Invalidation
		}
	}
	return nil
}

type isMasterEnvelope_Body interface {
	isMasterEnvelope_Body()
}

type MasterEnvelope_Ping struct {
	Ping *EventPing `protobuf:"bytes,10,opt,name=ping,proto3,oneof"`
}

type MasterEnvelope_ConfigChanged struct {
	ConfigChanged *ConfigChanged `protobuf:"bytes,11,opt,name=config_changed,json=configChanged,proto3,oneof"`
}

type MasterEnvelope_Invalidation struct {
	Invalidation *Invalidation `protobuf:"bytes,12,opt,name=invalidation,proto3,oneof"`
}

func (*MasterEnvelope_Ping) isMasterEnvelope_Body() {}

func (*MasterEnvelope_ConfigChanged) isMasterEnvelope_Body() {}

func (*MasterEnvelope_Invalidation) isMasterEnvelope_Body() {}

type EventPing struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventPing) Reset() {
	*x = EventPing{}
	mi := &file_sub2api_relay_v1_relay_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventPing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventPing) ProtoMessage() {}

func (x *EventPing) ProtoReflect() protoreflect.Message {
	mi := &file_sub2api_relay_v1_relay_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventPing.ProtoReflect.Descriptor instead.
func (*EventPing) Descriptor() ([]byte, []int) {
	return file_sub2api_relay_v1_relay_proto_rawDescGZIP(), []int{17}
}

func (x *EventPing) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_sub2api_relay_v1_relay_proto protoreflect.FileDescriptor

const file_sub2api_relay_v1_relay_proto_rawDesc = "" +
	"\n" +
	"\x1csub2api/relay/v1/relay.proto\x12\x10sub2api.relay.v1\"=\n" +
	"\x0fProtocolVersion\x12\x14\n" +
	"\x05major\x18\x01 \x01(\rR\x05major\x12\x14\n" +
	"\x05minor\x18\x02 \x01(\rR\x05minor\"t\n" +
	"\fHelloRequest\x12;\n" +
	"\aversion\x18\x01 \x01(\v2!.sub2api.relay.v1.ProtocolVersionR\aversion\x12'\n" +
	"\x0fprogram_version\x18\x02 \x01(\tR\x0eprogramVersion\"\xbb\x02\n" +
	"\rHelloResponse\x12!\n" +
	"\fmaster_epoch\x18\x01 \x01(\tR\vmasterEpoch\x12F\n" +
	"\rmin_supported\x18\x02 \x01(\v2!.sub2api.relay.v1.ProtocolVersionR\fminSupported\x12;\n" +
	"\acurrent\x18\x03 \x01(\v2!.sub2api.relay.v1.ProtocolVersionR\acurrent\x12:\n" +
	"\n" +
	"peer_class\x18\x04 \x01(\x0e2\x1b.sub2api.relay.v1.PeerClassR\tpeerClass\x12\x17\n" +
	"\anode_id\x18\x05 \x01(\x03R\x06nodeId\x12-\n" +
	"\x13master_time_unix_ms\x18\x06 \x01(\x03R\x10masterTimeUnixMs\"\x8c\x02\n" +
	"\x0fRegisterRequest\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12'\n" +
	"\x0fprogram_version\x18\x02 \x01(\tR\x0eprogramVersion\x12R\n" +
	"\vsystem_info\x18\x03 \x03(\v21.sub2api.relay.v1.RegisterRequest.SystemInfoEntryR\n" +
	"systemInfo\x12!\n" +
	"\fdisplay_name\x18\x04 \x01(\tR\vdisplayName\x1a=\n" +
	"\x0fSystemInfoEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"q\n" +
	"\x10RegisterResponse\x124\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1c.sub2api.relay.v1.NodeStatusR\x06status\x12'\n" +
	"\x0fkey_fingerprint\x18\x02 \x01(\tR\x0ekeyFingerprint\"<\n" +
	"\x11NodeStatusRequest\x12'\n" +
	"\x0fprogram_version\x18\x01 \x01(\tR\x0eprogramVersion\"\xa7\x01\n" +
	"\x12NodeStatusResponse\x124\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1c.sub2api.relay.v1.NodeStatusR\x06status\x122\n" +
	"\x15heartbeat_interval_ms\x18\x02 \x01(\x03R\x13heartbeatIntervalMs\x12'\n" +
	"\x0fkey_fingerprint\x18\x03 \x01(\tR\x0ekeyFingerprint\"n\n" +
	"\x12CertificateRequest\x12$\n" +
	"\x0etls_public_key\x18\x01 \x01(\fR\ftlsPublicKey\x122\n" +
	"\x15encryption_public_key\x18\x02 \x01(\fR\x13encryptionPublicKey\"{\n" +
	"\x13CertificateResponse\x12 \n" +
	"\vcertificate\x18\x01 \x01(\fR\vcertificate\x12)\n" +
	"\x11not_after_unix_ms\x18\x02 \x01(\x03R\x0enotAfterUnixMs\x12\x17\n" +
	"\anode_id\x18\x03 \x01(\x03R\x06nodeId\"'\n" +
	"\vPingRequest\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\"W\n" +
	"\fPingResponse\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\x12-\n" +
	"\x13master_time_unix_ms\x18\x02 \x01(\x03R\x10masterTimeUnixMs\"[\n" +
	"\fNodeEnvelope\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x04R\x03seq\x121\n" +
	"\x04ping\x18\n" +
	" \x01(\v2\x1b.sub2api.relay.v1.EventPingH\x00R\x04pingB\x06\n" +
	"\x04body\"9\n" +
	"\x12FetchConfigRequest\x12#\n" +
	"\rknown_version\x18\x01 \x01(\tR\fknownVersion\"\xa8\x03\n" +
	"\x0eConfigSnapshot\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x1c\n" +
	"\tunchanged\x18\x02 \x01(\bR\tunchanged\x12J\n" +
	"\bsettings\x18\x03 \x03(\v2..sub2api.relay.v1.ConfigSnapshot.SettingsEntryR\bsettings\x12J\n" +
	"\bsections\x18\x04 \x03(\v2..sub2api.relay.v1.ConfigSnapshot.SectionsEntryR\bsections\x12\x1f\n" +
	"\vnode_config\x18\x05 \x01(\fR\n" +
	"nodeConfig\x12+\n" +
	"\x11root_fingerprints\x18\x06 \x03(\tR\x10rootFingerprints\x1a;\n" +
	"\rSettingsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a;\n" +
	"\rSectionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\")\n" +
	"\rConfigChanged\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\"l\n" +
	"\fInvalidation\x12$\n" +
	"\x0eapi_key_hashes\x18\x01 \x03(\tR\fapiKeyHashes\x12\x19\n" +
	"\buser_ids\x18\x02 \x03(\x03R\auserIds\x12\x1b\n" +
	"\tgroup_ids\x18\x03 \x03(\x03R\bgroupIds\"\xed\x01\n" +
	"\x0eMasterEnvelope\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x04R\x03seq\x121\n" +
	"\x04ping\x18\n" +
	" \x01(\v2\x1b.sub2api.relay.v1.EventPingH\x00R\x04ping\x12H\n" +
	"\x0econfig_changed\x18\v \x01(\v2\x1f.sub2api.relay.v1.ConfigChangedH\x00R\rconfigChanged\x12D\n" +
	"\finvalidation\x18\f \x01(\v2\x1e.sub2api.relay.v1.InvalidationH\x00R\finvalidationB\x06\n" +
	"\x04body\"%\n" +
	"\tEventPing\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload*r\n" +
	"\tPeerClass\x12\x1a\n" +
	"\x16PEER_CLASS_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14PEER_CLASS_ANONYMOUS\x10\x01\x12\x18\n" +
	"\x14PEER_CLASS_LONG_TERM\x10\x02\x12\x15\n" +
	"\x11PEER_CLASS_ISSUED\x10\x03*\xc1\x01\n" +
	"\n" +
	"NodeStatus\x12\x1b\n" +
	"\x17NODE_STATUS_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13NODE_STATUS_UNKNOWN\x10\x01\x12\x17\n" +
	"\x13NODE_STATUS_PENDING\x10\x02\x12\x16\n" +
	"\x12NODE_STATUS_ACTIVE\x10\x03\x12\x18\n" +
	"\x14NODE_STATUS_DRAINING\x10\x04\x12\x18\n" +
	"\x14NODE_STATUS_DISABLED\x10\x05\x12\x18\n" +
	"\x14NODE_STATUS_REJECTED\x10\x062\xca\x03\n" +
	"\x0fRelayEnrollment\x12H\n" +
	"\x05Hello\x12\x1e.sub2api.relay.v1.HelloRequest\x1a\x1f.sub2api.relay.v1.HelloResponse\x12Q\n" +
	"\bRegister\x12!.sub2api.relay.v1.RegisterRequest\x1a\".sub2api.relay.v1.RegisterResponse\x12W\n" +
	"\n" +
	"NodeStatus\x12#.sub2api.relay.v1.NodeStatusRequest\x1a$.sub2api.relay.v1.NodeStatusResponse\x12`\n" +
	"\x11ObtainCertificate\x12$.sub2api.relay.v1.CertificateRequest\x1a%.sub2api.relay.v1.CertificateResponse\x12_\n" +
	"\x10RenewCertificate\x12$.sub2api.relay.v1.CertificateRequest\x1a%.sub2api.relay.v1.CertificateResponse2\xac\x01\n" +
	"\fRelayControl\x12E\n" +
	"\x04Ping\x12\x1d.sub2api.relay.v1.PingRequest\x1a\x1e.sub2api.relay.v1.PingResponse\x12U\n" +
	"\vFetchConfig\x12$.sub2api.relay.v1.FetchConfigRequest\x1a .sub2api.relay.v1.ConfigSnapshot2]\n" +
	"\vRelayEvents\x12N\n" +
	"\x06Stream\x12\x1e.sub2api.relay.v1.NodeEnvelope\x1a .sub2api.relay.v1.MasterEnvelope(\x010\x01BBZ@github.com/Wei-Shaw/sub2api/internal/relay/proto/relayv1;relayv1b\x06proto3"

var (
	file_sub2api_relay_v1_relay_proto_rawDescOnce sync.Once
	file_sub2api_relay_v1_relay_proto_rawDescData []byte
)

func file_sub2api_relay_v1_relay_proto_rawDescGZIP() []byte {
	file_sub2api_relay_v1_relay_proto_rawDescOnce.Do(func() {
		file_sub2api_relay_v1_relay_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sub2api_relay_v1_relay_proto_rawDesc), len(file_sub2api_relay_v1_relay_proto_rawDesc)))
	})
	return file_sub2api_relay_v1_relay_proto_rawDescData
}

var file_sub2api_relay_v1_relay_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_sub2api_relay_v1_relay_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_sub2api_relay_v1_relay_proto_goTypes = []any{
	(PeerClass)(0),              // 0: sub2api.relay.v1.PeerClass
	(NodeStatus)(0),             // 1: sub2api.relay.v1.NodeStatus
	(*ProtocolVersion)(nil),     // 2: sub2api.relay.v1.ProtocolVersion
	(*HelloRequest)(nil),        // 3: sub2api.relay.v1.HelloRequest
	(*HelloResponse)(nil),       // 4: sub2api.relay.v1.HelloResponse
	(*RegisterRequest)(nil),     // 5: sub2api.relay.v1.RegisterRequest
	(*RegisterResponse)(nil),    // 6: sub2api.relay.v1.RegisterResponse
	(*NodeStatusRequest)(nil),   // 7: sub2api.relay.v1.NodeStatusRequest
	(*NodeStatusResponse)(nil),  // 8: sub2api.relay.v1.NodeStatusResponse
	(*CertificateRequest)(nil),  // 9: sub2api.relay.v1.CertificateRequest
	(*CertificateResponse)(nil), // 10: sub2api.relay.v1.CertificateResponse
	(*PingRequest)(nil),         // 11: sub2api.relay.v1.PingRequest
	(*PingResponse)(nil),        // 12: sub2api.relay.v1.PingResponse
	(*NodeEnvelope)(nil),        // 13: sub2api.relay.v1.NodeEnvelope
	(*FetchConfigRequest)(nil),  // 14: sub2api.relay.v1.FetchConfigRequest
	(*ConfigSnapshot)(nil),      // 15: sub2api.relay.v1.ConfigSnapshot
	(*ConfigChanged)(nil),       // 16: sub2api.relay.v1.ConfigChanged
	(*Invalidation)(nil),        // 17: sub2api.relay.v1.Invalidation
	(*MasterEnvelope)(nil),      // 18: sub2api.relay.v1.MasterEnvelope
	(*EventPing)(nil),           // 19: sub2api.relay.v1.EventPing
	nil,                         // 20: sub2api.relay.v1.RegisterRequest.SystemInfoEntry
	nil,                         // 21: sub2api.relay.v1.ConfigSnapshot.SettingsEntry
	nil,                         // 22: sub2api.relay.v1.ConfigSnapshot.SectionsEntry
}
var file_sub2api_relay_v1_relay_proto_depIdxs = []int32{
	2,  // 0: sub2api.relay.v1.HelloRequest.version:type_name -> sub2api.relay.v1.ProtocolVersion
	2,  // 1: sub2api.relay.v1.HelloResponse.min_supported:type_name -> sub2api.relay.v1.ProtocolVersion
	2,  // 2: sub2api.relay.v1.HelloResponse.current:type_name -> sub2api.relay.v1.ProtocolVersion
	0,  // 3: sub2api.relay.v1.HelloResponse.peer_class:type_name -> sub2api.relay.v1.PeerClass
	20, // 4: sub2api.relay.v1.RegisterRequest.system_info:type_name -> sub2api.relay.v1.RegisterRequest.SystemInfoEntry
	1,  // 5: sub2api.relay.v1.RegisterResponse.status:type_name -> sub2api.relay.v1.NodeStatus
	1,  // 6: sub2api.relay.v1.NodeStatusResponse.status:type_name -> sub2api.relay.v1.NodeStatus
	19, // 7: sub2api.relay.v1.NodeEnvelope.ping:type_name -> sub2api.relay.v1.EventPing
	21, // 8: sub2api.relay.v1.ConfigSnapshot.settings:type_name -> sub2api.relay.v1.ConfigSnapshot.SettingsEntry
	22, // 9: sub2api.relay.v1.ConfigSnapshot.sections:type_name -> sub2api.relay.v1.ConfigSnapshot.SectionsEntry
	19, // 10: sub2api.relay.v1.MasterEnvelope.ping:type_name -> sub2api.relay.v1.EventPing
	16, // 11: sub2api.relay.v1.MasterEnvelope.config_changed:type_name -> sub2api.relay.v1.ConfigChanged
	17, // 12: sub2api.relay.v1.MasterEnvelope.invalidation:type_name -> sub2api.relay.v1.Invalidation
	3,  // 13: sub2api.relay.v1.RelayEnrollment.Hello:input_type -> sub2api.relay.v1.HelloRequest
	5,  // 14: sub2api.relay.v1.RelayEnrollment.Register:input_type -> sub2api.relay.v1.RegisterRequest
	7,  // 15: sub2api.relay.v1.RelayEnrollment.NodeStatus:input_type -> sub2api.relay.v1.NodeStatusRequest
	9,  // 16: sub2api.relay.v1.RelayEnrollment.ObtainCertificate:input_type -> sub2api.relay.v1.CertificateRequest
	9,  // 17: sub2api.relay.v1.RelayEnrollment.RenewCertificate:input_type -> sub2api.relay.v1.CertificateRequest
	11, // 18: sub2api.relay.v1.RelayControl.Ping:input_type -> sub2api.relay.v1.PingRequest
	14, // 19: sub2api.relay.v1.RelayControl.FetchConfig:input_type -> sub2api.relay.v1.FetchConfigRequest
	13, // 20: sub2api.relay.v1.RelayEvents.Stream:input_type -> sub2api.relay.v1.NodeEnvelope
	4,  // 21: sub2api.relay.v1.RelayEnrollment.Hello:output_type -> sub2api.relay.v1.HelloResponse
	6,  // 22: sub2api.relay.v1.RelayEnrollment.Register:output_type -> sub2api.relay.v1.RegisterResponse
	8,  // 23: sub2api.relay.v1.RelayEnrollment.NodeStatus:output_type -> sub2api.relay.v1.NodeStatusResponse
	10, // 24: sub2api.relay.v1.RelayEnrollment.ObtainCertificate:output_type -> sub2api.relay.v1.CertificateResponse
	10, // 25: sub2api.relay.v1.RelayEnrollment.RenewCertificate:output_type -> sub2api.relay.v1.CertificateResponse
	12, // 26: sub2api.relay.v1.RelayControl.Ping:output_type -> sub2api.relay.v1.PingResponse
	15, // 27: sub2api.relay.v1.RelayControl.FetchConfig:output_type -> sub2api.relay.v1.ConfigSnapshot
	18, // 28: sub2api.relay.v1.RelayEvents.Stream:output_type -> sub2api.relay.v1.MasterEnvelope
	21, // [21:29] is the sub-list for method output_type
	13, // [13:21] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_sub2api_relay_v1_relay_proto_init() }
func file_sub2api_relay_v1_relay_proto_init() {
	if File_sub2api_relay_v1_relay_proto != nil {
		return
	}
	file_sub2api_relay_v1_relay_proto_msgTypes[11].OneofWrappers = []any{
		(*NodeEnvelope_Ping)(nil),
	}
	file_sub2api_relay_v1_relay_proto_msgTypes[16].OneofWrappers = []any{
		(*MasterEnvelope_Ping)(nil),
		(*MasterEnvelope_ConfigChanged)(nil),
		(*MasterEnvelope_Invalidation)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sub2api_relay_v1_relay_proto_rawDesc), len(file_sub2api_relay_v1_relay_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_sub2api_relay_v1_relay_proto_goTypes,
		DependencyIndexes: file_sub2api_relay_v1_relay_proto_depIdxs,
		EnumInfos:         file_sub2api_relay_v1_relay_proto_enumTypes,
		MessageInfos:      file_sub2api_relay_v1_relay_proto_msgTypes,
	}.Build()
	File_sub2api_relay_v1_relay_proto = out.File
	file_sub2api_relay_v1_relay_proto_goTypes = nil
	file_sub2api_relay_v1_relay_proto_depIdxs = nil
}
