// 主从节点通信协议（docs/MASTER_RELAY_NODES.md 第 7 节，开发计划 2.3）。
//
// 连接按优先级分开（控制 / 事件 / 扣费 / 审核 / 日志），每类连接只调用对应的
// service。业务消息由后续工作包逐步加入：
//   - 新增 RPC 只加不改；
//   - 事件流的信封用 oneof，字段号按下面的保留区间分配，老版本收到不认识的类型
//     会忽略，不会出错。
//
// 生成：internal/relay/proto/generate.sh（不要手改生成代码）。

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.36.2
// source: sub2api/relay/v1/relay.proto

package relayv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 对端类型，与 transport.PeerClass 一一对应。
type PeerClass int32

const (
	PeerClass_PEER_CLASS_UNSPECIFIED PeerClass = 0
	// 没有出示证书（只能注册）。
	PeerClass_PEER_CLASS_ANONYMOUS PeerClass = 1
	// 用从节点长期密钥自签的证书（待激活、证书过期后的恢复）。
	PeerClass_PEER_CLASS_LONG_TERM PeerClass = 2
	// 主节点签发的主从通信证书（已激活节点的正常通信）。
	PeerClass_PEER_CLASS_ISSUED PeerClass = 3
)

// Enum value maps for PeerClass.
var (
	PeerClass_name = map[int32]string{
		0: "PEER_CLASS_UNSPECIFIED",
		1: "PEER_CLASS_ANONYMOUS",
		2: "PEER_CLASS_LONG_TERM",
		3: "PEER_CLASS_ISSUED",
	}
	PeerClass_value = map[string]int32{
		"PEER_CLASS_UNSPECIFIED": 0,
		"PEER_CLASS_ANONYMOUS":   1,
		"PEER_CLASS_LONG_TERM":   2,
		"PEER_CLASS_ISSUED":      3,
	}
)

func (x PeerClass) Enum() *PeerClass {
	p := new(PeerClass)
	*p = x
	return p
}

func (x PeerClass) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PeerClass) Descriptor() protoreflect.EnumDescriptor {
	return file_sub2api_relay_v1_relay_proto_enumTypes[0].Descriptor()
}

func (PeerClass) Type() protoreflect.EnumType {
	return &file_sub2api_relay_v1_relay_proto_enumTypes[0]
}

func (x PeerClass) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PeerClass.Descriptor instead.
func (PeerClass) EnumDescriptor() ([]byte, []int) {
	return file_sub2api_relay_v1_relay_proto_rawDescGZIP(), []int{0}
}

type ProtocolVersion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Major         uint32                 `protobuf:"varint,1,opt,name=major,proto3" json:"major,omitempty"`
	Minor         uint32                 `protobuf:"varint,2,opt,name=minor,proto3" json:"minor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtocolVersion) Reset() {
	*x = ProtocolVersion{}
	mi := &file_sub2api_relay_v1_relay_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtocolVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtocolVersion) ProtoMessage() {}

func (x *ProtocolVersion) ProtoReflect() protoreflect.Message {
	mi := &file_sub2api_relay_v1_relay_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtocolVersion.ProtoReflect.Descriptor instead.
func (*ProtocolVersion) Descriptor() ([]byte, []int) {
	return file_sub2api_relay_v1_relay_proto_rawDescGZIP(), []int{0}
}

func (x *ProtocolVersion) GetMajor() uint32 {
	if x != nil {
		return x.Major
	}
	return 0
}

func (x *ProtocolVersion) GetMinor() uint32 {
	if x != nil {
		return x.Minor
	}
	return 0
}

type HelloRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Version        *ProtocolVersion       `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	ProgramVersion string                 `protobuf:"bytes,2,opt,name=program_version,json=programVersion,proto3" json:"program_version,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HelloRequest) Reset() {
	*x = HelloRequest{}
	mi := &file_sub2api_relay_v1_relay_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloRequest) ProtoMessage() {}

func (x *HelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sub2api_relay_v1_relay_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloRequest.ProtoReflect.Descriptor instead.
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return file_sub2api_relay_v1_relay_proto_rawDescGZIP(), []int{1}
}

func (x *HelloRequest) GetVersion() *ProtocolVersion {
	if x != nil {
		return x.Version
	}
	return nil
}

func (x *HelloRequest) GetProgramVersion() string {
	if x != nil {
		return x.ProgramVersion
	}
	return ""
}

type HelloResponse struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	MasterEpoch  string                 `protobuf:"bytes,1,opt,name=master_epoch,json=masterEpoch,proto3" json:"master_epoch,omitempty"`
	MinSupported *ProtocolVersion       `protobuf:"bytes,2,opt,name=min_supported,json=minSupported,proto3" json:"min_supported,omitempty"`
	Current      *ProtocolVersion       `protobuf:"bytes,3,opt,name=current,proto3" json:"current,omitempty"`
	PeerClass    PeerClass              `protobuf:"varint,4,opt,name=peer_class,json=peerClass,proto3,enum=sub2api.relay.v1.PeerClass" json:"peer_class,omitempty"`
	// 签发证书的对端：证书里的节点 ID。其他类型为 0。
	NodeId int64 `protobuf:"varint,5,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	// 主节点当前时间（Unix 毫秒），用于测时钟偏差（设计 7.4）。
	MasterTimeUnixMs int64 `protobuf:"varint,6,opt,name=master_time_unix_ms,json=masterTimeUnixMs,proto3" json:"master_time_unix_ms,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *HelloResponse) Reset() {
	*x = HelloResponse{}
	mi := &file_sub2api_relay_v1_relay_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloResponse) ProtoMessage() {}

func (x *HelloResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sub2api_relay_v1_relay_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloResponse.ProtoReflect.Descriptor instead.
func (*HelloResponse) Descriptor() ([]byte, []int) {
	return file_sub2api_relay_v1_relay_proto_rawDescGZIP(), []int{2}
}

func (x *HelloResponse) GetMasterEpoch() string {
	if x != nil {
		return x.MasterEpoch
	}
	return ""
}

func (x *HelloResponse) GetMinSupported() *ProtocolVersion {
	if x != nil {
		return x.MinSupported
	}
	return nil
}

func (x *HelloResponse) GetCurrent() *ProtocolVersion {
	if x != nil {
		return x.Current
	}
	return nil
}

func (x *HelloResponse) GetPeerClass() PeerClass {
	if x != nil {
		return x.PeerClass
	}
	return PeerClass_PEER_CLASS_UNSPECIFIED
}

func (x *HelloResponse) GetNodeId() int64 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *HelloResponse) GetMasterTimeUnixMs() int64 {
	if x != nil {
		return x.MasterTimeUnixMs
	}
	return 0
}

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_sub2api_relay_v1_relay_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sub2api_relay_v1_relay_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_sub2api_relay_v1_relay_proto_rawDescGZIP(), []int{3}
}

func (x *PingRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type PingResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Payload          []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	MasterTimeUnixMs int64                  `protobuf:"varint,2,opt,name=master_time_unix_ms,json=masterTimeUnixMs,proto3" json:"master_time_unix_ms,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_sub2api_relay_v1_relay_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sub2api_relay_v1_relay_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_sub2api_relay_v1_relay_proto_rawDescGZIP(), []int{4}
}

func (x *PingResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *PingResponse) GetMasterTimeUnixMs() int64 {
	if x != nil {
		return x.MasterTimeUnixMs
	}
	return 0
}

// 从节点 → 主节点的事件信封。
// 字段号：1~9 信封本身；10~99 从节点上报的事件；100~199 对主节点指令的回执；
// 200 起留给以后。
type NodeEnvelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Seq   uint64                 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	// Types that are valid to be assigned to Body:
	//
	//	*NodeEnvelope_Ping
	Body          isNodeEnvelope_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeEnvelope) Reset() {
	*x = NodeEnvelope{}
	mi := &file_sub2api_relay_v1_relay_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeEnvelope) ProtoMessage() {}

func (x *NodeEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_sub2api_relay_v1_relay_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeEnvelope.ProtoReflect.Descriptor instead.
func (*NodeEnvelope) Descriptor() ([]byte, []int) {
	return file_sub2api_relay_v1_relay_proto_rawDescGZIP(), []int{5}
}

func (x *NodeEnvelope) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *NodeEnvelope) GetBody() isNodeEnvelope_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *NodeEnvelope) GetPing() *EventPing {
	if x != nil {
		if x, ok := x.Body.(*NodeEnvelope_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

type isNodeEnvelope_Body interface {
	isNodeEnvelope_Body()
}

type NodeEnvelope_Ping struct {
	Ping *EventPing `protobuf:"bytes,10,opt,name=ping,proto3,oneof"`
}

func (*NodeEnvelope_Ping) isNodeEnvelope_Body() {}

// 主节点 → 从节点的事件信封。
// 字段号：1~9 信封本身；10~99 主节点指令；100~199 对从节点事件的回执；200 起留给以后。
type MasterEnvelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Seq   uint64                 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	// Types that are valid to be assigned to Body:
	//
	//	*MasterEnvelope_Ping
	Body          isMasterEnvelope_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MasterEnvelope) Reset() {
	*x = MasterEnvelope{}
	mi := &file_sub2api_relay_v1_relay_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MasterEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MasterEnvelope) ProtoMessage() {}

func (x *MasterEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_sub2api_relay_v1_relay_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MasterEnvelope.ProtoReflect.Descriptor instead.
func (*MasterEnvelope) Descriptor() ([]byte, []int) {
	return file_sub2api_relay_v1_relay_proto_rawDescGZIP(), []int{6}
}

func (x *MasterEnvelope) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *MasterEnvelope) GetBody() isMasterEnvelope_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *MasterEnvelope) GetPing() *EventPing {
	if x != nil {
		if x, ok := x.Body.(*MasterEnvelope_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

type isMasterEnvelope_Body interface {
	isMasterEnvelope_Body()
}

type MasterEnvelope_Ping struct {
	Ping *EventPing `protobuf:"bytes,10,opt,name=ping,proto3,oneof"`
}

func (*MasterEnvelope_Ping) isMasterEnvelope_Body() {}

type EventPing struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventPing) Reset() {
	*x = EventPing{}
	mi := &file_sub2api_relay_v1_relay_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventPing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventPing) ProtoMessage() {}

func (x *EventPing) ProtoReflect() protoreflect.Message {
	mi := &file_sub2api_relay_v1_relay_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventPing.ProtoReflect.Descriptor instead.
func (*EventPing) Descriptor() ([]byte, []int) {
	return file_sub2api_relay_v1_relay_proto_rawDescGZIP(), []int{7}
}

func (x *EventPing) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_sub2api_relay_v1_relay_proto protoreflect.FileDescriptor

const file_sub2api_relay_v1_relay_proto_rawDesc = "" +
	"\n" +
	"\x1csub2api/relay/v1/relay.proto\x12\x10sub2api.relay.v1\"=\n" +
	"\x0fProtocolVersion\x12\x14\n" +
	"\x05major\x18\x01 \x01(\rR\x05major\x12\x14\n" +
	"\x05minor\x18\x02 \x01(\rR\x05minor\"t\n" +
	"\fHelloRequest\x12;\n" +
	"\aversion\x18\x01 \x01(\v2!.sub2api.relay.v1.ProtocolVersionR\aversion\x12'\n" +
	"\x0fprogram_version\x18\x02 \x01(\tR\x0eprogramVersion\"\xbb\x02\n" +
	"\rHelloResponse\x12!\n" +
	"\fmaster_epoch\x18\x01 \x01(\tR\vmasterEpoch\x12F\n" +
	"\rmin_supported\x18\x02 \x01(\v2!.sub2api.relay.v1.ProtocolVersionR\fminSupported\x12;\n" +
	"\acurrent\x18\x03 \x01(\v2!.sub2api.relay.v1.ProtocolVersionR\acurrent\x12:\n" +
	"\n" +
	"peer_class\x18\x04 \x01(\x0e2\x1b.sub2api.relay.v1.PeerClassR\tpeerClass\x12\x17\n" +
	"\anode_id\x18\x05 \x01(\x03R\x06nodeId\x12-\n" +
	"\x13master_time_unix_ms\x18\x06 \x01(\x03R\x10masterTimeUnixMs\"'\n" +
	"\vPingRequest\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\"W\n" +
	"\fPingResponse\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\x12-\n" +
	"\x13master_time_unix_ms\x18\x02 \x01(\x03R\x10masterTimeUnixMs\"[\n" +
	"\fNodeEnvelope\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x04R\x03seq\x121\n" +
	"\x04ping\x18\n" +
	" \x01(\v2\x1b.sub2api.relay.v1.EventPingH\x00R\x04pingB\x06\n" +
	"\x04body\"]\n" +
	"\x0eMasterEnvelope\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x04R\x03seq\x121\n" +
	"\x04ping\x18\n" +
	" \x01(\v2\x1b.sub2api.relay.v1.EventPingH\x00R\x04pingB\x06\n" +
	"\x04body\"%\n" +
	"\tEventPing\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload*r\n" +
	"\tPeerClass\x12\x1a\n" +
	"\x16PEER_CLASS_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14PEER_CLASS_ANONYMOUS\x10\x01\x12\x18\n" +
	"\x14PEER_CLASS_LONG_TERM\x10\x02\x12\x15\n" +
	"\x11PEER_CLASS_ISSUED\x10\x032[\n" +
	"\x0fRelayEnrollment\x12H\n" +
	"\x05Hello\x12\x1e.sub2api.relay.v1.HelloRequest\x1a\x1f.sub2api.relay.v1.HelloResponse2U\n" +
	"\fRelayControl\x12E\n" +
	"\x04Ping\x12\x1d.sub2api.relay.v1.PingRequest\x1a\x1e.sub2api.relay.v1.PingResponse2]\n" +
	"\vRelayEvents\x12N\n" +
	"\x06Stream\x12\x1e.sub2api.relay.v1.NodeEnvelope\x1a .sub2api.relay.v1.MasterEnvelope(\x010\x01BBZ@github.com/Wei-Shaw/sub2api/internal/relay/proto/relayv1;relayv1b\x06proto3"

var (
	file_sub2api_relay_v1_relay_proto_rawDescOnce sync.Once
	file_sub2api_relay_v1_relay_proto_rawDescData []byte
)

func file_sub2api_relay_v1_relay_proto_rawDescGZIP() []byte {
	file_sub2api_relay_v1_relay_proto_rawDescOnce.Do(func() {
		file_sub2api_relay_v1_relay_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sub2api_relay_v1_relay_proto_rawDesc), len(file_sub2api_relay_v1_relay_proto_rawDesc)))
	})
	return file_sub2api_relay_v1_relay_proto_rawDescData
}

var file_sub2api_relay_v1_relay_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_sub2api_relay_v1_relay_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_sub2api_relay_v1_relay_proto_goTypes = []any{
	(PeerClass)(0),          // 0: sub2api.relay.v1.PeerClass
	(*ProtocolVersion)(nil), // 1: sub2api.relay.v1.ProtocolVersion
	(*HelloRequest)(nil),    // 2: sub2api.relay.v1.HelloRequest
	(*HelloResponse)(nil),   // 3: sub2api.relay.v1.HelloResponse
	(*PingRequest)(nil),     // 4: sub2api.relay.v1.PingRequest
	(*PingResponse)(nil),    // 5: sub2api.relay.v1.PingResponse
	(*NodeEnvelope)(nil),    // 6: sub2api.relay.v1.NodeEnvelope
	(*MasterEnvelope)(nil),  // 7: sub2api.relay.v1.MasterEnvelope
	(*EventPing)(nil),       // 8: sub2api.relay.v1.EventPing
}
var file_sub2api_relay_v1_relay_proto_depIdxs = []int32{
	1, // 0: sub2api.relay.v1.HelloRequest.version:type_name -> sub2api.relay.v1.ProtocolVersion
	1, // 1: sub2api.relay.v1.HelloResponse.min_supported:type_name -> sub2api.relay.v1.ProtocolVersion
	1, // 2: sub2api.relay.v1.HelloResponse.current:type_name -> sub2api.relay.v1.ProtocolVersion
	0, // 3: sub2api.relay.v1.HelloResponse.peer_class:type_name -> sub2api.relay.v1.PeerClass
	8, // 4: sub2api.relay.v1.NodeEnvelope.ping:type_name -> sub2api.relay.v1.EventPing
	8, // 5: sub2api.relay.v1.MasterEnvelope.ping:type_name -> sub2api.relay.v1.EventPing
	2, // 6: sub2api.relay.v1.RelayEnrollment.Hello:input_type -> sub2api.relay.v1.HelloRequest
	4, // 7: sub2api.relay.v1.RelayControl.Ping:input_type -> sub2api.relay.v1.PingRequest
	6, // 8: sub2api.relay.v1.RelayEvents.Stream:input_type -> sub2api.relay.v1.NodeEnvelope
	3, // 9: sub2api.relay.v1.RelayEnrollment.Hello:output_type -> sub2api.relay.v1.HelloResponse
	5, // 10: sub2api.relay.v1.RelayControl.Ping:output_type -> sub2api.relay.v1.PingResponse
	7, // 11: sub2api.relay.v1.RelayEvents.Stream:output_type -> sub2api.relay.v1.MasterEnvelope
	9, // [9:12] is the sub-list for method output_type
	6, // [6:9] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_sub2api_relay_v1_relay_proto_init() }
func file_sub2api_relay_v1_relay_proto_init() {
	if File_sub2api_relay_v1_relay_proto != nil {
		return
	}
	file_sub2api_relay_v1_relay_proto_msgTypes[5].OneofWrappers = []any{
		(*NodeEnvelope_Ping)(nil),
	}
	file_sub2api_relay_v1_relay_proto_msgTypes[6].OneofWrappers = []any{
		(*MasterEnvelope_Ping)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sub2api_relay_v1_relay_proto_rawDesc), len(file_sub2api_relay_v1_relay_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_sub2api_relay_v1_relay_proto_goTypes,
		DependencyIndexes: file_sub2api_relay_v1_relay_proto_depIdxs,
		EnumInfos:         file_sub2api_relay_v1_relay_proto_enumTypes,
		MessageInfos:      file_sub2api_relay_v1_relay_proto_msgTypes,
	}.Build()
	File_sub2api_relay_v1_relay_proto = out.File
	file_sub2api_relay_v1_relay_proto_goTypes = nil
	file_sub2api_relay_v1_relay_proto_depIdxs = nil
}
