// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/contributionroom"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// ContributionRoom is the model entity for the ContributionRoom schema.
type ContributionRoom struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// OwnerUserID holds the value of the "owner_user_id" field.
	OwnerUserID int64 `json:"owner_user_id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// ConsumerRateMultiplier holds the value of the "consumer_rate_multiplier" field.
	ConsumerRateMultiplier float64 `json:"consumer_rate_multiplier,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// Visibility holds the value of the "visibility" field.
	Visibility string `json:"visibility,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ContributionRoomQuery when eager-loading is set.
	Edges        ContributionRoomEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ContributionRoomEdges holds the relations/edges for other nodes in the graph.
type ContributionRoomEdges struct {
	// Owner holds the value of the owner edge.
	Owner *User `json:"owner,omitempty"`
	// Accounts holds the value of the accounts edge.
	Accounts []*ContributionRoomAccount `json:"accounts,omitempty"`
	// Preferences holds the value of the preferences edge.
	Preferences []*UserContributionRoomPreference `json:"preferences,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// OwnerOrErr returns the Owner value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ContributionRoomEdges) OwnerOrErr() (*User, error) {
	if e.Owner != nil {
		return e.Owner, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "owner"}
}

// AccountsOrErr returns the Accounts value or an error if the edge
// was not loaded in eager-loading.
func (e ContributionRoomEdges) AccountsOrErr() ([]*ContributionRoomAccount, error) {
	if e.loadedTypes[1] {
		return e.Accounts, nil
	}
	return nil, &NotLoadedError{edge: "accounts"}
}

// PreferencesOrErr returns the Preferences value or an error if the edge
// was not loaded in eager-loading.
func (e ContributionRoomEdges) PreferencesOrErr() ([]*UserContributionRoomPreference, error) {
	if e.loadedTypes[2] {
		return e.Preferences, nil
	}
	return nil, &NotLoadedError{edge: "preferences"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ContributionRoom) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case contributionroom.FieldConsumerRateMultiplier:
			values[i] = new(sql.NullFloat64)
		case contributionroom.FieldID, contributionroom.FieldOwnerUserID:
			values[i] = new(sql.NullInt64)
		case contributionroom.FieldName, contributionroom.FieldStatus, contributionroom.FieldVisibility:
			values[i] = new(sql.NullString)
		case contributionroom.FieldCreatedAt, contributionroom.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ContributionRoom fields.
func (_m *ContributionRoom) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case contributionroom.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case contributionroom.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case contributionroom.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case contributionroom.FieldOwnerUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field owner_user_id", values[i])
			} else if value.Valid {
				_m.OwnerUserID = value.Int64
			}
		case contributionroom.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case contributionroom.FieldConsumerRateMultiplier:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field consumer_rate_multiplier", values[i])
			} else if value.Valid {
				_m.ConsumerRateMultiplier = value.Float64
			}
		case contributionroom.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case contributionroom.FieldVisibility:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field visibility", values[i])
			} else if value.Valid {
				_m.Visibility = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ContributionRoom.
// This includes values selected through modifiers, order, etc.
func (_m *ContributionRoom) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryOwner queries the "owner" edge of the ContributionRoom entity.
func (_m *ContributionRoom) QueryOwner() *UserQuery {
	return NewContributionRoomClient(_m.config).QueryOwner(_m)
}

// QueryAccounts queries the "accounts" edge of the ContributionRoom entity.
func (_m *ContributionRoom) QueryAccounts() *ContributionRoomAccountQuery {
	return NewContributionRoomClient(_m.config).QueryAccounts(_m)
}

// QueryPreferences queries the "preferences" edge of the ContributionRoom entity.
func (_m *ContributionRoom) QueryPreferences() *UserContributionRoomPreferenceQuery {
	return NewContributionRoomClient(_m.config).QueryPreferences(_m)
}

// Update returns a builder for updating this ContributionRoom.
// Note that you need to call ContributionRoom.Unwrap() before calling this method if this ContributionRoom
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ContributionRoom) Update() *ContributionRoomUpdateOne {
	return NewContributionRoomClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ContributionRoom entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ContributionRoom) Unwrap() *ContributionRoom {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ContributionRoom is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ContributionRoom) String() string {
	var builder strings.Builder
	builder.WriteString("ContributionRoom(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("owner_user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.OwnerUserID))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("consumer_rate_multiplier=")
	builder.WriteString(fmt.Sprintf("%v", _m.ConsumerRateMultiplier))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("visibility=")
	builder.WriteString(_m.Visibility)
	builder.WriteByte(')')
	return builder.String()
}

// ContributionRooms is a parsable slice of ContributionRoom.
type ContributionRooms []*ContributionRoom
