// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/account"
	"github.com/Wei-Shaw/sub2api/ent/contributionroom"
	"github.com/Wei-Shaw/sub2api/ent/contributionroomaccount"
)

// ContributionRoomAccount is the model entity for the ContributionRoomAccount schema.
type ContributionRoomAccount struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// RoomID holds the value of the "room_id" field.
	RoomID int64 `json:"room_id,omitempty"`
	// AccountID holds the value of the "account_id" field.
	AccountID int64 `json:"account_id,omitempty"`
	// Enabled holds the value of the "enabled" field.
	Enabled bool `json:"enabled,omitempty"`
	// Maximum concurrent requests that this room may route to the contributed account.
	ShareConcurrency int `json:"share_concurrency,omitempty"`
	// Maximum raw token cost this room may consume from the contributed account.
	ShareBudgetUsd float64 `json:"share_budget_usd,omitempty"`
	// Raw token cost already consumed through this room membership.
	ShareUsedUsd float64 `json:"share_used_usd,omitempty"`
	// VerifiedAt holds the value of the "verified_at" field.
	VerifiedAt *time.Time `json:"verified_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ContributionRoomAccountQuery when eager-loading is set.
	Edges        ContributionRoomAccountEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ContributionRoomAccountEdges holds the relations/edges for other nodes in the graph.
type ContributionRoomAccountEdges struct {
	// Room holds the value of the room edge.
	Room *ContributionRoom `json:"room,omitempty"`
	// Account holds the value of the account edge.
	Account *Account `json:"account,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// RoomOrErr returns the Room value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ContributionRoomAccountEdges) RoomOrErr() (*ContributionRoom, error) {
	if e.Room != nil {
		return e.Room, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: contributionroom.Label}
	}
	return nil, &NotLoadedError{edge: "room"}
}

// AccountOrErr returns the Account value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ContributionRoomAccountEdges) AccountOrErr() (*Account, error) {
	if e.Account != nil {
		return e.Account, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: account.Label}
	}
	return nil, &NotLoadedError{edge: "account"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ContributionRoomAccount) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case contributionroomaccount.FieldEnabled:
			values[i] = new(sql.NullBool)
		case contributionroomaccount.FieldShareBudgetUsd, contributionroomaccount.FieldShareUsedUsd:
			values[i] = new(sql.NullFloat64)
		case contributionroomaccount.FieldID, contributionroomaccount.FieldRoomID, contributionroomaccount.FieldAccountID, contributionroomaccount.FieldShareConcurrency:
			values[i] = new(sql.NullInt64)
		case contributionroomaccount.FieldCreatedAt, contributionroomaccount.FieldUpdatedAt, contributionroomaccount.FieldVerifiedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ContributionRoomAccount fields.
func (_m *ContributionRoomAccount) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case contributionroomaccount.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case contributionroomaccount.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case contributionroomaccount.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case contributionroomaccount.FieldRoomID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field room_id", values[i])
			} else if value.Valid {
				_m.RoomID = value.Int64
			}
		case contributionroomaccount.FieldAccountID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field account_id", values[i])
			} else if value.Valid {
				_m.AccountID = value.Int64
			}
		case contributionroomaccount.FieldEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enabled", values[i])
			} else if value.Valid {
				_m.Enabled = value.Bool
			}
		case contributionroomaccount.FieldShareConcurrency:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field share_concurrency", values[i])
			} else if value.Valid {
				_m.ShareConcurrency = int(value.Int64)
			}
		case contributionroomaccount.FieldShareBudgetUsd:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field share_budget_usd", values[i])
			} else if value.Valid {
				_m.ShareBudgetUsd = value.Float64
			}
		case contributionroomaccount.FieldShareUsedUsd:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field share_used_usd", values[i])
			} else if value.Valid {
				_m.ShareUsedUsd = value.Float64
			}
		case contributionroomaccount.FieldVerifiedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field verified_at", values[i])
			} else if value.Valid {
				_m.VerifiedAt = new(time.Time)
				*_m.VerifiedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ContributionRoomAccount.
// This includes values selected through modifiers, order, etc.
func (_m *ContributionRoomAccount) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryRoom queries the "room" edge of the ContributionRoomAccount entity.
func (_m *ContributionRoomAccount) QueryRoom() *ContributionRoomQuery {
	return NewContributionRoomAccountClient(_m.config).QueryRoom(_m)
}

// QueryAccount queries the "account" edge of the ContributionRoomAccount entity.
func (_m *ContributionRoomAccount) QueryAccount() *AccountQuery {
	return NewContributionRoomAccountClient(_m.config).QueryAccount(_m)
}

// Update returns a builder for updating this ContributionRoomAccount.
// Note that you need to call ContributionRoomAccount.Unwrap() before calling this method if this ContributionRoomAccount
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ContributionRoomAccount) Update() *ContributionRoomAccountUpdateOne {
	return NewContributionRoomAccountClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ContributionRoomAccount entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ContributionRoomAccount) Unwrap() *ContributionRoomAccount {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ContributionRoomAccount is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ContributionRoomAccount) String() string {
	var builder strings.Builder
	builder.WriteString("ContributionRoomAccount(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("room_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.RoomID))
	builder.WriteString(", ")
	builder.WriteString("account_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.AccountID))
	builder.WriteString(", ")
	builder.WriteString("enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.Enabled))
	builder.WriteString(", ")
	builder.WriteString("share_concurrency=")
	builder.WriteString(fmt.Sprintf("%v", _m.ShareConcurrency))
	builder.WriteString(", ")
	builder.WriteString("share_budget_usd=")
	builder.WriteString(fmt.Sprintf("%v", _m.ShareBudgetUsd))
	builder.WriteString(", ")
	builder.WriteString("share_used_usd=")
	builder.WriteString(fmt.Sprintf("%v", _m.ShareUsedUsd))
	builder.WriteString(", ")
	if v := _m.VerifiedAt; v != nil {
		builder.WriteString("verified_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// ContributionRoomAccounts is a parsable slice of ContributionRoomAccount.
type ContributionRoomAccounts []*ContributionRoomAccount
