// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/account"
	"github.com/Wei-Shaw/sub2api/ent/contributionaccountverification"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ContributionAccountVerificationUpdate is the builder for updating ContributionAccountVerification entities.
type ContributionAccountVerificationUpdate struct {
	config
	hooks    []Hook
	mutation *ContributionAccountVerificationMutation
}

// Where appends a list predicates to the ContributionAccountVerificationUpdate builder.
func (_u *ContributionAccountVerificationUpdate) Where(ps ...predicate.ContributionAccountVerification) *ContributionAccountVerificationUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ContributionAccountVerificationUpdate) SetUpdatedAt(v time.Time) *ContributionAccountVerificationUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *ContributionAccountVerificationUpdate) SetAccountID(v int64) *ContributionAccountVerificationUpdate {
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *ContributionAccountVerificationUpdate) SetNillableAccountID(v *int64) *ContributionAccountVerificationUpdate {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// SetPlatform sets the "platform" field.
func (_u *ContributionAccountVerificationUpdate) SetPlatform(v string) *ContributionAccountVerificationUpdate {
	_u.mutation.SetPlatform(v)
	return _u
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_u *ContributionAccountVerificationUpdate) SetNillablePlatform(v *string) *ContributionAccountVerificationUpdate {
	if v != nil {
		_u.SetPlatform(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *ContributionAccountVerificationUpdate) SetStatus(v string) *ContributionAccountVerificationUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ContributionAccountVerificationUpdate) SetNillableStatus(v *string) *ContributionAccountVerificationUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetModelFamily sets the "model_family" field.
func (_u *ContributionAccountVerificationUpdate) SetModelFamily(v string) *ContributionAccountVerificationUpdate {
	_u.mutation.SetModelFamily(v)
	return _u
}

// SetNillableModelFamily sets the "model_family" field if the given value is not nil.
func (_u *ContributionAccountVerificationUpdate) SetNillableModelFamily(v *string) *ContributionAccountVerificationUpdate {
	if v != nil {
		_u.SetModelFamily(*v)
	}
	return _u
}

// SetSourceKind sets the "source_kind" field.
func (_u *ContributionAccountVerificationUpdate) SetSourceKind(v string) *ContributionAccountVerificationUpdate {
	_u.mutation.SetSourceKind(v)
	return _u
}

// SetNillableSourceKind sets the "source_kind" field if the given value is not nil.
func (_u *ContributionAccountVerificationUpdate) SetNillableSourceKind(v *string) *ContributionAccountVerificationUpdate {
	if v != nil {
		_u.SetSourceKind(*v)
	}
	return _u
}

// SetTestedModel sets the "tested_model" field.
func (_u *ContributionAccountVerificationUpdate) SetTestedModel(v string) *ContributionAccountVerificationUpdate {
	_u.mutation.SetTestedModel(v)
	return _u
}

// SetNillableTestedModel sets the "tested_model" field if the given value is not nil.
func (_u *ContributionAccountVerificationUpdate) SetNillableTestedModel(v *string) *ContributionAccountVerificationUpdate {
	if v != nil {
		_u.SetTestedModel(*v)
	}
	return _u
}

// ClearTestedModel clears the value of the "tested_model" field.
func (_u *ContributionAccountVerificationUpdate) ClearTestedModel() *ContributionAccountVerificationUpdate {
	_u.mutation.ClearTestedModel()
	return _u
}

// SetTestedAt sets the "tested_at" field.
func (_u *ContributionAccountVerificationUpdate) SetTestedAt(v time.Time) *ContributionAccountVerificationUpdate {
	_u.mutation.SetTestedAt(v)
	return _u
}

// SetNillableTestedAt sets the "tested_at" field if the given value is not nil.
func (_u *ContributionAccountVerificationUpdate) SetNillableTestedAt(v *time.Time) *ContributionAccountVerificationUpdate {
	if v != nil {
		_u.SetTestedAt(*v)
	}
	return _u
}

// ClearTestedAt clears the value of the "tested_at" field.
func (_u *ContributionAccountVerificationUpdate) ClearTestedAt() *ContributionAccountVerificationUpdate {
	_u.mutation.ClearTestedAt()
	return _u
}

// SetRedactedErrorSummary sets the "redacted_error_summary" field.
func (_u *ContributionAccountVerificationUpdate) SetRedactedErrorSummary(v string) *ContributionAccountVerificationUpdate {
	_u.mutation.SetRedactedErrorSummary(v)
	return _u
}

// SetNillableRedactedErrorSummary sets the "redacted_error_summary" field if the given value is not nil.
func (_u *ContributionAccountVerificationUpdate) SetNillableRedactedErrorSummary(v *string) *ContributionAccountVerificationUpdate {
	if v != nil {
		_u.SetRedactedErrorSummary(*v)
	}
	return _u
}

// ClearRedactedErrorSummary clears the value of the "redacted_error_summary" field.
func (_u *ContributionAccountVerificationUpdate) ClearRedactedErrorSummary() *ContributionAccountVerificationUpdate {
	_u.mutation.ClearRedactedErrorSummary()
	return _u
}

// SetAccount sets the "account" edge to the Account entity.
func (_u *ContributionAccountVerificationUpdate) SetAccount(v *Account) *ContributionAccountVerificationUpdate {
	return _u.SetAccountID(v.ID)
}

// Mutation returns the ContributionAccountVerificationMutation object of the builder.
func (_u *ContributionAccountVerificationUpdate) Mutation() *ContributionAccountVerificationMutation {
	return _u.mutation
}

// ClearAccount clears the "account" edge to the Account entity.
func (_u *ContributionAccountVerificationUpdate) ClearAccount() *ContributionAccountVerificationUpdate {
	_u.mutation.ClearAccount()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ContributionAccountVerificationUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ContributionAccountVerificationUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ContributionAccountVerificationUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ContributionAccountVerificationUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ContributionAccountVerificationUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := contributionaccountverification.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ContributionAccountVerificationUpdate) check() error {
	if v, ok := _u.mutation.Platform(); ok {
		if err := contributionaccountverification.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "ContributionAccountVerification.platform": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := contributionaccountverification.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ContributionAccountVerification.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ModelFamily(); ok {
		if err := contributionaccountverification.ModelFamilyValidator(v); err != nil {
			return &ValidationError{Name: "model_family", err: fmt.Errorf(`ent: validator failed for field "ContributionAccountVerification.model_family": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SourceKind(); ok {
		if err := contributionaccountverification.SourceKindValidator(v); err != nil {
			return &ValidationError{Name: "source_kind", err: fmt.Errorf(`ent: validator failed for field "ContributionAccountVerification.source_kind": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TestedModel(); ok {
		if err := contributionaccountverification.TestedModelValidator(v); err != nil {
			return &ValidationError{Name: "tested_model", err: fmt.Errorf(`ent: validator failed for field "ContributionAccountVerification.tested_model": %w`, err)}
		}
	}
	if _u.mutation.AccountCleared() && len(_u.mutation.AccountIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ContributionAccountVerification.account"`)
	}
	return nil
}

func (_u *ContributionAccountVerificationUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(contributionaccountverification.Table, contributionaccountverification.Columns, sqlgraph.NewFieldSpec(contributionaccountverification.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(contributionaccountverification.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Platform(); ok {
		_spec.SetField(contributionaccountverification.FieldPlatform, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(contributionaccountverification.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ModelFamily(); ok {
		_spec.SetField(contributionaccountverification.FieldModelFamily, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceKind(); ok {
		_spec.SetField(contributionaccountverification.FieldSourceKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.TestedModel(); ok {
		_spec.SetField(contributionaccountverification.FieldTestedModel, field.TypeString, value)
	}
	if _u.mutation.TestedModelCleared() {
		_spec.ClearField(contributionaccountverification.FieldTestedModel, field.TypeString)
	}
	if value, ok := _u.mutation.TestedAt(); ok {
		_spec.SetField(contributionaccountverification.FieldTestedAt, field.TypeTime, value)
	}
	if _u.mutation.TestedAtCleared() {
		_spec.ClearField(contributionaccountverification.FieldTestedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.RedactedErrorSummary(); ok {
		_spec.SetField(contributionaccountverification.FieldRedactedErrorSummary, field.TypeString, value)
	}
	if _u.mutation.RedactedErrorSummaryCleared() {
		_spec.ClearField(contributionaccountverification.FieldRedactedErrorSummary, field.TypeString)
	}
	if _u.mutation.AccountCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   contributionaccountverification.AccountTable,
			Columns: []string{contributionaccountverification.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   contributionaccountverification.AccountTable,
			Columns: []string{contributionaccountverification.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{contributionaccountverification.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ContributionAccountVerificationUpdateOne is the builder for updating a single ContributionAccountVerification entity.
type ContributionAccountVerificationUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ContributionAccountVerificationMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ContributionAccountVerificationUpdateOne) SetUpdatedAt(v time.Time) *ContributionAccountVerificationUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *ContributionAccountVerificationUpdateOne) SetAccountID(v int64) *ContributionAccountVerificationUpdateOne {
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *ContributionAccountVerificationUpdateOne) SetNillableAccountID(v *int64) *ContributionAccountVerificationUpdateOne {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// SetPlatform sets the "platform" field.
func (_u *ContributionAccountVerificationUpdateOne) SetPlatform(v string) *ContributionAccountVerificationUpdateOne {
	_u.mutation.SetPlatform(v)
	return _u
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_u *ContributionAccountVerificationUpdateOne) SetNillablePlatform(v *string) *ContributionAccountVerificationUpdateOne {
	if v != nil {
		_u.SetPlatform(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *ContributionAccountVerificationUpdateOne) SetStatus(v string) *ContributionAccountVerificationUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ContributionAccountVerificationUpdateOne) SetNillableStatus(v *string) *ContributionAccountVerificationUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetModelFamily sets the "model_family" field.
func (_u *ContributionAccountVerificationUpdateOne) SetModelFamily(v string) *ContributionAccountVerificationUpdateOne {
	_u.mutation.SetModelFamily(v)
	return _u
}

// SetNillableModelFamily sets the "model_family" field if the given value is not nil.
func (_u *ContributionAccountVerificationUpdateOne) SetNillableModelFamily(v *string) *ContributionAccountVerificationUpdateOne {
	if v != nil {
		_u.SetModelFamily(*v)
	}
	return _u
}

// SetSourceKind sets the "source_kind" field.
func (_u *ContributionAccountVerificationUpdateOne) SetSourceKind(v string) *ContributionAccountVerificationUpdateOne {
	_u.mutation.SetSourceKind(v)
	return _u
}

// SetNillableSourceKind sets the "source_kind" field if the given value is not nil.
func (_u *ContributionAccountVerificationUpdateOne) SetNillableSourceKind(v *string) *ContributionAccountVerificationUpdateOne {
	if v != nil {
		_u.SetSourceKind(*v)
	}
	return _u
}

// SetTestedModel sets the "tested_model" field.
func (_u *ContributionAccountVerificationUpdateOne) SetTestedModel(v string) *ContributionAccountVerificationUpdateOne {
	_u.mutation.SetTestedModel(v)
	return _u
}

// SetNillableTestedModel sets the "tested_model" field if the given value is not nil.
func (_u *ContributionAccountVerificationUpdateOne) SetNillableTestedModel(v *string) *ContributionAccountVerificationUpdateOne {
	if v != nil {
		_u.SetTestedModel(*v)
	}
	return _u
}

// ClearTestedModel clears the value of the "tested_model" field.
func (_u *ContributionAccountVerificationUpdateOne) ClearTestedModel() *ContributionAccountVerificationUpdateOne {
	_u.mutation.ClearTestedModel()
	return _u
}

// SetTestedAt sets the "tested_at" field.
func (_u *ContributionAccountVerificationUpdateOne) SetTestedAt(v time.Time) *ContributionAccountVerificationUpdateOne {
	_u.mutation.SetTestedAt(v)
	return _u
}

// SetNillableTestedAt sets the "tested_at" field if the given value is not nil.
func (_u *ContributionAccountVerificationUpdateOne) SetNillableTestedAt(v *time.Time) *ContributionAccountVerificationUpdateOne {
	if v != nil {
		_u.SetTestedAt(*v)
	}
	return _u
}

// ClearTestedAt clears the value of the "tested_at" field.
func (_u *ContributionAccountVerificationUpdateOne) ClearTestedAt() *ContributionAccountVerificationUpdateOne {
	_u.mutation.ClearTestedAt()
	return _u
}

// SetRedactedErrorSummary sets the "redacted_error_summary" field.
func (_u *ContributionAccountVerificationUpdateOne) SetRedactedErrorSummary(v string) *ContributionAccountVerificationUpdateOne {
	_u.mutation.SetRedactedErrorSummary(v)
	return _u
}

// SetNillableRedactedErrorSummary sets the "redacted_error_summary" field if the given value is not nil.
func (_u *ContributionAccountVerificationUpdateOne) SetNillableRedactedErrorSummary(v *string) *ContributionAccountVerificationUpdateOne {
	if v != nil {
		_u.SetRedactedErrorSummary(*v)
	}
	return _u
}

// ClearRedactedErrorSummary clears the value of the "redacted_error_summary" field.
func (_u *ContributionAccountVerificationUpdateOne) ClearRedactedErrorSummary() *ContributionAccountVerificationUpdateOne {
	_u.mutation.ClearRedactedErrorSummary()
	return _u
}

// SetAccount sets the "account" edge to the Account entity.
func (_u *ContributionAccountVerificationUpdateOne) SetAccount(v *Account) *ContributionAccountVerificationUpdateOne {
	return _u.SetAccountID(v.ID)
}

// Mutation returns the ContributionAccountVerificationMutation object of the builder.
func (_u *ContributionAccountVerificationUpdateOne) Mutation() *ContributionAccountVerificationMutation {
	return _u.mutation
}

// ClearAccount clears the "account" edge to the Account entity.
func (_u *ContributionAccountVerificationUpdateOne) ClearAccount() *ContributionAccountVerificationUpdateOne {
	_u.mutation.ClearAccount()
	return _u
}

// Where appends a list predicates to the ContributionAccountVerificationUpdate builder.
func (_u *ContributionAccountVerificationUpdateOne) Where(ps ...predicate.ContributionAccountVerification) *ContributionAccountVerificationUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ContributionAccountVerificationUpdateOne) Select(field string, fields ...string) *ContributionAccountVerificationUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ContributionAccountVerification entity.
func (_u *ContributionAccountVerificationUpdateOne) Save(ctx context.Context) (*ContributionAccountVerification, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ContributionAccountVerificationUpdateOne) SaveX(ctx context.Context) *ContributionAccountVerification {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ContributionAccountVerificationUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ContributionAccountVerificationUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ContributionAccountVerificationUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := contributionaccountverification.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ContributionAccountVerificationUpdateOne) check() error {
	if v, ok := _u.mutation.Platform(); ok {
		if err := contributionaccountverification.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "ContributionAccountVerification.platform": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := contributionaccountverification.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ContributionAccountVerification.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ModelFamily(); ok {
		if err := contributionaccountverification.ModelFamilyValidator(v); err != nil {
			return &ValidationError{Name: "model_family", err: fmt.Errorf(`ent: validator failed for field "ContributionAccountVerification.model_family": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SourceKind(); ok {
		if err := contributionaccountverification.SourceKindValidator(v); err != nil {
			return &ValidationError{Name: "source_kind", err: fmt.Errorf(`ent: validator failed for field "ContributionAccountVerification.source_kind": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TestedModel(); ok {
		if err := contributionaccountverification.TestedModelValidator(v); err != nil {
			return &ValidationError{Name: "tested_model", err: fmt.Errorf(`ent: validator failed for field "ContributionAccountVerification.tested_model": %w`, err)}
		}
	}
	if _u.mutation.AccountCleared() && len(_u.mutation.AccountIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ContributionAccountVerification.account"`)
	}
	return nil
}

func (_u *ContributionAccountVerificationUpdateOne) sqlSave(ctx context.Context) (_node *ContributionAccountVerification, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(contributionaccountverification.Table, contributionaccountverification.Columns, sqlgraph.NewFieldSpec(contributionaccountverification.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ContributionAccountVerification.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, contributionaccountverification.FieldID)
		for _, f := range fields {
			if !contributionaccountverification.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != contributionaccountverification.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(contributionaccountverification.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Platform(); ok {
		_spec.SetField(contributionaccountverification.FieldPlatform, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(contributionaccountverification.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ModelFamily(); ok {
		_spec.SetField(contributionaccountverification.FieldModelFamily, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceKind(); ok {
		_spec.SetField(contributionaccountverification.FieldSourceKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.TestedModel(); ok {
		_spec.SetField(contributionaccountverification.FieldTestedModel, field.TypeString, value)
	}
	if _u.mutation.TestedModelCleared() {
		_spec.ClearField(contributionaccountverification.FieldTestedModel, field.TypeString)
	}
	if value, ok := _u.mutation.TestedAt(); ok {
		_spec.SetField(contributionaccountverification.FieldTestedAt, field.TypeTime, value)
	}
	if _u.mutation.TestedAtCleared() {
		_spec.ClearField(contributionaccountverification.FieldTestedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.RedactedErrorSummary(); ok {
		_spec.SetField(contributionaccountverification.FieldRedactedErrorSummary, field.TypeString, value)
	}
	if _u.mutation.RedactedErrorSummaryCleared() {
		_spec.ClearField(contributionaccountverification.FieldRedactedErrorSummary, field.TypeString)
	}
	if _u.mutation.AccountCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   contributionaccountverification.AccountTable,
			Columns: []string{contributionaccountverification.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   contributionaccountverification.AccountTable,
			Columns: []string{contributionaccountverification.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ContributionAccountVerification{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{contributionaccountverification.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
