// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/account"
	"github.com/Wei-Shaw/sub2api/ent/contributionaccountverification"
)

// ContributionAccountVerification is the model entity for the ContributionAccountVerification schema.
type ContributionAccountVerification struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// AccountID holds the value of the "account_id" field.
	AccountID int64 `json:"account_id,omitempty"`
	// Platform holds the value of the "platform" field.
	Platform string `json:"platform,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// Model family proven by the canonical contribution probe, for example gpt or claude.
	ModelFamily string `json:"model_family,omitempty"`
	// Credential provenance classification such as official_openai or openai_compatible.
	SourceKind string `json:"source_kind,omitempty"`
	// TestedModel holds the value of the "tested_model" field.
	TestedModel *string `json:"tested_model,omitempty"`
	// TestedAt holds the value of the "tested_at" field.
	TestedAt *time.Time `json:"tested_at,omitempty"`
	// Redacted summary only; credentials and raw upstream errors must not be stored here.
	RedactedErrorSummary *string `json:"redacted_error_summary,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ContributionAccountVerificationQuery when eager-loading is set.
	Edges        ContributionAccountVerificationEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ContributionAccountVerificationEdges holds the relations/edges for other nodes in the graph.
type ContributionAccountVerificationEdges struct {
	// Account holds the value of the account edge.
	Account *Account `json:"account,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// AccountOrErr returns the Account value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ContributionAccountVerificationEdges) AccountOrErr() (*Account, error) {
	if e.Account != nil {
		return e.Account, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: account.Label}
	}
	return nil, &NotLoadedError{edge: "account"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ContributionAccountVerification) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case contributionaccountverification.FieldID, contributionaccountverification.FieldAccountID:
			values[i] = new(sql.NullInt64)
		case contributionaccountverification.FieldPlatform, contributionaccountverification.FieldStatus, contributionaccountverification.FieldModelFamily, contributionaccountverification.FieldSourceKind, contributionaccountverification.FieldTestedModel, contributionaccountverification.FieldRedactedErrorSummary:
			values[i] = new(sql.NullString)
		case contributionaccountverification.FieldCreatedAt, contributionaccountverification.FieldUpdatedAt, contributionaccountverification.FieldTestedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ContributionAccountVerification fields.
func (_m *ContributionAccountVerification) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case contributionaccountverification.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case contributionaccountverification.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case contributionaccountverification.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case contributionaccountverification.FieldAccountID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field account_id", values[i])
			} else if value.Valid {
				_m.AccountID = value.Int64
			}
		case contributionaccountverification.FieldPlatform:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field platform", values[i])
			} else if value.Valid {
				_m.Platform = value.String
			}
		case contributionaccountverification.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case contributionaccountverification.FieldModelFamily:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field model_family", values[i])
			} else if value.Valid {
				_m.ModelFamily = value.String
			}
		case contributionaccountverification.FieldSourceKind:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source_kind", values[i])
			} else if value.Valid {
				_m.SourceKind = value.String
			}
		case contributionaccountverification.FieldTestedModel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field tested_model", values[i])
			} else if value.Valid {
				_m.TestedModel = new(string)
				*_m.TestedModel = value.String
			}
		case contributionaccountverification.FieldTestedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field tested_at", values[i])
			} else if value.Valid {
				_m.TestedAt = new(time.Time)
				*_m.TestedAt = value.Time
			}
		case contributionaccountverification.FieldRedactedErrorSummary:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field redacted_error_summary", values[i])
			} else if value.Valid {
				_m.RedactedErrorSummary = new(string)
				*_m.RedactedErrorSummary = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ContributionAccountVerification.
// This includes values selected through modifiers, order, etc.
func (_m *ContributionAccountVerification) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryAccount queries the "account" edge of the ContributionAccountVerification entity.
func (_m *ContributionAccountVerification) QueryAccount() *AccountQuery {
	return NewContributionAccountVerificationClient(_m.config).QueryAccount(_m)
}

// Update returns a builder for updating this ContributionAccountVerification.
// Note that you need to call ContributionAccountVerification.Unwrap() before calling this method if this ContributionAccountVerification
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ContributionAccountVerification) Update() *ContributionAccountVerificationUpdateOne {
	return NewContributionAccountVerificationClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ContributionAccountVerification entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ContributionAccountVerification) Unwrap() *ContributionAccountVerification {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ContributionAccountVerification is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ContributionAccountVerification) String() string {
	var builder strings.Builder
	builder.WriteString("ContributionAccountVerification(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("account_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.AccountID))
	builder.WriteString(", ")
	builder.WriteString("platform=")
	builder.WriteString(_m.Platform)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("model_family=")
	builder.WriteString(_m.ModelFamily)
	builder.WriteString(", ")
	builder.WriteString("source_kind=")
	builder.WriteString(_m.SourceKind)
	builder.WriteString(", ")
	if v := _m.TestedModel; v != nil {
		builder.WriteString("tested_model=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.TestedAt; v != nil {
		builder.WriteString("tested_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.RedactedErrorSummary; v != nil {
		builder.WriteString("redacted_error_summary=")
		builder.WriteString(*v)
	}
	builder.WriteByte(')')
	return builder.String()
}

// ContributionAccountVerifications is a parsable slice of ContributionAccountVerification.
type ContributionAccountVerifications []*ContributionAccountVerification
