// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/account"
	"github.com/Wei-Shaw/sub2api/ent/contributionaccountverification"
)

// ContributionAccountVerificationCreate is the builder for creating a ContributionAccountVerification entity.
type ContributionAccountVerificationCreate struct {
	config
	mutation *ContributionAccountVerificationMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *ContributionAccountVerificationCreate) SetCreatedAt(v time.Time) *ContributionAccountVerificationCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ContributionAccountVerificationCreate) SetNillableCreatedAt(v *time.Time) *ContributionAccountVerificationCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ContributionAccountVerificationCreate) SetUpdatedAt(v time.Time) *ContributionAccountVerificationCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ContributionAccountVerificationCreate) SetNillableUpdatedAt(v *time.Time) *ContributionAccountVerificationCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetAccountID sets the "account_id" field.
func (_c *ContributionAccountVerificationCreate) SetAccountID(v int64) *ContributionAccountVerificationCreate {
	_c.mutation.SetAccountID(v)
	return _c
}

// SetPlatform sets the "platform" field.
func (_c *ContributionAccountVerificationCreate) SetPlatform(v string) *ContributionAccountVerificationCreate {
	_c.mutation.SetPlatform(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *ContributionAccountVerificationCreate) SetStatus(v string) *ContributionAccountVerificationCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *ContributionAccountVerificationCreate) SetNillableStatus(v *string) *ContributionAccountVerificationCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetModelFamily sets the "model_family" field.
func (_c *ContributionAccountVerificationCreate) SetModelFamily(v string) *ContributionAccountVerificationCreate {
	_c.mutation.SetModelFamily(v)
	return _c
}

// SetNillableModelFamily sets the "model_family" field if the given value is not nil.
func (_c *ContributionAccountVerificationCreate) SetNillableModelFamily(v *string) *ContributionAccountVerificationCreate {
	if v != nil {
		_c.SetModelFamily(*v)
	}
	return _c
}

// SetSourceKind sets the "source_kind" field.
func (_c *ContributionAccountVerificationCreate) SetSourceKind(v string) *ContributionAccountVerificationCreate {
	_c.mutation.SetSourceKind(v)
	return _c
}

// SetNillableSourceKind sets the "source_kind" field if the given value is not nil.
func (_c *ContributionAccountVerificationCreate) SetNillableSourceKind(v *string) *ContributionAccountVerificationCreate {
	if v != nil {
		_c.SetSourceKind(*v)
	}
	return _c
}

// SetTestedModel sets the "tested_model" field.
func (_c *ContributionAccountVerificationCreate) SetTestedModel(v string) *ContributionAccountVerificationCreate {
	_c.mutation.SetTestedModel(v)
	return _c
}

// SetNillableTestedModel sets the "tested_model" field if the given value is not nil.
func (_c *ContributionAccountVerificationCreate) SetNillableTestedModel(v *string) *ContributionAccountVerificationCreate {
	if v != nil {
		_c.SetTestedModel(*v)
	}
	return _c
}

// SetTestedAt sets the "tested_at" field.
func (_c *ContributionAccountVerificationCreate) SetTestedAt(v time.Time) *ContributionAccountVerificationCreate {
	_c.mutation.SetTestedAt(v)
	return _c
}

// SetNillableTestedAt sets the "tested_at" field if the given value is not nil.
func (_c *ContributionAccountVerificationCreate) SetNillableTestedAt(v *time.Time) *ContributionAccountVerificationCreate {
	if v != nil {
		_c.SetTestedAt(*v)
	}
	return _c
}

// SetRedactedErrorSummary sets the "redacted_error_summary" field.
func (_c *ContributionAccountVerificationCreate) SetRedactedErrorSummary(v string) *ContributionAccountVerificationCreate {
	_c.mutation.SetRedactedErrorSummary(v)
	return _c
}

// SetNillableRedactedErrorSummary sets the "redacted_error_summary" field if the given value is not nil.
func (_c *ContributionAccountVerificationCreate) SetNillableRedactedErrorSummary(v *string) *ContributionAccountVerificationCreate {
	if v != nil {
		_c.SetRedactedErrorSummary(*v)
	}
	return _c
}

// SetAccount sets the "account" edge to the Account entity.
func (_c *ContributionAccountVerificationCreate) SetAccount(v *Account) *ContributionAccountVerificationCreate {
	return _c.SetAccountID(v.ID)
}

// Mutation returns the ContributionAccountVerificationMutation object of the builder.
func (_c *ContributionAccountVerificationCreate) Mutation() *ContributionAccountVerificationMutation {
	return _c.mutation
}

// Save creates the ContributionAccountVerification in the database.
func (_c *ContributionAccountVerificationCreate) Save(ctx context.Context) (*ContributionAccountVerification, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ContributionAccountVerificationCreate) SaveX(ctx context.Context) *ContributionAccountVerification {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ContributionAccountVerificationCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ContributionAccountVerificationCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ContributionAccountVerificationCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := contributionaccountverification.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := contributionaccountverification.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := contributionaccountverification.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.ModelFamily(); !ok {
		v := contributionaccountverification.DefaultModelFamily
		_c.mutation.SetModelFamily(v)
	}
	if _, ok := _c.mutation.SourceKind(); !ok {
		v := contributionaccountverification.DefaultSourceKind
		_c.mutation.SetSourceKind(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ContributionAccountVerificationCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ContributionAccountVerification.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ContributionAccountVerification.updated_at"`)}
	}
	if _, ok := _c.mutation.AccountID(); !ok {
		return &ValidationError{Name: "account_id", err: errors.New(`ent: missing required field "ContributionAccountVerification.account_id"`)}
	}
	if _, ok := _c.mutation.Platform(); !ok {
		return &ValidationError{Name: "platform", err: errors.New(`ent: missing required field "ContributionAccountVerification.platform"`)}
	}
	if v, ok := _c.mutation.Platform(); ok {
		if err := contributionaccountverification.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "ContributionAccountVerification.platform": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "ContributionAccountVerification.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := contributionaccountverification.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ContributionAccountVerification.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ModelFamily(); !ok {
		return &ValidationError{Name: "model_family", err: errors.New(`ent: missing required field "ContributionAccountVerification.model_family"`)}
	}
	if v, ok := _c.mutation.ModelFamily(); ok {
		if err := contributionaccountverification.ModelFamilyValidator(v); err != nil {
			return &ValidationError{Name: "model_family", err: fmt.Errorf(`ent: validator failed for field "ContributionAccountVerification.model_family": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SourceKind(); !ok {
		return &ValidationError{Name: "source_kind", err: errors.New(`ent: missing required field "ContributionAccountVerification.source_kind"`)}
	}
	if v, ok := _c.mutation.SourceKind(); ok {
		if err := contributionaccountverification.SourceKindValidator(v); err != nil {
			return &ValidationError{Name: "source_kind", err: fmt.Errorf(`ent: validator failed for field "ContributionAccountVerification.source_kind": %w`, err)}
		}
	}
	if v, ok := _c.mutation.TestedModel(); ok {
		if err := contributionaccountverification.TestedModelValidator(v); err != nil {
			return &ValidationError{Name: "tested_model", err: fmt.Errorf(`ent: validator failed for field "ContributionAccountVerification.tested_model": %w`, err)}
		}
	}
	if len(_c.mutation.AccountIDs()) == 0 {
		return &ValidationError{Name: "account", err: errors.New(`ent: missing required edge "ContributionAccountVerification.account"`)}
	}
	return nil
}

func (_c *ContributionAccountVerificationCreate) sqlSave(ctx context.Context) (*ContributionAccountVerification, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ContributionAccountVerificationCreate) createSpec() (*ContributionAccountVerification, *sqlgraph.CreateSpec) {
	var (
		_node = &ContributionAccountVerification{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(contributionaccountverification.Table, sqlgraph.NewFieldSpec(contributionaccountverification.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(contributionaccountverification.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(contributionaccountverification.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Platform(); ok {
		_spec.SetField(contributionaccountverification.FieldPlatform, field.TypeString, value)
		_node.Platform = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(contributionaccountverification.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.ModelFamily(); ok {
		_spec.SetField(contributionaccountverification.FieldModelFamily, field.TypeString, value)
		_node.ModelFamily = value
	}
	if value, ok := _c.mutation.SourceKind(); ok {
		_spec.SetField(contributionaccountverification.FieldSourceKind, field.TypeString, value)
		_node.SourceKind = value
	}
	if value, ok := _c.mutation.TestedModel(); ok {
		_spec.SetField(contributionaccountverification.FieldTestedModel, field.TypeString, value)
		_node.TestedModel = &value
	}
	if value, ok := _c.mutation.TestedAt(); ok {
		_spec.SetField(contributionaccountverification.FieldTestedAt, field.TypeTime, value)
		_node.TestedAt = &value
	}
	if value, ok := _c.mutation.RedactedErrorSummary(); ok {
		_spec.SetField(contributionaccountverification.FieldRedactedErrorSummary, field.TypeString, value)
		_node.RedactedErrorSummary = &value
	}
	if nodes := _c.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   contributionaccountverification.AccountTable,
			Columns: []string{contributionaccountverification.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.AccountID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ContributionAccountVerification.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ContributionAccountVerificationUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ContributionAccountVerificationCreate) OnConflict(opts ...sql.ConflictOption) *ContributionAccountVerificationUpsertOne {
	_c.conflict = opts
	return &ContributionAccountVerificationUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ContributionAccountVerification.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ContributionAccountVerificationCreate) OnConflictColumns(columns ...string) *ContributionAccountVerificationUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ContributionAccountVerificationUpsertOne{
		create: _c,
	}
}

type (
	// ContributionAccountVerificationUpsertOne is the builder for "upsert"-ing
	//  one ContributionAccountVerification node.
	ContributionAccountVerificationUpsertOne struct {
		create *ContributionAccountVerificationCreate
	}

	// ContributionAccountVerificationUpsert is the "OnConflict" setter.
	ContributionAccountVerificationUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *ContributionAccountVerificationUpsert) SetUpdatedAt(v time.Time) *ContributionAccountVerificationUpsert {
	u.Set(contributionaccountverification.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ContributionAccountVerificationUpsert) UpdateUpdatedAt() *ContributionAccountVerificationUpsert {
	u.SetExcluded(contributionaccountverification.FieldUpdatedAt)
	return u
}

// SetAccountID sets the "account_id" field.
func (u *ContributionAccountVerificationUpsert) SetAccountID(v int64) *ContributionAccountVerificationUpsert {
	u.Set(contributionaccountverification.FieldAccountID, v)
	return u
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *ContributionAccountVerificationUpsert) UpdateAccountID() *ContributionAccountVerificationUpsert {
	u.SetExcluded(contributionaccountverification.FieldAccountID)
	return u
}

// SetPlatform sets the "platform" field.
func (u *ContributionAccountVerificationUpsert) SetPlatform(v string) *ContributionAccountVerificationUpsert {
	u.Set(contributionaccountverification.FieldPlatform, v)
	return u
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *ContributionAccountVerificationUpsert) UpdatePlatform() *ContributionAccountVerificationUpsert {
	u.SetExcluded(contributionaccountverification.FieldPlatform)
	return u
}

// SetStatus sets the "status" field.
func (u *ContributionAccountVerificationUpsert) SetStatus(v string) *ContributionAccountVerificationUpsert {
	u.Set(contributionaccountverification.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ContributionAccountVerificationUpsert) UpdateStatus() *ContributionAccountVerificationUpsert {
	u.SetExcluded(contributionaccountverification.FieldStatus)
	return u
}

// SetModelFamily sets the "model_family" field.
func (u *ContributionAccountVerificationUpsert) SetModelFamily(v string) *ContributionAccountVerificationUpsert {
	u.Set(contributionaccountverification.FieldModelFamily, v)
	return u
}

// UpdateModelFamily sets the "model_family" field to the value that was provided on create.
func (u *ContributionAccountVerificationUpsert) UpdateModelFamily() *ContributionAccountVerificationUpsert {
	u.SetExcluded(contributionaccountverification.FieldModelFamily)
	return u
}

// SetSourceKind sets the "source_kind" field.
func (u *ContributionAccountVerificationUpsert) SetSourceKind(v string) *ContributionAccountVerificationUpsert {
	u.Set(contributionaccountverification.FieldSourceKind, v)
	return u
}

// UpdateSourceKind sets the "source_kind" field to the value that was provided on create.
func (u *ContributionAccountVerificationUpsert) UpdateSourceKind() *ContributionAccountVerificationUpsert {
	u.SetExcluded(contributionaccountverification.FieldSourceKind)
	return u
}

// SetTestedModel sets the "tested_model" field.
func (u *ContributionAccountVerificationUpsert) SetTestedModel(v string) *ContributionAccountVerificationUpsert {
	u.Set(contributionaccountverification.FieldTestedModel, v)
	return u
}

// UpdateTestedModel sets the "tested_model" field to the value that was provided on create.
func (u *ContributionAccountVerificationUpsert) UpdateTestedModel() *ContributionAccountVerificationUpsert {
	u.SetExcluded(contributionaccountverification.FieldTestedModel)
	return u
}

// ClearTestedModel clears the value of the "tested_model" field.
func (u *ContributionAccountVerificationUpsert) ClearTestedModel() *ContributionAccountVerificationUpsert {
	u.SetNull(contributionaccountverification.FieldTestedModel)
	return u
}

// SetTestedAt sets the "tested_at" field.
func (u *ContributionAccountVerificationUpsert) SetTestedAt(v time.Time) *ContributionAccountVerificationUpsert {
	u.Set(contributionaccountverification.FieldTestedAt, v)
	return u
}

// UpdateTestedAt sets the "tested_at" field to the value that was provided on create.
func (u *ContributionAccountVerificationUpsert) UpdateTestedAt() *ContributionAccountVerificationUpsert {
	u.SetExcluded(contributionaccountverification.FieldTestedAt)
	return u
}

// ClearTestedAt clears the value of the "tested_at" field.
func (u *ContributionAccountVerificationUpsert) ClearTestedAt() *ContributionAccountVerificationUpsert {
	u.SetNull(contributionaccountverification.FieldTestedAt)
	return u
}

// SetRedactedErrorSummary sets the "redacted_error_summary" field.
func (u *ContributionAccountVerificationUpsert) SetRedactedErrorSummary(v string) *ContributionAccountVerificationUpsert {
	u.Set(contributionaccountverification.FieldRedactedErrorSummary, v)
	return u
}

// UpdateRedactedErrorSummary sets the "redacted_error_summary" field to the value that was provided on create.
func (u *ContributionAccountVerificationUpsert) UpdateRedactedErrorSummary() *ContributionAccountVerificationUpsert {
	u.SetExcluded(contributionaccountverification.FieldRedactedErrorSummary)
	return u
}

// ClearRedactedErrorSummary clears the value of the "redacted_error_summary" field.
func (u *ContributionAccountVerificationUpsert) ClearRedactedErrorSummary() *ContributionAccountVerificationUpsert {
	u.SetNull(contributionaccountverification.FieldRedactedErrorSummary)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.ContributionAccountVerification.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ContributionAccountVerificationUpsertOne) UpdateNewValues() *ContributionAccountVerificationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(contributionaccountverification.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ContributionAccountVerification.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ContributionAccountVerificationUpsertOne) Ignore() *ContributionAccountVerificationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ContributionAccountVerificationUpsertOne) DoNothing() *ContributionAccountVerificationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ContributionAccountVerificationCreate.OnConflict
// documentation for more info.
func (u *ContributionAccountVerificationUpsertOne) Update(set func(*ContributionAccountVerificationUpsert)) *ContributionAccountVerificationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ContributionAccountVerificationUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ContributionAccountVerificationUpsertOne) SetUpdatedAt(v time.Time) *ContributionAccountVerificationUpsertOne {
	return u.Update(func(s *ContributionAccountVerificationUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ContributionAccountVerificationUpsertOne) UpdateUpdatedAt() *ContributionAccountVerificationUpsertOne {
	return u.Update(func(s *ContributionAccountVerificationUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetAccountID sets the "account_id" field.
func (u *ContributionAccountVerificationUpsertOne) SetAccountID(v int64) *ContributionAccountVerificationUpsertOne {
	return u.Update(func(s *ContributionAccountVerificationUpsert) {
		s.SetAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *ContributionAccountVerificationUpsertOne) UpdateAccountID() *ContributionAccountVerificationUpsertOne {
	return u.Update(func(s *ContributionAccountVerificationUpsert) {
		s.UpdateAccountID()
	})
}

// SetPlatform sets the "platform" field.
func (u *ContributionAccountVerificationUpsertOne) SetPlatform(v string) *ContributionAccountVerificationUpsertOne {
	return u.Update(func(s *ContributionAccountVerificationUpsert) {
		s.SetPlatform(v)
	})
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *ContributionAccountVerificationUpsertOne) UpdatePlatform() *ContributionAccountVerificationUpsertOne {
	return u.Update(func(s *ContributionAccountVerificationUpsert) {
		s.UpdatePlatform()
	})
}

// SetStatus sets the "status" field.
func (u *ContributionAccountVerificationUpsertOne) SetStatus(v string) *ContributionAccountVerificationUpsertOne {
	return u.Update(func(s *ContributionAccountVerificationUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ContributionAccountVerificationUpsertOne) UpdateStatus() *ContributionAccountVerificationUpsertOne {
	return u.Update(func(s *ContributionAccountVerificationUpsert) {
		s.UpdateStatus()
	})
}

// SetModelFamily sets the "model_family" field.
func (u *ContributionAccountVerificationUpsertOne) SetModelFamily(v string) *ContributionAccountVerificationUpsertOne {
	return u.Update(func(s *ContributionAccountVerificationUpsert) {
		s.SetModelFamily(v)
	})
}

// UpdateModelFamily sets the "model_family" field to the value that was provided on create.
func (u *ContributionAccountVerificationUpsertOne) UpdateModelFamily() *ContributionAccountVerificationUpsertOne {
	return u.Update(func(s *ContributionAccountVerificationUpsert) {
		s.UpdateModelFamily()
	})
}

// SetSourceKind sets the "source_kind" field.
func (u *ContributionAccountVerificationUpsertOne) SetSourceKind(v string) *ContributionAccountVerificationUpsertOne {
	return u.Update(func(s *ContributionAccountVerificationUpsert) {
		s.SetSourceKind(v)
	})
}

// UpdateSourceKind sets the "source_kind" field to the value that was provided on create.
func (u *ContributionAccountVerificationUpsertOne) UpdateSourceKind() *ContributionAccountVerificationUpsertOne {
	return u.Update(func(s *ContributionAccountVerificationUpsert) {
		s.UpdateSourceKind()
	})
}

// SetTestedModel sets the "tested_model" field.
func (u *ContributionAccountVerificationUpsertOne) SetTestedModel(v string) *ContributionAccountVerificationUpsertOne {
	return u.Update(func(s *ContributionAccountVerificationUpsert) {
		s.SetTestedModel(v)
	})
}

// UpdateTestedModel sets the "tested_model" field to the value that was provided on create.
func (u *ContributionAccountVerificationUpsertOne) UpdateTestedModel() *ContributionAccountVerificationUpsertOne {
	return u.Update(func(s *ContributionAccountVerificationUpsert) {
		s.UpdateTestedModel()
	})
}

// ClearTestedModel clears the value of the "tested_model" field.
func (u *ContributionAccountVerificationUpsertOne) ClearTestedModel() *ContributionAccountVerificationUpsertOne {
	return u.Update(func(s *ContributionAccountVerificationUpsert) {
		s.ClearTestedModel()
	})
}

// SetTestedAt sets the "tested_at" field.
func (u *ContributionAccountVerificationUpsertOne) SetTestedAt(v time.Time) *ContributionAccountVerificationUpsertOne {
	return u.Update(func(s *ContributionAccountVerificationUpsert) {
		s.SetTestedAt(v)
	})
}

// UpdateTestedAt sets the "tested_at" field to the value that was provided on create.
func (u *ContributionAccountVerificationUpsertOne) UpdateTestedAt() *ContributionAccountVerificationUpsertOne {
	return u.Update(func(s *ContributionAccountVerificationUpsert) {
		s.UpdateTestedAt()
	})
}

// ClearTestedAt clears the value of the "tested_at" field.
func (u *ContributionAccountVerificationUpsertOne) ClearTestedAt() *ContributionAccountVerificationUpsertOne {
	return u.Update(func(s *ContributionAccountVerificationUpsert) {
		s.ClearTestedAt()
	})
}

// SetRedactedErrorSummary sets the "redacted_error_summary" field.
func (u *ContributionAccountVerificationUpsertOne) SetRedactedErrorSummary(v string) *ContributionAccountVerificationUpsertOne {
	return u.Update(func(s *ContributionAccountVerificationUpsert) {
		s.SetRedactedErrorSummary(v)
	})
}

// UpdateRedactedErrorSummary sets the "redacted_error_summary" field to the value that was provided on create.
func (u *ContributionAccountVerificationUpsertOne) UpdateRedactedErrorSummary() *ContributionAccountVerificationUpsertOne {
	return u.Update(func(s *ContributionAccountVerificationUpsert) {
		s.UpdateRedactedErrorSummary()
	})
}

// ClearRedactedErrorSummary clears the value of the "redacted_error_summary" field.
func (u *ContributionAccountVerificationUpsertOne) ClearRedactedErrorSummary() *ContributionAccountVerificationUpsertOne {
	return u.Update(func(s *ContributionAccountVerificationUpsert) {
		s.ClearRedactedErrorSummary()
	})
}

// Exec executes the query.
func (u *ContributionAccountVerificationUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ContributionAccountVerificationCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ContributionAccountVerificationUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ContributionAccountVerificationUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ContributionAccountVerificationUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ContributionAccountVerificationCreateBulk is the builder for creating many ContributionAccountVerification entities in bulk.
type ContributionAccountVerificationCreateBulk struct {
	config
	err      error
	builders []*ContributionAccountVerificationCreate
	conflict []sql.ConflictOption
}

// Save creates the ContributionAccountVerification entities in the database.
func (_c *ContributionAccountVerificationCreateBulk) Save(ctx context.Context) ([]*ContributionAccountVerification, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ContributionAccountVerification, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ContributionAccountVerificationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ContributionAccountVerificationCreateBulk) SaveX(ctx context.Context) []*ContributionAccountVerification {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ContributionAccountVerificationCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ContributionAccountVerificationCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ContributionAccountVerification.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ContributionAccountVerificationUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ContributionAccountVerificationCreateBulk) OnConflict(opts ...sql.ConflictOption) *ContributionAccountVerificationUpsertBulk {
	_c.conflict = opts
	return &ContributionAccountVerificationUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ContributionAccountVerification.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ContributionAccountVerificationCreateBulk) OnConflictColumns(columns ...string) *ContributionAccountVerificationUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ContributionAccountVerificationUpsertBulk{
		create: _c,
	}
}

// ContributionAccountVerificationUpsertBulk is the builder for "upsert"-ing
// a bulk of ContributionAccountVerification nodes.
type ContributionAccountVerificationUpsertBulk struct {
	create *ContributionAccountVerificationCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ContributionAccountVerification.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ContributionAccountVerificationUpsertBulk) UpdateNewValues() *ContributionAccountVerificationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(contributionaccountverification.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ContributionAccountVerification.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ContributionAccountVerificationUpsertBulk) Ignore() *ContributionAccountVerificationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ContributionAccountVerificationUpsertBulk) DoNothing() *ContributionAccountVerificationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ContributionAccountVerificationCreateBulk.OnConflict
// documentation for more info.
func (u *ContributionAccountVerificationUpsertBulk) Update(set func(*ContributionAccountVerificationUpsert)) *ContributionAccountVerificationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ContributionAccountVerificationUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ContributionAccountVerificationUpsertBulk) SetUpdatedAt(v time.Time) *ContributionAccountVerificationUpsertBulk {
	return u.Update(func(s *ContributionAccountVerificationUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ContributionAccountVerificationUpsertBulk) UpdateUpdatedAt() *ContributionAccountVerificationUpsertBulk {
	return u.Update(func(s *ContributionAccountVerificationUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetAccountID sets the "account_id" field.
func (u *ContributionAccountVerificationUpsertBulk) SetAccountID(v int64) *ContributionAccountVerificationUpsertBulk {
	return u.Update(func(s *ContributionAccountVerificationUpsert) {
		s.SetAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *ContributionAccountVerificationUpsertBulk) UpdateAccountID() *ContributionAccountVerificationUpsertBulk {
	return u.Update(func(s *ContributionAccountVerificationUpsert) {
		s.UpdateAccountID()
	})
}

// SetPlatform sets the "platform" field.
func (u *ContributionAccountVerificationUpsertBulk) SetPlatform(v string) *ContributionAccountVerificationUpsertBulk {
	return u.Update(func(s *ContributionAccountVerificationUpsert) {
		s.SetPlatform(v)
	})
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *ContributionAccountVerificationUpsertBulk) UpdatePlatform() *ContributionAccountVerificationUpsertBulk {
	return u.Update(func(s *ContributionAccountVerificationUpsert) {
		s.UpdatePlatform()
	})
}

// SetStatus sets the "status" field.
func (u *ContributionAccountVerificationUpsertBulk) SetStatus(v string) *ContributionAccountVerificationUpsertBulk {
	return u.Update(func(s *ContributionAccountVerificationUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ContributionAccountVerificationUpsertBulk) UpdateStatus() *ContributionAccountVerificationUpsertBulk {
	return u.Update(func(s *ContributionAccountVerificationUpsert) {
		s.UpdateStatus()
	})
}

// SetModelFamily sets the "model_family" field.
func (u *ContributionAccountVerificationUpsertBulk) SetModelFamily(v string) *ContributionAccountVerificationUpsertBulk {
	return u.Update(func(s *ContributionAccountVerificationUpsert) {
		s.SetModelFamily(v)
	})
}

// UpdateModelFamily sets the "model_family" field to the value that was provided on create.
func (u *ContributionAccountVerificationUpsertBulk) UpdateModelFamily() *ContributionAccountVerificationUpsertBulk {
	return u.Update(func(s *ContributionAccountVerificationUpsert) {
		s.UpdateModelFamily()
	})
}

// SetSourceKind sets the "source_kind" field.
func (u *ContributionAccountVerificationUpsertBulk) SetSourceKind(v string) *ContributionAccountVerificationUpsertBulk {
	return u.Update(func(s *ContributionAccountVerificationUpsert) {
		s.SetSourceKind(v)
	})
}

// UpdateSourceKind sets the "source_kind" field to the value that was provided on create.
func (u *ContributionAccountVerificationUpsertBulk) UpdateSourceKind() *ContributionAccountVerificationUpsertBulk {
	return u.Update(func(s *ContributionAccountVerificationUpsert) {
		s.UpdateSourceKind()
	})
}

// SetTestedModel sets the "tested_model" field.
func (u *ContributionAccountVerificationUpsertBulk) SetTestedModel(v string) *ContributionAccountVerificationUpsertBulk {
	return u.Update(func(s *ContributionAccountVerificationUpsert) {
		s.SetTestedModel(v)
	})
}

// UpdateTestedModel sets the "tested_model" field to the value that was provided on create.
func (u *ContributionAccountVerificationUpsertBulk) UpdateTestedModel() *ContributionAccountVerificationUpsertBulk {
	return u.Update(func(s *ContributionAccountVerificationUpsert) {
		s.UpdateTestedModel()
	})
}

// ClearTestedModel clears the value of the "tested_model" field.
func (u *ContributionAccountVerificationUpsertBulk) ClearTestedModel() *ContributionAccountVerificationUpsertBulk {
	return u.Update(func(s *ContributionAccountVerificationUpsert) {
		s.ClearTestedModel()
	})
}

// SetTestedAt sets the "tested_at" field.
func (u *ContributionAccountVerificationUpsertBulk) SetTestedAt(v time.Time) *ContributionAccountVerificationUpsertBulk {
	return u.Update(func(s *ContributionAccountVerificationUpsert) {
		s.SetTestedAt(v)
	})
}

// UpdateTestedAt sets the "tested_at" field to the value that was provided on create.
func (u *ContributionAccountVerificationUpsertBulk) UpdateTestedAt() *ContributionAccountVerificationUpsertBulk {
	return u.Update(func(s *ContributionAccountVerificationUpsert) {
		s.UpdateTestedAt()
	})
}

// ClearTestedAt clears the value of the "tested_at" field.
func (u *ContributionAccountVerificationUpsertBulk) ClearTestedAt() *ContributionAccountVerificationUpsertBulk {
	return u.Update(func(s *ContributionAccountVerificationUpsert) {
		s.ClearTestedAt()
	})
}

// SetRedactedErrorSummary sets the "redacted_error_summary" field.
func (u *ContributionAccountVerificationUpsertBulk) SetRedactedErrorSummary(v string) *ContributionAccountVerificationUpsertBulk {
	return u.Update(func(s *ContributionAccountVerificationUpsert) {
		s.SetRedactedErrorSummary(v)
	})
}

// UpdateRedactedErrorSummary sets the "redacted_error_summary" field to the value that was provided on create.
func (u *ContributionAccountVerificationUpsertBulk) UpdateRedactedErrorSummary() *ContributionAccountVerificationUpsertBulk {
	return u.Update(func(s *ContributionAccountVerificationUpsert) {
		s.UpdateRedactedErrorSummary()
	})
}

// ClearRedactedErrorSummary clears the value of the "redacted_error_summary" field.
func (u *ContributionAccountVerificationUpsertBulk) ClearRedactedErrorSummary() *ContributionAccountVerificationUpsertBulk {
	return u.Update(func(s *ContributionAccountVerificationUpsert) {
		s.ClearRedactedErrorSummary()
	})
}

// Exec executes the query.
func (u *ContributionAccountVerificationUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ContributionAccountVerificationCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ContributionAccountVerificationCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ContributionAccountVerificationUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
