// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/contributionroom"
	"github.com/Wei-Shaw/sub2api/ent/contributionroomaccount"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/Wei-Shaw/sub2api/ent/usercontributionroompreference"
)

// ContributionRoomQuery is the builder for querying ContributionRoom entities.
type ContributionRoomQuery struct {
	config
	ctx             *QueryContext
	order           []contributionroom.OrderOption
	inters          []Interceptor
	predicates      []predicate.ContributionRoom
	withOwner       *UserQuery
	withAccounts    *ContributionRoomAccountQuery
	withPreferences *UserContributionRoomPreferenceQuery
	modifiers       []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ContributionRoomQuery builder.
func (_q *ContributionRoomQuery) Where(ps ...predicate.ContributionRoom) *ContributionRoomQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *ContributionRoomQuery) Limit(limit int) *ContributionRoomQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *ContributionRoomQuery) Offset(offset int) *ContributionRoomQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *ContributionRoomQuery) Unique(unique bool) *ContributionRoomQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *ContributionRoomQuery) Order(o ...contributionroom.OrderOption) *ContributionRoomQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryOwner chains the current query on the "owner" edge.
func (_q *ContributionRoomQuery) QueryOwner() *UserQuery {
	query := (&UserClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(contributionroom.Table, contributionroom.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, contributionroom.OwnerTable, contributionroom.OwnerColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryAccounts chains the current query on the "accounts" edge.
func (_q *ContributionRoomQuery) QueryAccounts() *ContributionRoomAccountQuery {
	query := (&ContributionRoomAccountClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(contributionroom.Table, contributionroom.FieldID, selector),
			sqlgraph.To(contributionroomaccount.Table, contributionroomaccount.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, contributionroom.AccountsTable, contributionroom.AccountsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryPreferences chains the current query on the "preferences" edge.
func (_q *ContributionRoomQuery) QueryPreferences() *UserContributionRoomPreferenceQuery {
	query := (&UserContributionRoomPreferenceClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(contributionroom.Table, contributionroom.FieldID, selector),
			sqlgraph.To(usercontributionroompreference.Table, usercontributionroompreference.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, contributionroom.PreferencesTable, contributionroom.PreferencesColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first ContributionRoom entity from the query.
// Returns a *NotFoundError when no ContributionRoom was found.
func (_q *ContributionRoomQuery) First(ctx context.Context) (*ContributionRoom, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{contributionroom.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *ContributionRoomQuery) FirstX(ctx context.Context) *ContributionRoom {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ContributionRoom ID from the query.
// Returns a *NotFoundError when no ContributionRoom ID was found.
func (_q *ContributionRoomQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{contributionroom.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *ContributionRoomQuery) FirstIDX(ctx context.Context) int64 {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ContributionRoom entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ContributionRoom entity is found.
// Returns a *NotFoundError when no ContributionRoom entities are found.
func (_q *ContributionRoomQuery) Only(ctx context.Context) (*ContributionRoom, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{contributionroom.Label}
	default:
		return nil, &NotSingularError{contributionroom.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *ContributionRoomQuery) OnlyX(ctx context.Context) *ContributionRoom {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ContributionRoom ID in the query.
// Returns a *NotSingularError when more than one ContributionRoom ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *ContributionRoomQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{contributionroom.Label}
	default:
		err = &NotSingularError{contributionroom.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *ContributionRoomQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ContributionRooms.
func (_q *ContributionRoomQuery) All(ctx context.Context) ([]*ContributionRoom, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ContributionRoom, *ContributionRoomQuery]()
	return withInterceptors[[]*ContributionRoom](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *ContributionRoomQuery) AllX(ctx context.Context) []*ContributionRoom {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ContributionRoom IDs.
func (_q *ContributionRoomQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(contributionroom.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *ContributionRoomQuery) IDsX(ctx context.Context) []int64 {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *ContributionRoomQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*ContributionRoomQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *ContributionRoomQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *ContributionRoomQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *ContributionRoomQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ContributionRoomQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *ContributionRoomQuery) Clone() *ContributionRoomQuery {
	if _q == nil {
		return nil
	}
	return &ContributionRoomQuery{
		config:          _q.config,
		ctx:             _q.ctx.Clone(),
		order:           append([]contributionroom.OrderOption{}, _q.order...),
		inters:          append([]Interceptor{}, _q.inters...),
		predicates:      append([]predicate.ContributionRoom{}, _q.predicates...),
		withOwner:       _q.withOwner.Clone(),
		withAccounts:    _q.withAccounts.Clone(),
		withPreferences: _q.withPreferences.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithOwner tells the query-builder to eager-load the nodes that are connected to
// the "owner" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ContributionRoomQuery) WithOwner(opts ...func(*UserQuery)) *ContributionRoomQuery {
	query := (&UserClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withOwner = query
	return _q
}

// WithAccounts tells the query-builder to eager-load the nodes that are connected to
// the "accounts" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ContributionRoomQuery) WithAccounts(opts ...func(*ContributionRoomAccountQuery)) *ContributionRoomQuery {
	query := (&ContributionRoomAccountClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withAccounts = query
	return _q
}

// WithPreferences tells the query-builder to eager-load the nodes that are connected to
// the "preferences" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ContributionRoomQuery) WithPreferences(opts ...func(*UserContributionRoomPreferenceQuery)) *ContributionRoomQuery {
	query := (&UserContributionRoomPreferenceClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withPreferences = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ContributionRoom.Query().
//		GroupBy(contributionroom.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *ContributionRoomQuery) GroupBy(field string, fields ...string) *ContributionRoomGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ContributionRoomGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = contributionroom.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.ContributionRoom.Query().
//		Select(contributionroom.FieldCreatedAt).
//		Scan(ctx, &v)
func (_q *ContributionRoomQuery) Select(fields ...string) *ContributionRoomSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &ContributionRoomSelect{ContributionRoomQuery: _q}
	sbuild.label = contributionroom.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ContributionRoomSelect configured with the given aggregations.
func (_q *ContributionRoomQuery) Aggregate(fns ...AggregateFunc) *ContributionRoomSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *ContributionRoomQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !contributionroom.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *ContributionRoomQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ContributionRoom, error) {
	var (
		nodes       = []*ContributionRoom{}
		_spec       = _q.querySpec()
		loadedTypes = [3]bool{
			_q.withOwner != nil,
			_q.withAccounts != nil,
			_q.withPreferences != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ContributionRoom).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ContributionRoom{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withOwner; query != nil {
		if err := _q.loadOwner(ctx, query, nodes, nil,
			func(n *ContributionRoom, e *User) { n.Edges.Owner = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withAccounts; query != nil {
		if err := _q.loadAccounts(ctx, query, nodes,
			func(n *ContributionRoom) { n.Edges.Accounts = []*ContributionRoomAccount{} },
			func(n *ContributionRoom, e *ContributionRoomAccount) { n.Edges.Accounts = append(n.Edges.Accounts, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withPreferences; query != nil {
		if err := _q.loadPreferences(ctx, query, nodes,
			func(n *ContributionRoom) { n.Edges.Preferences = []*UserContributionRoomPreference{} },
			func(n *ContributionRoom, e *UserContributionRoomPreference) {
				n.Edges.Preferences = append(n.Edges.Preferences, e)
			}); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *ContributionRoomQuery) loadOwner(ctx context.Context, query *UserQuery, nodes []*ContributionRoom, init func(*ContributionRoom), assign func(*ContributionRoom, *User)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*ContributionRoom)
	for i := range nodes {
		fk := nodes[i].OwnerUserID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "owner_user_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *ContributionRoomQuery) loadAccounts(ctx context.Context, query *ContributionRoomAccountQuery, nodes []*ContributionRoom, init func(*ContributionRoom), assign func(*ContributionRoom, *ContributionRoomAccount)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int64]*ContributionRoom)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(contributionroomaccount.FieldRoomID)
	}
	query.Where(predicate.ContributionRoomAccount(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(contributionroom.AccountsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.RoomID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "room_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *ContributionRoomQuery) loadPreferences(ctx context.Context, query *UserContributionRoomPreferenceQuery, nodes []*ContributionRoom, init func(*ContributionRoom), assign func(*ContributionRoom, *UserContributionRoomPreference)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int64]*ContributionRoom)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(usercontributionroompreference.FieldRoomID)
	}
	query.Where(predicate.UserContributionRoomPreference(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(contributionroom.PreferencesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.RoomID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "room_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *ContributionRoomQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *ContributionRoomQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(contributionroom.Table, contributionroom.Columns, sqlgraph.NewFieldSpec(contributionroom.FieldID, field.TypeInt64))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, contributionroom.FieldID)
		for i := range fields {
			if fields[i] != contributionroom.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withOwner != nil {
			_spec.Node.AddColumnOnce(contributionroom.FieldOwnerUserID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *ContributionRoomQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(contributionroom.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = contributionroom.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (_q *ContributionRoomQuery) ForUpdate(opts ...sql.LockOption) *ContributionRoomQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return _q
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (_q *ContributionRoomQuery) ForShare(opts ...sql.LockOption) *ContributionRoomQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return _q
}

// ContributionRoomGroupBy is the group-by builder for ContributionRoom entities.
type ContributionRoomGroupBy struct {
	selector
	build *ContributionRoomQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *ContributionRoomGroupBy) Aggregate(fns ...AggregateFunc) *ContributionRoomGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *ContributionRoomGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ContributionRoomQuery, *ContributionRoomGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *ContributionRoomGroupBy) sqlScan(ctx context.Context, root *ContributionRoomQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ContributionRoomSelect is the builder for selecting fields of ContributionRoom entities.
type ContributionRoomSelect struct {
	*ContributionRoomQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *ContributionRoomSelect) Aggregate(fns ...AggregateFunc) *ContributionRoomSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *ContributionRoomSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ContributionRoomQuery, *ContributionRoomSelect](ctx, _s.ContributionRoomQuery, _s, _s.inters, v)
}

func (_s *ContributionRoomSelect) sqlScan(ctx context.Context, root *ContributionRoomQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
