// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/account"
	"github.com/Wei-Shaw/sub2api/ent/contributionroom"
	"github.com/Wei-Shaw/sub2api/ent/contributionroomaccount"
)

// ContributionRoomAccountCreate is the builder for creating a ContributionRoomAccount entity.
type ContributionRoomAccountCreate struct {
	config
	mutation *ContributionRoomAccountMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *ContributionRoomAccountCreate) SetCreatedAt(v time.Time) *ContributionRoomAccountCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ContributionRoomAccountCreate) SetNillableCreatedAt(v *time.Time) *ContributionRoomAccountCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ContributionRoomAccountCreate) SetUpdatedAt(v time.Time) *ContributionRoomAccountCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ContributionRoomAccountCreate) SetNillableUpdatedAt(v *time.Time) *ContributionRoomAccountCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetRoomID sets the "room_id" field.
func (_c *ContributionRoomAccountCreate) SetRoomID(v int64) *ContributionRoomAccountCreate {
	_c.mutation.SetRoomID(v)
	return _c
}

// SetAccountID sets the "account_id" field.
func (_c *ContributionRoomAccountCreate) SetAccountID(v int64) *ContributionRoomAccountCreate {
	_c.mutation.SetAccountID(v)
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *ContributionRoomAccountCreate) SetEnabled(v bool) *ContributionRoomAccountCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *ContributionRoomAccountCreate) SetNillableEnabled(v *bool) *ContributionRoomAccountCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetShareConcurrency sets the "share_concurrency" field.
func (_c *ContributionRoomAccountCreate) SetShareConcurrency(v int) *ContributionRoomAccountCreate {
	_c.mutation.SetShareConcurrency(v)
	return _c
}

// SetNillableShareConcurrency sets the "share_concurrency" field if the given value is not nil.
func (_c *ContributionRoomAccountCreate) SetNillableShareConcurrency(v *int) *ContributionRoomAccountCreate {
	if v != nil {
		_c.SetShareConcurrency(*v)
	}
	return _c
}

// SetShareBudgetUsd sets the "share_budget_usd" field.
func (_c *ContributionRoomAccountCreate) SetShareBudgetUsd(v float64) *ContributionRoomAccountCreate {
	_c.mutation.SetShareBudgetUsd(v)
	return _c
}

// SetNillableShareBudgetUsd sets the "share_budget_usd" field if the given value is not nil.
func (_c *ContributionRoomAccountCreate) SetNillableShareBudgetUsd(v *float64) *ContributionRoomAccountCreate {
	if v != nil {
		_c.SetShareBudgetUsd(*v)
	}
	return _c
}

// SetShareUsedUsd sets the "share_used_usd" field.
func (_c *ContributionRoomAccountCreate) SetShareUsedUsd(v float64) *ContributionRoomAccountCreate {
	_c.mutation.SetShareUsedUsd(v)
	return _c
}

// SetNillableShareUsedUsd sets the "share_used_usd" field if the given value is not nil.
func (_c *ContributionRoomAccountCreate) SetNillableShareUsedUsd(v *float64) *ContributionRoomAccountCreate {
	if v != nil {
		_c.SetShareUsedUsd(*v)
	}
	return _c
}

// SetVerifiedAt sets the "verified_at" field.
func (_c *ContributionRoomAccountCreate) SetVerifiedAt(v time.Time) *ContributionRoomAccountCreate {
	_c.mutation.SetVerifiedAt(v)
	return _c
}

// SetNillableVerifiedAt sets the "verified_at" field if the given value is not nil.
func (_c *ContributionRoomAccountCreate) SetNillableVerifiedAt(v *time.Time) *ContributionRoomAccountCreate {
	if v != nil {
		_c.SetVerifiedAt(*v)
	}
	return _c
}

// SetRoom sets the "room" edge to the ContributionRoom entity.
func (_c *ContributionRoomAccountCreate) SetRoom(v *ContributionRoom) *ContributionRoomAccountCreate {
	return _c.SetRoomID(v.ID)
}

// SetAccount sets the "account" edge to the Account entity.
func (_c *ContributionRoomAccountCreate) SetAccount(v *Account) *ContributionRoomAccountCreate {
	return _c.SetAccountID(v.ID)
}

// Mutation returns the ContributionRoomAccountMutation object of the builder.
func (_c *ContributionRoomAccountCreate) Mutation() *ContributionRoomAccountMutation {
	return _c.mutation
}

// Save creates the ContributionRoomAccount in the database.
func (_c *ContributionRoomAccountCreate) Save(ctx context.Context) (*ContributionRoomAccount, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ContributionRoomAccountCreate) SaveX(ctx context.Context) *ContributionRoomAccount {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ContributionRoomAccountCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ContributionRoomAccountCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ContributionRoomAccountCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := contributionroomaccount.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := contributionroomaccount.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		v := contributionroomaccount.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
	if _, ok := _c.mutation.ShareConcurrency(); !ok {
		v := contributionroomaccount.DefaultShareConcurrency
		_c.mutation.SetShareConcurrency(v)
	}
	if _, ok := _c.mutation.ShareBudgetUsd(); !ok {
		v := contributionroomaccount.DefaultShareBudgetUsd
		_c.mutation.SetShareBudgetUsd(v)
	}
	if _, ok := _c.mutation.ShareUsedUsd(); !ok {
		v := contributionroomaccount.DefaultShareUsedUsd
		_c.mutation.SetShareUsedUsd(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ContributionRoomAccountCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ContributionRoomAccount.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ContributionRoomAccount.updated_at"`)}
	}
	if _, ok := _c.mutation.RoomID(); !ok {
		return &ValidationError{Name: "room_id", err: errors.New(`ent: missing required field "ContributionRoomAccount.room_id"`)}
	}
	if _, ok := _c.mutation.AccountID(); !ok {
		return &ValidationError{Name: "account_id", err: errors.New(`ent: missing required field "ContributionRoomAccount.account_id"`)}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "ContributionRoomAccount.enabled"`)}
	}
	if _, ok := _c.mutation.ShareConcurrency(); !ok {
		return &ValidationError{Name: "share_concurrency", err: errors.New(`ent: missing required field "ContributionRoomAccount.share_concurrency"`)}
	}
	if _, ok := _c.mutation.ShareBudgetUsd(); !ok {
		return &ValidationError{Name: "share_budget_usd", err: errors.New(`ent: missing required field "ContributionRoomAccount.share_budget_usd"`)}
	}
	if _, ok := _c.mutation.ShareUsedUsd(); !ok {
		return &ValidationError{Name: "share_used_usd", err: errors.New(`ent: missing required field "ContributionRoomAccount.share_used_usd"`)}
	}
	if len(_c.mutation.RoomIDs()) == 0 {
		return &ValidationError{Name: "room", err: errors.New(`ent: missing required edge "ContributionRoomAccount.room"`)}
	}
	if len(_c.mutation.AccountIDs()) == 0 {
		return &ValidationError{Name: "account", err: errors.New(`ent: missing required edge "ContributionRoomAccount.account"`)}
	}
	return nil
}

func (_c *ContributionRoomAccountCreate) sqlSave(ctx context.Context) (*ContributionRoomAccount, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ContributionRoomAccountCreate) createSpec() (*ContributionRoomAccount, *sqlgraph.CreateSpec) {
	var (
		_node = &ContributionRoomAccount{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(contributionroomaccount.Table, sqlgraph.NewFieldSpec(contributionroomaccount.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(contributionroomaccount.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(contributionroomaccount.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(contributionroomaccount.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.ShareConcurrency(); ok {
		_spec.SetField(contributionroomaccount.FieldShareConcurrency, field.TypeInt, value)
		_node.ShareConcurrency = value
	}
	if value, ok := _c.mutation.ShareBudgetUsd(); ok {
		_spec.SetField(contributionroomaccount.FieldShareBudgetUsd, field.TypeFloat64, value)
		_node.ShareBudgetUsd = value
	}
	if value, ok := _c.mutation.ShareUsedUsd(); ok {
		_spec.SetField(contributionroomaccount.FieldShareUsedUsd, field.TypeFloat64, value)
		_node.ShareUsedUsd = value
	}
	if value, ok := _c.mutation.VerifiedAt(); ok {
		_spec.SetField(contributionroomaccount.FieldVerifiedAt, field.TypeTime, value)
		_node.VerifiedAt = &value
	}
	if nodes := _c.mutation.RoomIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   contributionroomaccount.RoomTable,
			Columns: []string{contributionroomaccount.RoomColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(contributionroom.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.RoomID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   contributionroomaccount.AccountTable,
			Columns: []string{contributionroomaccount.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.AccountID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ContributionRoomAccount.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ContributionRoomAccountUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ContributionRoomAccountCreate) OnConflict(opts ...sql.ConflictOption) *ContributionRoomAccountUpsertOne {
	_c.conflict = opts
	return &ContributionRoomAccountUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ContributionRoomAccount.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ContributionRoomAccountCreate) OnConflictColumns(columns ...string) *ContributionRoomAccountUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ContributionRoomAccountUpsertOne{
		create: _c,
	}
}

type (
	// ContributionRoomAccountUpsertOne is the builder for "upsert"-ing
	//  one ContributionRoomAccount node.
	ContributionRoomAccountUpsertOne struct {
		create *ContributionRoomAccountCreate
	}

	// ContributionRoomAccountUpsert is the "OnConflict" setter.
	ContributionRoomAccountUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *ContributionRoomAccountUpsert) SetUpdatedAt(v time.Time) *ContributionRoomAccountUpsert {
	u.Set(contributionroomaccount.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ContributionRoomAccountUpsert) UpdateUpdatedAt() *ContributionRoomAccountUpsert {
	u.SetExcluded(contributionroomaccount.FieldUpdatedAt)
	return u
}

// SetRoomID sets the "room_id" field.
func (u *ContributionRoomAccountUpsert) SetRoomID(v int64) *ContributionRoomAccountUpsert {
	u.Set(contributionroomaccount.FieldRoomID, v)
	return u
}

// UpdateRoomID sets the "room_id" field to the value that was provided on create.
func (u *ContributionRoomAccountUpsert) UpdateRoomID() *ContributionRoomAccountUpsert {
	u.SetExcluded(contributionroomaccount.FieldRoomID)
	return u
}

// SetAccountID sets the "account_id" field.
func (u *ContributionRoomAccountUpsert) SetAccountID(v int64) *ContributionRoomAccountUpsert {
	u.Set(contributionroomaccount.FieldAccountID, v)
	return u
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *ContributionRoomAccountUpsert) UpdateAccountID() *ContributionRoomAccountUpsert {
	u.SetExcluded(contributionroomaccount.FieldAccountID)
	return u
}

// SetEnabled sets the "enabled" field.
func (u *ContributionRoomAccountUpsert) SetEnabled(v bool) *ContributionRoomAccountUpsert {
	u.Set(contributionroomaccount.FieldEnabled, v)
	return u
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *ContributionRoomAccountUpsert) UpdateEnabled() *ContributionRoomAccountUpsert {
	u.SetExcluded(contributionroomaccount.FieldEnabled)
	return u
}

// SetShareConcurrency sets the "share_concurrency" field.
func (u *ContributionRoomAccountUpsert) SetShareConcurrency(v int) *ContributionRoomAccountUpsert {
	u.Set(contributionroomaccount.FieldShareConcurrency, v)
	return u
}

// UpdateShareConcurrency sets the "share_concurrency" field to the value that was provided on create.
func (u *ContributionRoomAccountUpsert) UpdateShareConcurrency() *ContributionRoomAccountUpsert {
	u.SetExcluded(contributionroomaccount.FieldShareConcurrency)
	return u
}

// AddShareConcurrency adds v to the "share_concurrency" field.
func (u *ContributionRoomAccountUpsert) AddShareConcurrency(v int) *ContributionRoomAccountUpsert {
	u.Add(contributionroomaccount.FieldShareConcurrency, v)
	return u
}

// SetShareBudgetUsd sets the "share_budget_usd" field.
func (u *ContributionRoomAccountUpsert) SetShareBudgetUsd(v float64) *ContributionRoomAccountUpsert {
	u.Set(contributionroomaccount.FieldShareBudgetUsd, v)
	return u
}

// UpdateShareBudgetUsd sets the "share_budget_usd" field to the value that was provided on create.
func (u *ContributionRoomAccountUpsert) UpdateShareBudgetUsd() *ContributionRoomAccountUpsert {
	u.SetExcluded(contributionroomaccount.FieldShareBudgetUsd)
	return u
}

// AddShareBudgetUsd adds v to the "share_budget_usd" field.
func (u *ContributionRoomAccountUpsert) AddShareBudgetUsd(v float64) *ContributionRoomAccountUpsert {
	u.Add(contributionroomaccount.FieldShareBudgetUsd, v)
	return u
}

// SetShareUsedUsd sets the "share_used_usd" field.
func (u *ContributionRoomAccountUpsert) SetShareUsedUsd(v float64) *ContributionRoomAccountUpsert {
	u.Set(contributionroomaccount.FieldShareUsedUsd, v)
	return u
}

// UpdateShareUsedUsd sets the "share_used_usd" field to the value that was provided on create.
func (u *ContributionRoomAccountUpsert) UpdateShareUsedUsd() *ContributionRoomAccountUpsert {
	u.SetExcluded(contributionroomaccount.FieldShareUsedUsd)
	return u
}

// AddShareUsedUsd adds v to the "share_used_usd" field.
func (u *ContributionRoomAccountUpsert) AddShareUsedUsd(v float64) *ContributionRoomAccountUpsert {
	u.Add(contributionroomaccount.FieldShareUsedUsd, v)
	return u
}

// SetVerifiedAt sets the "verified_at" field.
func (u *ContributionRoomAccountUpsert) SetVerifiedAt(v time.Time) *ContributionRoomAccountUpsert {
	u.Set(contributionroomaccount.FieldVerifiedAt, v)
	return u
}

// UpdateVerifiedAt sets the "verified_at" field to the value that was provided on create.
func (u *ContributionRoomAccountUpsert) UpdateVerifiedAt() *ContributionRoomAccountUpsert {
	u.SetExcluded(contributionroomaccount.FieldVerifiedAt)
	return u
}

// ClearVerifiedAt clears the value of the "verified_at" field.
func (u *ContributionRoomAccountUpsert) ClearVerifiedAt() *ContributionRoomAccountUpsert {
	u.SetNull(contributionroomaccount.FieldVerifiedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.ContributionRoomAccount.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ContributionRoomAccountUpsertOne) UpdateNewValues() *ContributionRoomAccountUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(contributionroomaccount.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ContributionRoomAccount.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ContributionRoomAccountUpsertOne) Ignore() *ContributionRoomAccountUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ContributionRoomAccountUpsertOne) DoNothing() *ContributionRoomAccountUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ContributionRoomAccountCreate.OnConflict
// documentation for more info.
func (u *ContributionRoomAccountUpsertOne) Update(set func(*ContributionRoomAccountUpsert)) *ContributionRoomAccountUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ContributionRoomAccountUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ContributionRoomAccountUpsertOne) SetUpdatedAt(v time.Time) *ContributionRoomAccountUpsertOne {
	return u.Update(func(s *ContributionRoomAccountUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ContributionRoomAccountUpsertOne) UpdateUpdatedAt() *ContributionRoomAccountUpsertOne {
	return u.Update(func(s *ContributionRoomAccountUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetRoomID sets the "room_id" field.
func (u *ContributionRoomAccountUpsertOne) SetRoomID(v int64) *ContributionRoomAccountUpsertOne {
	return u.Update(func(s *ContributionRoomAccountUpsert) {
		s.SetRoomID(v)
	})
}

// UpdateRoomID sets the "room_id" field to the value that was provided on create.
func (u *ContributionRoomAccountUpsertOne) UpdateRoomID() *ContributionRoomAccountUpsertOne {
	return u.Update(func(s *ContributionRoomAccountUpsert) {
		s.UpdateRoomID()
	})
}

// SetAccountID sets the "account_id" field.
func (u *ContributionRoomAccountUpsertOne) SetAccountID(v int64) *ContributionRoomAccountUpsertOne {
	return u.Update(func(s *ContributionRoomAccountUpsert) {
		s.SetAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *ContributionRoomAccountUpsertOne) UpdateAccountID() *ContributionRoomAccountUpsertOne {
	return u.Update(func(s *ContributionRoomAccountUpsert) {
		s.UpdateAccountID()
	})
}

// SetEnabled sets the "enabled" field.
func (u *ContributionRoomAccountUpsertOne) SetEnabled(v bool) *ContributionRoomAccountUpsertOne {
	return u.Update(func(s *ContributionRoomAccountUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *ContributionRoomAccountUpsertOne) UpdateEnabled() *ContributionRoomAccountUpsertOne {
	return u.Update(func(s *ContributionRoomAccountUpsert) {
		s.UpdateEnabled()
	})
}

// SetShareConcurrency sets the "share_concurrency" field.
func (u *ContributionRoomAccountUpsertOne) SetShareConcurrency(v int) *ContributionRoomAccountUpsertOne {
	return u.Update(func(s *ContributionRoomAccountUpsert) {
		s.SetShareConcurrency(v)
	})
}

// AddShareConcurrency adds v to the "share_concurrency" field.
func (u *ContributionRoomAccountUpsertOne) AddShareConcurrency(v int) *ContributionRoomAccountUpsertOne {
	return u.Update(func(s *ContributionRoomAccountUpsert) {
		s.AddShareConcurrency(v)
	})
}

// UpdateShareConcurrency sets the "share_concurrency" field to the value that was provided on create.
func (u *ContributionRoomAccountUpsertOne) UpdateShareConcurrency() *ContributionRoomAccountUpsertOne {
	return u.Update(func(s *ContributionRoomAccountUpsert) {
		s.UpdateShareConcurrency()
	})
}

// SetShareBudgetUsd sets the "share_budget_usd" field.
func (u *ContributionRoomAccountUpsertOne) SetShareBudgetUsd(v float64) *ContributionRoomAccountUpsertOne {
	return u.Update(func(s *ContributionRoomAccountUpsert) {
		s.SetShareBudgetUsd(v)
	})
}

// AddShareBudgetUsd adds v to the "share_budget_usd" field.
func (u *ContributionRoomAccountUpsertOne) AddShareBudgetUsd(v float64) *ContributionRoomAccountUpsertOne {
	return u.Update(func(s *ContributionRoomAccountUpsert) {
		s.AddShareBudgetUsd(v)
	})
}

// UpdateShareBudgetUsd sets the "share_budget_usd" field to the value that was provided on create.
func (u *ContributionRoomAccountUpsertOne) UpdateShareBudgetUsd() *ContributionRoomAccountUpsertOne {
	return u.Update(func(s *ContributionRoomAccountUpsert) {
		s.UpdateShareBudgetUsd()
	})
}

// SetShareUsedUsd sets the "share_used_usd" field.
func (u *ContributionRoomAccountUpsertOne) SetShareUsedUsd(v float64) *ContributionRoomAccountUpsertOne {
	return u.Update(func(s *ContributionRoomAccountUpsert) {
		s.SetShareUsedUsd(v)
	})
}

// AddShareUsedUsd adds v to the "share_used_usd" field.
func (u *ContributionRoomAccountUpsertOne) AddShareUsedUsd(v float64) *ContributionRoomAccountUpsertOne {
	return u.Update(func(s *ContributionRoomAccountUpsert) {
		s.AddShareUsedUsd(v)
	})
}

// UpdateShareUsedUsd sets the "share_used_usd" field to the value that was provided on create.
func (u *ContributionRoomAccountUpsertOne) UpdateShareUsedUsd() *ContributionRoomAccountUpsertOne {
	return u.Update(func(s *ContributionRoomAccountUpsert) {
		s.UpdateShareUsedUsd()
	})
}

// SetVerifiedAt sets the "verified_at" field.
func (u *ContributionRoomAccountUpsertOne) SetVerifiedAt(v time.Time) *ContributionRoomAccountUpsertOne {
	return u.Update(func(s *ContributionRoomAccountUpsert) {
		s.SetVerifiedAt(v)
	})
}

// UpdateVerifiedAt sets the "verified_at" field to the value that was provided on create.
func (u *ContributionRoomAccountUpsertOne) UpdateVerifiedAt() *ContributionRoomAccountUpsertOne {
	return u.Update(func(s *ContributionRoomAccountUpsert) {
		s.UpdateVerifiedAt()
	})
}

// ClearVerifiedAt clears the value of the "verified_at" field.
func (u *ContributionRoomAccountUpsertOne) ClearVerifiedAt() *ContributionRoomAccountUpsertOne {
	return u.Update(func(s *ContributionRoomAccountUpsert) {
		s.ClearVerifiedAt()
	})
}

// Exec executes the query.
func (u *ContributionRoomAccountUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ContributionRoomAccountCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ContributionRoomAccountUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ContributionRoomAccountUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ContributionRoomAccountUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ContributionRoomAccountCreateBulk is the builder for creating many ContributionRoomAccount entities in bulk.
type ContributionRoomAccountCreateBulk struct {
	config
	err      error
	builders []*ContributionRoomAccountCreate
	conflict []sql.ConflictOption
}

// Save creates the ContributionRoomAccount entities in the database.
func (_c *ContributionRoomAccountCreateBulk) Save(ctx context.Context) ([]*ContributionRoomAccount, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ContributionRoomAccount, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ContributionRoomAccountMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ContributionRoomAccountCreateBulk) SaveX(ctx context.Context) []*ContributionRoomAccount {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ContributionRoomAccountCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ContributionRoomAccountCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ContributionRoomAccount.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ContributionRoomAccountUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ContributionRoomAccountCreateBulk) OnConflict(opts ...sql.ConflictOption) *ContributionRoomAccountUpsertBulk {
	_c.conflict = opts
	return &ContributionRoomAccountUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ContributionRoomAccount.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ContributionRoomAccountCreateBulk) OnConflictColumns(columns ...string) *ContributionRoomAccountUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ContributionRoomAccountUpsertBulk{
		create: _c,
	}
}

// ContributionRoomAccountUpsertBulk is the builder for "upsert"-ing
// a bulk of ContributionRoomAccount nodes.
type ContributionRoomAccountUpsertBulk struct {
	create *ContributionRoomAccountCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ContributionRoomAccount.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ContributionRoomAccountUpsertBulk) UpdateNewValues() *ContributionRoomAccountUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(contributionroomaccount.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ContributionRoomAccount.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ContributionRoomAccountUpsertBulk) Ignore() *ContributionRoomAccountUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ContributionRoomAccountUpsertBulk) DoNothing() *ContributionRoomAccountUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ContributionRoomAccountCreateBulk.OnConflict
// documentation for more info.
func (u *ContributionRoomAccountUpsertBulk) Update(set func(*ContributionRoomAccountUpsert)) *ContributionRoomAccountUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ContributionRoomAccountUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ContributionRoomAccountUpsertBulk) SetUpdatedAt(v time.Time) *ContributionRoomAccountUpsertBulk {
	return u.Update(func(s *ContributionRoomAccountUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ContributionRoomAccountUpsertBulk) UpdateUpdatedAt() *ContributionRoomAccountUpsertBulk {
	return u.Update(func(s *ContributionRoomAccountUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetRoomID sets the "room_id" field.
func (u *ContributionRoomAccountUpsertBulk) SetRoomID(v int64) *ContributionRoomAccountUpsertBulk {
	return u.Update(func(s *ContributionRoomAccountUpsert) {
		s.SetRoomID(v)
	})
}

// UpdateRoomID sets the "room_id" field to the value that was provided on create.
func (u *ContributionRoomAccountUpsertBulk) UpdateRoomID() *ContributionRoomAccountUpsertBulk {
	return u.Update(func(s *ContributionRoomAccountUpsert) {
		s.UpdateRoomID()
	})
}

// SetAccountID sets the "account_id" field.
func (u *ContributionRoomAccountUpsertBulk) SetAccountID(v int64) *ContributionRoomAccountUpsertBulk {
	return u.Update(func(s *ContributionRoomAccountUpsert) {
		s.SetAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *ContributionRoomAccountUpsertBulk) UpdateAccountID() *ContributionRoomAccountUpsertBulk {
	return u.Update(func(s *ContributionRoomAccountUpsert) {
		s.UpdateAccountID()
	})
}

// SetEnabled sets the "enabled" field.
func (u *ContributionRoomAccountUpsertBulk) SetEnabled(v bool) *ContributionRoomAccountUpsertBulk {
	return u.Update(func(s *ContributionRoomAccountUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *ContributionRoomAccountUpsertBulk) UpdateEnabled() *ContributionRoomAccountUpsertBulk {
	return u.Update(func(s *ContributionRoomAccountUpsert) {
		s.UpdateEnabled()
	})
}

// SetShareConcurrency sets the "share_concurrency" field.
func (u *ContributionRoomAccountUpsertBulk) SetShareConcurrency(v int) *ContributionRoomAccountUpsertBulk {
	return u.Update(func(s *ContributionRoomAccountUpsert) {
		s.SetShareConcurrency(v)
	})
}

// AddShareConcurrency adds v to the "share_concurrency" field.
func (u *ContributionRoomAccountUpsertBulk) AddShareConcurrency(v int) *ContributionRoomAccountUpsertBulk {
	return u.Update(func(s *ContributionRoomAccountUpsert) {
		s.AddShareConcurrency(v)
	})
}

// UpdateShareConcurrency sets the "share_concurrency" field to the value that was provided on create.
func (u *ContributionRoomAccountUpsertBulk) UpdateShareConcurrency() *ContributionRoomAccountUpsertBulk {
	return u.Update(func(s *ContributionRoomAccountUpsert) {
		s.UpdateShareConcurrency()
	})
}

// SetShareBudgetUsd sets the "share_budget_usd" field.
func (u *ContributionRoomAccountUpsertBulk) SetShareBudgetUsd(v float64) *ContributionRoomAccountUpsertBulk {
	return u.Update(func(s *ContributionRoomAccountUpsert) {
		s.SetShareBudgetUsd(v)
	})
}

// AddShareBudgetUsd adds v to the "share_budget_usd" field.
func (u *ContributionRoomAccountUpsertBulk) AddShareBudgetUsd(v float64) *ContributionRoomAccountUpsertBulk {
	return u.Update(func(s *ContributionRoomAccountUpsert) {
		s.AddShareBudgetUsd(v)
	})
}

// UpdateShareBudgetUsd sets the "share_budget_usd" field to the value that was provided on create.
func (u *ContributionRoomAccountUpsertBulk) UpdateShareBudgetUsd() *ContributionRoomAccountUpsertBulk {
	return u.Update(func(s *ContributionRoomAccountUpsert) {
		s.UpdateShareBudgetUsd()
	})
}

// SetShareUsedUsd sets the "share_used_usd" field.
func (u *ContributionRoomAccountUpsertBulk) SetShareUsedUsd(v float64) *ContributionRoomAccountUpsertBulk {
	return u.Update(func(s *ContributionRoomAccountUpsert) {
		s.SetShareUsedUsd(v)
	})
}

// AddShareUsedUsd adds v to the "share_used_usd" field.
func (u *ContributionRoomAccountUpsertBulk) AddShareUsedUsd(v float64) *ContributionRoomAccountUpsertBulk {
	return u.Update(func(s *ContributionRoomAccountUpsert) {
		s.AddShareUsedUsd(v)
	})
}

// UpdateShareUsedUsd sets the "share_used_usd" field to the value that was provided on create.
func (u *ContributionRoomAccountUpsertBulk) UpdateShareUsedUsd() *ContributionRoomAccountUpsertBulk {
	return u.Update(func(s *ContributionRoomAccountUpsert) {
		s.UpdateShareUsedUsd()
	})
}

// SetVerifiedAt sets the "verified_at" field.
func (u *ContributionRoomAccountUpsertBulk) SetVerifiedAt(v time.Time) *ContributionRoomAccountUpsertBulk {
	return u.Update(func(s *ContributionRoomAccountUpsert) {
		s.SetVerifiedAt(v)
	})
}

// UpdateVerifiedAt sets the "verified_at" field to the value that was provided on create.
func (u *ContributionRoomAccountUpsertBulk) UpdateVerifiedAt() *ContributionRoomAccountUpsertBulk {
	return u.Update(func(s *ContributionRoomAccountUpsert) {
		s.UpdateVerifiedAt()
	})
}

// ClearVerifiedAt clears the value of the "verified_at" field.
func (u *ContributionRoomAccountUpsertBulk) ClearVerifiedAt() *ContributionRoomAccountUpsertBulk {
	return u.Update(func(s *ContributionRoomAccountUpsert) {
		s.ClearVerifiedAt()
	})
}

// Exec executes the query.
func (u *ContributionRoomAccountUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ContributionRoomAccountCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ContributionRoomAccountCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ContributionRoomAccountUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
