// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/apikey"
	"github.com/Wei-Shaw/sub2api/ent/contributionroom"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/Wei-Shaw/sub2api/ent/usercontributionroompreference"
)

// UserContributionRoomPreferenceUpdate is the builder for updating UserContributionRoomPreference entities.
type UserContributionRoomPreferenceUpdate struct {
	config
	hooks    []Hook
	mutation *UserContributionRoomPreferenceMutation
}

// Where appends a list predicates to the UserContributionRoomPreferenceUpdate builder.
func (_u *UserContributionRoomPreferenceUpdate) Where(ps ...predicate.UserContributionRoomPreference) *UserContributionRoomPreferenceUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserContributionRoomPreferenceUpdate) SetUpdatedAt(v time.Time) *UserContributionRoomPreferenceUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *UserContributionRoomPreferenceUpdate) SetUserID(v int64) *UserContributionRoomPreferenceUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UserContributionRoomPreferenceUpdate) SetNillableUserID(v *int64) *UserContributionRoomPreferenceUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetAPIKeyID sets the "api_key_id" field.
func (_u *UserContributionRoomPreferenceUpdate) SetAPIKeyID(v int64) *UserContributionRoomPreferenceUpdate {
	_u.mutation.SetAPIKeyID(v)
	return _u
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_u *UserContributionRoomPreferenceUpdate) SetNillableAPIKeyID(v *int64) *UserContributionRoomPreferenceUpdate {
	if v != nil {
		_u.SetAPIKeyID(*v)
	}
	return _u
}

// SetRoomID sets the "room_id" field.
func (_u *UserContributionRoomPreferenceUpdate) SetRoomID(v int64) *UserContributionRoomPreferenceUpdate {
	_u.mutation.SetRoomID(v)
	return _u
}

// SetNillableRoomID sets the "room_id" field if the given value is not nil.
func (_u *UserContributionRoomPreferenceUpdate) SetNillableRoomID(v *int64) *UserContributionRoomPreferenceUpdate {
	if v != nil {
		_u.SetRoomID(*v)
	}
	return _u
}

// SetAllowPoolFallback sets the "allow_pool_fallback" field.
func (_u *UserContributionRoomPreferenceUpdate) SetAllowPoolFallback(v bool) *UserContributionRoomPreferenceUpdate {
	_u.mutation.SetAllowPoolFallback(v)
	return _u
}

// SetNillableAllowPoolFallback sets the "allow_pool_fallback" field if the given value is not nil.
func (_u *UserContributionRoomPreferenceUpdate) SetNillableAllowPoolFallback(v *bool) *UserContributionRoomPreferenceUpdate {
	if v != nil {
		_u.SetAllowPoolFallback(*v)
	}
	return _u
}

// SetFallbackGroupID sets the "fallback_group_id" field.
func (_u *UserContributionRoomPreferenceUpdate) SetFallbackGroupID(v int64) *UserContributionRoomPreferenceUpdate {
	_u.mutation.ResetFallbackGroupID()
	_u.mutation.SetFallbackGroupID(v)
	return _u
}

// SetNillableFallbackGroupID sets the "fallback_group_id" field if the given value is not nil.
func (_u *UserContributionRoomPreferenceUpdate) SetNillableFallbackGroupID(v *int64) *UserContributionRoomPreferenceUpdate {
	if v != nil {
		_u.SetFallbackGroupID(*v)
	}
	return _u
}

// AddFallbackGroupID adds value to the "fallback_group_id" field.
func (_u *UserContributionRoomPreferenceUpdate) AddFallbackGroupID(v int64) *UserContributionRoomPreferenceUpdate {
	_u.mutation.AddFallbackGroupID(v)
	return _u
}

// ClearFallbackGroupID clears the value of the "fallback_group_id" field.
func (_u *UserContributionRoomPreferenceUpdate) ClearFallbackGroupID() *UserContributionRoomPreferenceUpdate {
	_u.mutation.ClearFallbackGroupID()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *UserContributionRoomPreferenceUpdate) SetUser(v *User) *UserContributionRoomPreferenceUpdate {
	return _u.SetUserID(v.ID)
}

// SetAPIKey sets the "api_key" edge to the APIKey entity.
func (_u *UserContributionRoomPreferenceUpdate) SetAPIKey(v *APIKey) *UserContributionRoomPreferenceUpdate {
	return _u.SetAPIKeyID(v.ID)
}

// SetRoom sets the "room" edge to the ContributionRoom entity.
func (_u *UserContributionRoomPreferenceUpdate) SetRoom(v *ContributionRoom) *UserContributionRoomPreferenceUpdate {
	return _u.SetRoomID(v.ID)
}

// Mutation returns the UserContributionRoomPreferenceMutation object of the builder.
func (_u *UserContributionRoomPreferenceUpdate) Mutation() *UserContributionRoomPreferenceMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *UserContributionRoomPreferenceUpdate) ClearUser() *UserContributionRoomPreferenceUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearAPIKey clears the "api_key" edge to the APIKey entity.
func (_u *UserContributionRoomPreferenceUpdate) ClearAPIKey() *UserContributionRoomPreferenceUpdate {
	_u.mutation.ClearAPIKey()
	return _u
}

// ClearRoom clears the "room" edge to the ContributionRoom entity.
func (_u *UserContributionRoomPreferenceUpdate) ClearRoom() *UserContributionRoomPreferenceUpdate {
	_u.mutation.ClearRoom()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserContributionRoomPreferenceUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserContributionRoomPreferenceUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserContributionRoomPreferenceUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserContributionRoomPreferenceUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserContributionRoomPreferenceUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := usercontributionroompreference.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserContributionRoomPreferenceUpdate) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserContributionRoomPreference.user"`)
	}
	if _u.mutation.APIKeyCleared() && len(_u.mutation.APIKeyIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserContributionRoomPreference.api_key"`)
	}
	if _u.mutation.RoomCleared() && len(_u.mutation.RoomIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserContributionRoomPreference.room"`)
	}
	return nil
}

func (_u *UserContributionRoomPreferenceUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(usercontributionroompreference.Table, usercontributionroompreference.Columns, sqlgraph.NewFieldSpec(usercontributionroompreference.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(usercontributionroompreference.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.AllowPoolFallback(); ok {
		_spec.SetField(usercontributionroompreference.FieldAllowPoolFallback, field.TypeBool, value)
	}
	if value, ok := _u.mutation.FallbackGroupID(); ok {
		_spec.SetField(usercontributionroompreference.FieldFallbackGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedFallbackGroupID(); ok {
		_spec.AddField(usercontributionroompreference.FieldFallbackGroupID, field.TypeInt64, value)
	}
	if _u.mutation.FallbackGroupIDCleared() {
		_spec.ClearField(usercontributionroompreference.FieldFallbackGroupID, field.TypeInt64)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   usercontributionroompreference.UserTable,
			Columns: []string{usercontributionroompreference.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   usercontributionroompreference.UserTable,
			Columns: []string{usercontributionroompreference.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.APIKeyCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usercontributionroompreference.APIKeyTable,
			Columns: []string{usercontributionroompreference.APIKeyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.APIKeyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usercontributionroompreference.APIKeyTable,
			Columns: []string{usercontributionroompreference.APIKeyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RoomCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usercontributionroompreference.RoomTable,
			Columns: []string{usercontributionroompreference.RoomColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(contributionroom.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RoomIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usercontributionroompreference.RoomTable,
			Columns: []string{usercontributionroompreference.RoomColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(contributionroom.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{usercontributionroompreference.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserContributionRoomPreferenceUpdateOne is the builder for updating a single UserContributionRoomPreference entity.
type UserContributionRoomPreferenceUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserContributionRoomPreferenceMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserContributionRoomPreferenceUpdateOne) SetUpdatedAt(v time.Time) *UserContributionRoomPreferenceUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *UserContributionRoomPreferenceUpdateOne) SetUserID(v int64) *UserContributionRoomPreferenceUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UserContributionRoomPreferenceUpdateOne) SetNillableUserID(v *int64) *UserContributionRoomPreferenceUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetAPIKeyID sets the "api_key_id" field.
func (_u *UserContributionRoomPreferenceUpdateOne) SetAPIKeyID(v int64) *UserContributionRoomPreferenceUpdateOne {
	_u.mutation.SetAPIKeyID(v)
	return _u
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_u *UserContributionRoomPreferenceUpdateOne) SetNillableAPIKeyID(v *int64) *UserContributionRoomPreferenceUpdateOne {
	if v != nil {
		_u.SetAPIKeyID(*v)
	}
	return _u
}

// SetRoomID sets the "room_id" field.
func (_u *UserContributionRoomPreferenceUpdateOne) SetRoomID(v int64) *UserContributionRoomPreferenceUpdateOne {
	_u.mutation.SetRoomID(v)
	return _u
}

// SetNillableRoomID sets the "room_id" field if the given value is not nil.
func (_u *UserContributionRoomPreferenceUpdateOne) SetNillableRoomID(v *int64) *UserContributionRoomPreferenceUpdateOne {
	if v != nil {
		_u.SetRoomID(*v)
	}
	return _u
}

// SetAllowPoolFallback sets the "allow_pool_fallback" field.
func (_u *UserContributionRoomPreferenceUpdateOne) SetAllowPoolFallback(v bool) *UserContributionRoomPreferenceUpdateOne {
	_u.mutation.SetAllowPoolFallback(v)
	return _u
}

// SetNillableAllowPoolFallback sets the "allow_pool_fallback" field if the given value is not nil.
func (_u *UserContributionRoomPreferenceUpdateOne) SetNillableAllowPoolFallback(v *bool) *UserContributionRoomPreferenceUpdateOne {
	if v != nil {
		_u.SetAllowPoolFallback(*v)
	}
	return _u
}

// SetFallbackGroupID sets the "fallback_group_id" field.
func (_u *UserContributionRoomPreferenceUpdateOne) SetFallbackGroupID(v int64) *UserContributionRoomPreferenceUpdateOne {
	_u.mutation.ResetFallbackGroupID()
	_u.mutation.SetFallbackGroupID(v)
	return _u
}

// SetNillableFallbackGroupID sets the "fallback_group_id" field if the given value is not nil.
func (_u *UserContributionRoomPreferenceUpdateOne) SetNillableFallbackGroupID(v *int64) *UserContributionRoomPreferenceUpdateOne {
	if v != nil {
		_u.SetFallbackGroupID(*v)
	}
	return _u
}

// AddFallbackGroupID adds value to the "fallback_group_id" field.
func (_u *UserContributionRoomPreferenceUpdateOne) AddFallbackGroupID(v int64) *UserContributionRoomPreferenceUpdateOne {
	_u.mutation.AddFallbackGroupID(v)
	return _u
}

// ClearFallbackGroupID clears the value of the "fallback_group_id" field.
func (_u *UserContributionRoomPreferenceUpdateOne) ClearFallbackGroupID() *UserContributionRoomPreferenceUpdateOne {
	_u.mutation.ClearFallbackGroupID()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *UserContributionRoomPreferenceUpdateOne) SetUser(v *User) *UserContributionRoomPreferenceUpdateOne {
	return _u.SetUserID(v.ID)
}

// SetAPIKey sets the "api_key" edge to the APIKey entity.
func (_u *UserContributionRoomPreferenceUpdateOne) SetAPIKey(v *APIKey) *UserContributionRoomPreferenceUpdateOne {
	return _u.SetAPIKeyID(v.ID)
}

// SetRoom sets the "room" edge to the ContributionRoom entity.
func (_u *UserContributionRoomPreferenceUpdateOne) SetRoom(v *ContributionRoom) *UserContributionRoomPreferenceUpdateOne {
	return _u.SetRoomID(v.ID)
}

// Mutation returns the UserContributionRoomPreferenceMutation object of the builder.
func (_u *UserContributionRoomPreferenceUpdateOne) Mutation() *UserContributionRoomPreferenceMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *UserContributionRoomPreferenceUpdateOne) ClearUser() *UserContributionRoomPreferenceUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearAPIKey clears the "api_key" edge to the APIKey entity.
func (_u *UserContributionRoomPreferenceUpdateOne) ClearAPIKey() *UserContributionRoomPreferenceUpdateOne {
	_u.mutation.ClearAPIKey()
	return _u
}

// ClearRoom clears the "room" edge to the ContributionRoom entity.
func (_u *UserContributionRoomPreferenceUpdateOne) ClearRoom() *UserContributionRoomPreferenceUpdateOne {
	_u.mutation.ClearRoom()
	return _u
}

// Where appends a list predicates to the UserContributionRoomPreferenceUpdate builder.
func (_u *UserContributionRoomPreferenceUpdateOne) Where(ps ...predicate.UserContributionRoomPreference) *UserContributionRoomPreferenceUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserContributionRoomPreferenceUpdateOne) Select(field string, fields ...string) *UserContributionRoomPreferenceUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UserContributionRoomPreference entity.
func (_u *UserContributionRoomPreferenceUpdateOne) Save(ctx context.Context) (*UserContributionRoomPreference, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserContributionRoomPreferenceUpdateOne) SaveX(ctx context.Context) *UserContributionRoomPreference {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserContributionRoomPreferenceUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserContributionRoomPreferenceUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserContributionRoomPreferenceUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := usercontributionroompreference.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserContributionRoomPreferenceUpdateOne) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserContributionRoomPreference.user"`)
	}
	if _u.mutation.APIKeyCleared() && len(_u.mutation.APIKeyIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserContributionRoomPreference.api_key"`)
	}
	if _u.mutation.RoomCleared() && len(_u.mutation.RoomIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserContributionRoomPreference.room"`)
	}
	return nil
}

func (_u *UserContributionRoomPreferenceUpdateOne) sqlSave(ctx context.Context) (_node *UserContributionRoomPreference, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(usercontributionroompreference.Table, usercontributionroompreference.Columns, sqlgraph.NewFieldSpec(usercontributionroompreference.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UserContributionRoomPreference.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, usercontributionroompreference.FieldID)
		for _, f := range fields {
			if !usercontributionroompreference.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != usercontributionroompreference.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(usercontributionroompreference.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.AllowPoolFallback(); ok {
		_spec.SetField(usercontributionroompreference.FieldAllowPoolFallback, field.TypeBool, value)
	}
	if value, ok := _u.mutation.FallbackGroupID(); ok {
		_spec.SetField(usercontributionroompreference.FieldFallbackGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedFallbackGroupID(); ok {
		_spec.AddField(usercontributionroompreference.FieldFallbackGroupID, field.TypeInt64, value)
	}
	if _u.mutation.FallbackGroupIDCleared() {
		_spec.ClearField(usercontributionroompreference.FieldFallbackGroupID, field.TypeInt64)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   usercontributionroompreference.UserTable,
			Columns: []string{usercontributionroompreference.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   usercontributionroompreference.UserTable,
			Columns: []string{usercontributionroompreference.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.APIKeyCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usercontributionroompreference.APIKeyTable,
			Columns: []string{usercontributionroompreference.APIKeyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.APIKeyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usercontributionroompreference.APIKeyTable,
			Columns: []string{usercontributionroompreference.APIKeyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RoomCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usercontributionroompreference.RoomTable,
			Columns: []string{usercontributionroompreference.RoomColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(contributionroom.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RoomIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usercontributionroompreference.RoomTable,
			Columns: []string{usercontributionroompreference.RoomColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(contributionroom.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &UserContributionRoomPreference{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{usercontributionroompreference.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
