// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/apikey"
	"github.com/Wei-Shaw/sub2api/ent/contributionroom"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/Wei-Shaw/sub2api/ent/usercontributionroompreference"
)

// UserContributionRoomPreferenceCreate is the builder for creating a UserContributionRoomPreference entity.
type UserContributionRoomPreferenceCreate struct {
	config
	mutation *UserContributionRoomPreferenceMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *UserContributionRoomPreferenceCreate) SetCreatedAt(v time.Time) *UserContributionRoomPreferenceCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *UserContributionRoomPreferenceCreate) SetNillableCreatedAt(v *time.Time) *UserContributionRoomPreferenceCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *UserContributionRoomPreferenceCreate) SetUpdatedAt(v time.Time) *UserContributionRoomPreferenceCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *UserContributionRoomPreferenceCreate) SetNillableUpdatedAt(v *time.Time) *UserContributionRoomPreferenceCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *UserContributionRoomPreferenceCreate) SetUserID(v int64) *UserContributionRoomPreferenceCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetAPIKeyID sets the "api_key_id" field.
func (_c *UserContributionRoomPreferenceCreate) SetAPIKeyID(v int64) *UserContributionRoomPreferenceCreate {
	_c.mutation.SetAPIKeyID(v)
	return _c
}

// SetRoomID sets the "room_id" field.
func (_c *UserContributionRoomPreferenceCreate) SetRoomID(v int64) *UserContributionRoomPreferenceCreate {
	_c.mutation.SetRoomID(v)
	return _c
}

// SetAllowPoolFallback sets the "allow_pool_fallback" field.
func (_c *UserContributionRoomPreferenceCreate) SetAllowPoolFallback(v bool) *UserContributionRoomPreferenceCreate {
	_c.mutation.SetAllowPoolFallback(v)
	return _c
}

// SetNillableAllowPoolFallback sets the "allow_pool_fallback" field if the given value is not nil.
func (_c *UserContributionRoomPreferenceCreate) SetNillableAllowPoolFallback(v *bool) *UserContributionRoomPreferenceCreate {
	if v != nil {
		_c.SetAllowPoolFallback(*v)
	}
	return _c
}

// SetFallbackGroupID sets the "fallback_group_id" field.
func (_c *UserContributionRoomPreferenceCreate) SetFallbackGroupID(v int64) *UserContributionRoomPreferenceCreate {
	_c.mutation.SetFallbackGroupID(v)
	return _c
}

// SetNillableFallbackGroupID sets the "fallback_group_id" field if the given value is not nil.
func (_c *UserContributionRoomPreferenceCreate) SetNillableFallbackGroupID(v *int64) *UserContributionRoomPreferenceCreate {
	if v != nil {
		_c.SetFallbackGroupID(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *UserContributionRoomPreferenceCreate) SetUser(v *User) *UserContributionRoomPreferenceCreate {
	return _c.SetUserID(v.ID)
}

// SetAPIKey sets the "api_key" edge to the APIKey entity.
func (_c *UserContributionRoomPreferenceCreate) SetAPIKey(v *APIKey) *UserContributionRoomPreferenceCreate {
	return _c.SetAPIKeyID(v.ID)
}

// SetRoom sets the "room" edge to the ContributionRoom entity.
func (_c *UserContributionRoomPreferenceCreate) SetRoom(v *ContributionRoom) *UserContributionRoomPreferenceCreate {
	return _c.SetRoomID(v.ID)
}

// Mutation returns the UserContributionRoomPreferenceMutation object of the builder.
func (_c *UserContributionRoomPreferenceCreate) Mutation() *UserContributionRoomPreferenceMutation {
	return _c.mutation
}

// Save creates the UserContributionRoomPreference in the database.
func (_c *UserContributionRoomPreferenceCreate) Save(ctx context.Context) (*UserContributionRoomPreference, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UserContributionRoomPreferenceCreate) SaveX(ctx context.Context) *UserContributionRoomPreference {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserContributionRoomPreferenceCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserContributionRoomPreferenceCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UserContributionRoomPreferenceCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := usercontributionroompreference.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := usercontributionroompreference.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.AllowPoolFallback(); !ok {
		v := usercontributionroompreference.DefaultAllowPoolFallback
		_c.mutation.SetAllowPoolFallback(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UserContributionRoomPreferenceCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "UserContributionRoomPreference.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "UserContributionRoomPreference.updated_at"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "UserContributionRoomPreference.user_id"`)}
	}
	if _, ok := _c.mutation.APIKeyID(); !ok {
		return &ValidationError{Name: "api_key_id", err: errors.New(`ent: missing required field "UserContributionRoomPreference.api_key_id"`)}
	}
	if _, ok := _c.mutation.RoomID(); !ok {
		return &ValidationError{Name: "room_id", err: errors.New(`ent: missing required field "UserContributionRoomPreference.room_id"`)}
	}
	if _, ok := _c.mutation.AllowPoolFallback(); !ok {
		return &ValidationError{Name: "allow_pool_fallback", err: errors.New(`ent: missing required field "UserContributionRoomPreference.allow_pool_fallback"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "UserContributionRoomPreference.user"`)}
	}
	if len(_c.mutation.APIKeyIDs()) == 0 {
		return &ValidationError{Name: "api_key", err: errors.New(`ent: missing required edge "UserContributionRoomPreference.api_key"`)}
	}
	if len(_c.mutation.RoomIDs()) == 0 {
		return &ValidationError{Name: "room", err: errors.New(`ent: missing required edge "UserContributionRoomPreference.room"`)}
	}
	return nil
}

func (_c *UserContributionRoomPreferenceCreate) sqlSave(ctx context.Context) (*UserContributionRoomPreference, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UserContributionRoomPreferenceCreate) createSpec() (*UserContributionRoomPreference, *sqlgraph.CreateSpec) {
	var (
		_node = &UserContributionRoomPreference{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(usercontributionroompreference.Table, sqlgraph.NewFieldSpec(usercontributionroompreference.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(usercontributionroompreference.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(usercontributionroompreference.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.AllowPoolFallback(); ok {
		_spec.SetField(usercontributionroompreference.FieldAllowPoolFallback, field.TypeBool, value)
		_node.AllowPoolFallback = value
	}
	if value, ok := _c.mutation.FallbackGroupID(); ok {
		_spec.SetField(usercontributionroompreference.FieldFallbackGroupID, field.TypeInt64, value)
		_node.FallbackGroupID = &value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   usercontributionroompreference.UserTable,
			Columns: []string{usercontributionroompreference.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.APIKeyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usercontributionroompreference.APIKeyTable,
			Columns: []string{usercontributionroompreference.APIKeyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.APIKeyID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.RoomIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usercontributionroompreference.RoomTable,
			Columns: []string{usercontributionroompreference.RoomColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(contributionroom.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.RoomID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UserContributionRoomPreference.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UserContributionRoomPreferenceUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *UserContributionRoomPreferenceCreate) OnConflict(opts ...sql.ConflictOption) *UserContributionRoomPreferenceUpsertOne {
	_c.conflict = opts
	return &UserContributionRoomPreferenceUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UserContributionRoomPreference.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UserContributionRoomPreferenceCreate) OnConflictColumns(columns ...string) *UserContributionRoomPreferenceUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UserContributionRoomPreferenceUpsertOne{
		create: _c,
	}
}

type (
	// UserContributionRoomPreferenceUpsertOne is the builder for "upsert"-ing
	//  one UserContributionRoomPreference node.
	UserContributionRoomPreferenceUpsertOne struct {
		create *UserContributionRoomPreferenceCreate
	}

	// UserContributionRoomPreferenceUpsert is the "OnConflict" setter.
	UserContributionRoomPreferenceUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *UserContributionRoomPreferenceUpsert) SetUpdatedAt(v time.Time) *UserContributionRoomPreferenceUpsert {
	u.Set(usercontributionroompreference.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UserContributionRoomPreferenceUpsert) UpdateUpdatedAt() *UserContributionRoomPreferenceUpsert {
	u.SetExcluded(usercontributionroompreference.FieldUpdatedAt)
	return u
}

// SetUserID sets the "user_id" field.
func (u *UserContributionRoomPreferenceUpsert) SetUserID(v int64) *UserContributionRoomPreferenceUpsert {
	u.Set(usercontributionroompreference.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserContributionRoomPreferenceUpsert) UpdateUserID() *UserContributionRoomPreferenceUpsert {
	u.SetExcluded(usercontributionroompreference.FieldUserID)
	return u
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *UserContributionRoomPreferenceUpsert) SetAPIKeyID(v int64) *UserContributionRoomPreferenceUpsert {
	u.Set(usercontributionroompreference.FieldAPIKeyID, v)
	return u
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *UserContributionRoomPreferenceUpsert) UpdateAPIKeyID() *UserContributionRoomPreferenceUpsert {
	u.SetExcluded(usercontributionroompreference.FieldAPIKeyID)
	return u
}

// SetRoomID sets the "room_id" field.
func (u *UserContributionRoomPreferenceUpsert) SetRoomID(v int64) *UserContributionRoomPreferenceUpsert {
	u.Set(usercontributionroompreference.FieldRoomID, v)
	return u
}

// UpdateRoomID sets the "room_id" field to the value that was provided on create.
func (u *UserContributionRoomPreferenceUpsert) UpdateRoomID() *UserContributionRoomPreferenceUpsert {
	u.SetExcluded(usercontributionroompreference.FieldRoomID)
	return u
}

// SetAllowPoolFallback sets the "allow_pool_fallback" field.
func (u *UserContributionRoomPreferenceUpsert) SetAllowPoolFallback(v bool) *UserContributionRoomPreferenceUpsert {
	u.Set(usercontributionroompreference.FieldAllowPoolFallback, v)
	return u
}

// UpdateAllowPoolFallback sets the "allow_pool_fallback" field to the value that was provided on create.
func (u *UserContributionRoomPreferenceUpsert) UpdateAllowPoolFallback() *UserContributionRoomPreferenceUpsert {
	u.SetExcluded(usercontributionroompreference.FieldAllowPoolFallback)
	return u
}

// SetFallbackGroupID sets the "fallback_group_id" field.
func (u *UserContributionRoomPreferenceUpsert) SetFallbackGroupID(v int64) *UserContributionRoomPreferenceUpsert {
	u.Set(usercontributionroompreference.FieldFallbackGroupID, v)
	return u
}

// UpdateFallbackGroupID sets the "fallback_group_id" field to the value that was provided on create.
func (u *UserContributionRoomPreferenceUpsert) UpdateFallbackGroupID() *UserContributionRoomPreferenceUpsert {
	u.SetExcluded(usercontributionroompreference.FieldFallbackGroupID)
	return u
}

// AddFallbackGroupID adds v to the "fallback_group_id" field.
func (u *UserContributionRoomPreferenceUpsert) AddFallbackGroupID(v int64) *UserContributionRoomPreferenceUpsert {
	u.Add(usercontributionroompreference.FieldFallbackGroupID, v)
	return u
}

// ClearFallbackGroupID clears the value of the "fallback_group_id" field.
func (u *UserContributionRoomPreferenceUpsert) ClearFallbackGroupID() *UserContributionRoomPreferenceUpsert {
	u.SetNull(usercontributionroompreference.FieldFallbackGroupID)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.UserContributionRoomPreference.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UserContributionRoomPreferenceUpsertOne) UpdateNewValues() *UserContributionRoomPreferenceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(usercontributionroompreference.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UserContributionRoomPreference.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *UserContributionRoomPreferenceUpsertOne) Ignore() *UserContributionRoomPreferenceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UserContributionRoomPreferenceUpsertOne) DoNothing() *UserContributionRoomPreferenceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UserContributionRoomPreferenceCreate.OnConflict
// documentation for more info.
func (u *UserContributionRoomPreferenceUpsertOne) Update(set func(*UserContributionRoomPreferenceUpsert)) *UserContributionRoomPreferenceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UserContributionRoomPreferenceUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UserContributionRoomPreferenceUpsertOne) SetUpdatedAt(v time.Time) *UserContributionRoomPreferenceUpsertOne {
	return u.Update(func(s *UserContributionRoomPreferenceUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UserContributionRoomPreferenceUpsertOne) UpdateUpdatedAt() *UserContributionRoomPreferenceUpsertOne {
	return u.Update(func(s *UserContributionRoomPreferenceUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *UserContributionRoomPreferenceUpsertOne) SetUserID(v int64) *UserContributionRoomPreferenceUpsertOne {
	return u.Update(func(s *UserContributionRoomPreferenceUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserContributionRoomPreferenceUpsertOne) UpdateUserID() *UserContributionRoomPreferenceUpsertOne {
	return u.Update(func(s *UserContributionRoomPreferenceUpsert) {
		s.UpdateUserID()
	})
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *UserContributionRoomPreferenceUpsertOne) SetAPIKeyID(v int64) *UserContributionRoomPreferenceUpsertOne {
	return u.Update(func(s *UserContributionRoomPreferenceUpsert) {
		s.SetAPIKeyID(v)
	})
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *UserContributionRoomPreferenceUpsertOne) UpdateAPIKeyID() *UserContributionRoomPreferenceUpsertOne {
	return u.Update(func(s *UserContributionRoomPreferenceUpsert) {
		s.UpdateAPIKeyID()
	})
}

// SetRoomID sets the "room_id" field.
func (u *UserContributionRoomPreferenceUpsertOne) SetRoomID(v int64) *UserContributionRoomPreferenceUpsertOne {
	return u.Update(func(s *UserContributionRoomPreferenceUpsert) {
		s.SetRoomID(v)
	})
}

// UpdateRoomID sets the "room_id" field to the value that was provided on create.
func (u *UserContributionRoomPreferenceUpsertOne) UpdateRoomID() *UserContributionRoomPreferenceUpsertOne {
	return u.Update(func(s *UserContributionRoomPreferenceUpsert) {
		s.UpdateRoomID()
	})
}

// SetAllowPoolFallback sets the "allow_pool_fallback" field.
func (u *UserContributionRoomPreferenceUpsertOne) SetAllowPoolFallback(v bool) *UserContributionRoomPreferenceUpsertOne {
	return u.Update(func(s *UserContributionRoomPreferenceUpsert) {
		s.SetAllowPoolFallback(v)
	})
}

// UpdateAllowPoolFallback sets the "allow_pool_fallback" field to the value that was provided on create.
func (u *UserContributionRoomPreferenceUpsertOne) UpdateAllowPoolFallback() *UserContributionRoomPreferenceUpsertOne {
	return u.Update(func(s *UserContributionRoomPreferenceUpsert) {
		s.UpdateAllowPoolFallback()
	})
}

// SetFallbackGroupID sets the "fallback_group_id" field.
func (u *UserContributionRoomPreferenceUpsertOne) SetFallbackGroupID(v int64) *UserContributionRoomPreferenceUpsertOne {
	return u.Update(func(s *UserContributionRoomPreferenceUpsert) {
		s.SetFallbackGroupID(v)
	})
}

// AddFallbackGroupID adds v to the "fallback_group_id" field.
func (u *UserContributionRoomPreferenceUpsertOne) AddFallbackGroupID(v int64) *UserContributionRoomPreferenceUpsertOne {
	return u.Update(func(s *UserContributionRoomPreferenceUpsert) {
		s.AddFallbackGroupID(v)
	})
}

// UpdateFallbackGroupID sets the "fallback_group_id" field to the value that was provided on create.
func (u *UserContributionRoomPreferenceUpsertOne) UpdateFallbackGroupID() *UserContributionRoomPreferenceUpsertOne {
	return u.Update(func(s *UserContributionRoomPreferenceUpsert) {
		s.UpdateFallbackGroupID()
	})
}

// ClearFallbackGroupID clears the value of the "fallback_group_id" field.
func (u *UserContributionRoomPreferenceUpsertOne) ClearFallbackGroupID() *UserContributionRoomPreferenceUpsertOne {
	return u.Update(func(s *UserContributionRoomPreferenceUpsert) {
		s.ClearFallbackGroupID()
	})
}

// Exec executes the query.
func (u *UserContributionRoomPreferenceUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UserContributionRoomPreferenceCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UserContributionRoomPreferenceUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *UserContributionRoomPreferenceUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *UserContributionRoomPreferenceUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// UserContributionRoomPreferenceCreateBulk is the builder for creating many UserContributionRoomPreference entities in bulk.
type UserContributionRoomPreferenceCreateBulk struct {
	config
	err      error
	builders []*UserContributionRoomPreferenceCreate
	conflict []sql.ConflictOption
}

// Save creates the UserContributionRoomPreference entities in the database.
func (_c *UserContributionRoomPreferenceCreateBulk) Save(ctx context.Context) ([]*UserContributionRoomPreference, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UserContributionRoomPreference, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserContributionRoomPreferenceMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UserContributionRoomPreferenceCreateBulk) SaveX(ctx context.Context) []*UserContributionRoomPreference {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserContributionRoomPreferenceCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserContributionRoomPreferenceCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UserContributionRoomPreference.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UserContributionRoomPreferenceUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *UserContributionRoomPreferenceCreateBulk) OnConflict(opts ...sql.ConflictOption) *UserContributionRoomPreferenceUpsertBulk {
	_c.conflict = opts
	return &UserContributionRoomPreferenceUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UserContributionRoomPreference.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UserContributionRoomPreferenceCreateBulk) OnConflictColumns(columns ...string) *UserContributionRoomPreferenceUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UserContributionRoomPreferenceUpsertBulk{
		create: _c,
	}
}

// UserContributionRoomPreferenceUpsertBulk is the builder for "upsert"-ing
// a bulk of UserContributionRoomPreference nodes.
type UserContributionRoomPreferenceUpsertBulk struct {
	create *UserContributionRoomPreferenceCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.UserContributionRoomPreference.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UserContributionRoomPreferenceUpsertBulk) UpdateNewValues() *UserContributionRoomPreferenceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(usercontributionroompreference.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UserContributionRoomPreference.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *UserContributionRoomPreferenceUpsertBulk) Ignore() *UserContributionRoomPreferenceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UserContributionRoomPreferenceUpsertBulk) DoNothing() *UserContributionRoomPreferenceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UserContributionRoomPreferenceCreateBulk.OnConflict
// documentation for more info.
func (u *UserContributionRoomPreferenceUpsertBulk) Update(set func(*UserContributionRoomPreferenceUpsert)) *UserContributionRoomPreferenceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UserContributionRoomPreferenceUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UserContributionRoomPreferenceUpsertBulk) SetUpdatedAt(v time.Time) *UserContributionRoomPreferenceUpsertBulk {
	return u.Update(func(s *UserContributionRoomPreferenceUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UserContributionRoomPreferenceUpsertBulk) UpdateUpdatedAt() *UserContributionRoomPreferenceUpsertBulk {
	return u.Update(func(s *UserContributionRoomPreferenceUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *UserContributionRoomPreferenceUpsertBulk) SetUserID(v int64) *UserContributionRoomPreferenceUpsertBulk {
	return u.Update(func(s *UserContributionRoomPreferenceUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserContributionRoomPreferenceUpsertBulk) UpdateUserID() *UserContributionRoomPreferenceUpsertBulk {
	return u.Update(func(s *UserContributionRoomPreferenceUpsert) {
		s.UpdateUserID()
	})
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *UserContributionRoomPreferenceUpsertBulk) SetAPIKeyID(v int64) *UserContributionRoomPreferenceUpsertBulk {
	return u.Update(func(s *UserContributionRoomPreferenceUpsert) {
		s.SetAPIKeyID(v)
	})
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *UserContributionRoomPreferenceUpsertBulk) UpdateAPIKeyID() *UserContributionRoomPreferenceUpsertBulk {
	return u.Update(func(s *UserContributionRoomPreferenceUpsert) {
		s.UpdateAPIKeyID()
	})
}

// SetRoomID sets the "room_id" field.
func (u *UserContributionRoomPreferenceUpsertBulk) SetRoomID(v int64) *UserContributionRoomPreferenceUpsertBulk {
	return u.Update(func(s *UserContributionRoomPreferenceUpsert) {
		s.SetRoomID(v)
	})
}

// UpdateRoomID sets the "room_id" field to the value that was provided on create.
func (u *UserContributionRoomPreferenceUpsertBulk) UpdateRoomID() *UserContributionRoomPreferenceUpsertBulk {
	return u.Update(func(s *UserContributionRoomPreferenceUpsert) {
		s.UpdateRoomID()
	})
}

// SetAllowPoolFallback sets the "allow_pool_fallback" field.
func (u *UserContributionRoomPreferenceUpsertBulk) SetAllowPoolFallback(v bool) *UserContributionRoomPreferenceUpsertBulk {
	return u.Update(func(s *UserContributionRoomPreferenceUpsert) {
		s.SetAllowPoolFallback(v)
	})
}

// UpdateAllowPoolFallback sets the "allow_pool_fallback" field to the value that was provided on create.
func (u *UserContributionRoomPreferenceUpsertBulk) UpdateAllowPoolFallback() *UserContributionRoomPreferenceUpsertBulk {
	return u.Update(func(s *UserContributionRoomPreferenceUpsert) {
		s.UpdateAllowPoolFallback()
	})
}

// SetFallbackGroupID sets the "fallback_group_id" field.
func (u *UserContributionRoomPreferenceUpsertBulk) SetFallbackGroupID(v int64) *UserContributionRoomPreferenceUpsertBulk {
	return u.Update(func(s *UserContributionRoomPreferenceUpsert) {
		s.SetFallbackGroupID(v)
	})
}

// AddFallbackGroupID adds v to the "fallback_group_id" field.
func (u *UserContributionRoomPreferenceUpsertBulk) AddFallbackGroupID(v int64) *UserContributionRoomPreferenceUpsertBulk {
	return u.Update(func(s *UserContributionRoomPreferenceUpsert) {
		s.AddFallbackGroupID(v)
	})
}

// UpdateFallbackGroupID sets the "fallback_group_id" field to the value that was provided on create.
func (u *UserContributionRoomPreferenceUpsertBulk) UpdateFallbackGroupID() *UserContributionRoomPreferenceUpsertBulk {
	return u.Update(func(s *UserContributionRoomPreferenceUpsert) {
		s.UpdateFallbackGroupID()
	})
}

// ClearFallbackGroupID clears the value of the "fallback_group_id" field.
func (u *UserContributionRoomPreferenceUpsertBulk) ClearFallbackGroupID() *UserContributionRoomPreferenceUpsertBulk {
	return u.Update(func(s *UserContributionRoomPreferenceUpsert) {
		s.ClearFallbackGroupID()
	})
}

// Exec executes the query.
func (u *UserContributionRoomPreferenceUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the UserContributionRoomPreferenceCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UserContributionRoomPreferenceCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UserContributionRoomPreferenceUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
