// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/apikey"
	"github.com/Wei-Shaw/sub2api/ent/contributionroom"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/Wei-Shaw/sub2api/ent/usercontributionroompreference"
)

// UserContributionRoomPreference is the model entity for the UserContributionRoomPreference schema.
type UserContributionRoomPreference struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// APIKeyID holds the value of the "api_key_id" field.
	APIKeyID int64 `json:"api_key_id,omitempty"`
	// RoomID holds the value of the "room_id" field.
	RoomID int64 `json:"room_id,omitempty"`
	// AllowPoolFallback holds the value of the "allow_pool_fallback" field.
	AllowPoolFallback bool `json:"allow_pool_fallback,omitempty"`
	// FallbackGroupID holds the value of the "fallback_group_id" field.
	FallbackGroupID *int64 `json:"fallback_group_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UserContributionRoomPreferenceQuery when eager-loading is set.
	Edges        UserContributionRoomPreferenceEdges `json:"edges"`
	selectValues sql.SelectValues
}

// UserContributionRoomPreferenceEdges holds the relations/edges for other nodes in the graph.
type UserContributionRoomPreferenceEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// APIKey holds the value of the api_key edge.
	APIKey *APIKey `json:"api_key,omitempty"`
	// Room holds the value of the room edge.
	Room *ContributionRoom `json:"room,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UserContributionRoomPreferenceEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// APIKeyOrErr returns the APIKey value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UserContributionRoomPreferenceEdges) APIKeyOrErr() (*APIKey, error) {
	if e.APIKey != nil {
		return e.APIKey, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: apikey.Label}
	}
	return nil, &NotLoadedError{edge: "api_key"}
}

// RoomOrErr returns the Room value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UserContributionRoomPreferenceEdges) RoomOrErr() (*ContributionRoom, error) {
	if e.Room != nil {
		return e.Room, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: contributionroom.Label}
	}
	return nil, &NotLoadedError{edge: "room"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UserContributionRoomPreference) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case usercontributionroompreference.FieldAllowPoolFallback:
			values[i] = new(sql.NullBool)
		case usercontributionroompreference.FieldID, usercontributionroompreference.FieldUserID, usercontributionroompreference.FieldAPIKeyID, usercontributionroompreference.FieldRoomID, usercontributionroompreference.FieldFallbackGroupID:
			values[i] = new(sql.NullInt64)
		case usercontributionroompreference.FieldCreatedAt, usercontributionroompreference.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UserContributionRoomPreference fields.
func (_m *UserContributionRoomPreference) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case usercontributionroompreference.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case usercontributionroompreference.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case usercontributionroompreference.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case usercontributionroompreference.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case usercontributionroompreference.FieldAPIKeyID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field api_key_id", values[i])
			} else if value.Valid {
				_m.APIKeyID = value.Int64
			}
		case usercontributionroompreference.FieldRoomID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field room_id", values[i])
			} else if value.Valid {
				_m.RoomID = value.Int64
			}
		case usercontributionroompreference.FieldAllowPoolFallback:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field allow_pool_fallback", values[i])
			} else if value.Valid {
				_m.AllowPoolFallback = value.Bool
			}
		case usercontributionroompreference.FieldFallbackGroupID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field fallback_group_id", values[i])
			} else if value.Valid {
				_m.FallbackGroupID = new(int64)
				*_m.FallbackGroupID = value.Int64
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UserContributionRoomPreference.
// This includes values selected through modifiers, order, etc.
func (_m *UserContributionRoomPreference) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the UserContributionRoomPreference entity.
func (_m *UserContributionRoomPreference) QueryUser() *UserQuery {
	return NewUserContributionRoomPreferenceClient(_m.config).QueryUser(_m)
}

// QueryAPIKey queries the "api_key" edge of the UserContributionRoomPreference entity.
func (_m *UserContributionRoomPreference) QueryAPIKey() *APIKeyQuery {
	return NewUserContributionRoomPreferenceClient(_m.config).QueryAPIKey(_m)
}

// QueryRoom queries the "room" edge of the UserContributionRoomPreference entity.
func (_m *UserContributionRoomPreference) QueryRoom() *ContributionRoomQuery {
	return NewUserContributionRoomPreferenceClient(_m.config).QueryRoom(_m)
}

// Update returns a builder for updating this UserContributionRoomPreference.
// Note that you need to call UserContributionRoomPreference.Unwrap() before calling this method if this UserContributionRoomPreference
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *UserContributionRoomPreference) Update() *UserContributionRoomPreferenceUpdateOne {
	return NewUserContributionRoomPreferenceClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the UserContributionRoomPreference entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *UserContributionRoomPreference) Unwrap() *UserContributionRoomPreference {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: UserContributionRoomPreference is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *UserContributionRoomPreference) String() string {
	var builder strings.Builder
	builder.WriteString("UserContributionRoomPreference(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("api_key_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.APIKeyID))
	builder.WriteString(", ")
	builder.WriteString("room_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.RoomID))
	builder.WriteString(", ")
	builder.WriteString("allow_pool_fallback=")
	builder.WriteString(fmt.Sprintf("%v", _m.AllowPoolFallback))
	builder.WriteString(", ")
	if v := _m.FallbackGroupID; v != nil {
		builder.WriteString("fallback_group_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteByte(')')
	return builder.String()
}

// UserContributionRoomPreferences is a parsable slice of UserContributionRoomPreference.
type UserContributionRoomPreferences []*UserContributionRoomPreference
