//go:build embed

package web

import (
	"bytes"
	"context"
	"crypto/sha256"
	"embed"
	"encoding/hex"
	"encoding/json"
	htmlpkg "html"
	"io"
	"io/fs"
	"net/http"
	"net/url"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/Wei-Shaw/sub2api/internal/server/middleware"
	"github.com/gin-gonic/gin"
)

const (
	// NonceHTMLPlaceholder is the placeholder for nonce in HTML script tags
	NonceHTMLPlaceholder = "__CSP_NONCE_VALUE__"
)

//go:embed all:dist
var frontendFS embed.FS

// PublicSettingsProvider is an interface to fetch public settings
type PublicSettingsProvider interface {
	GetPublicSettingsForInjection(ctx context.Context) (any, error)
}

// FrontendServer serves the embedded frontend with settings injection
type FrontendServer struct {
	distFS      fs.FS
	fileServer  http.Handler
	baseHTML    []byte
	cache       *HTMLCache
	settings    PublicSettingsProvider
	overrideDir string // local file override directory
}

// NewFrontendServer creates a new frontend server with settings injection
func NewFrontendServer(settingsProvider PublicSettingsProvider) (*FrontendServer, error) {
	distFS, err := fs.Sub(frontendFS, "dist")
	if err != nil {
		return nil, err
	}

	// Read base HTML once
	file, err := distFS.Open("index.html")
	if err != nil {
		return nil, err
	}
	defer func() { _ = file.Close() }()

	baseHTML, err := io.ReadAll(file)
	if err != nil {
		return nil, err
	}

	cache := NewHTMLCache()
	cache.SetBaseHTML(baseHTML)

	return &FrontendServer{
		distFS:      distFS,
		fileServer:  http.FileServer(http.FS(distFS)),
		baseHTML:    baseHTML,
		cache:       cache,
		settings:    settingsProvider,
		overrideDir: filepath.Join("data", "public"),
	}, nil
}

// InvalidateCache invalidates the HTML cache (call when settings change)
func (s *FrontendServer) InvalidateCache() {
	if s != nil && s.cache != nil {
		s.cache.Invalidate()
	}
}

// Middleware returns the Gin middleware handler
func (s *FrontendServer) Middleware() gin.HandlerFunc {
	return func(c *gin.Context) {
		path := c.Request.URL.Path

		// Skip API routes
		if shouldBypassEmbeddedFrontend(path) {
			c.Next()
			return
		}

		switch path {
		case "/robots.txt":
			s.serveRobotsTxt(c)
			return
		case "/sitemap.xml":
			s.serveSitemapXML(c)
			return
		}

		cleanPath := strings.TrimPrefix(path, "/")
		if cleanPath == "" {
			cleanPath = "index.html"
		}

		// For index.html or SPA routes, serve with injected settings and SEO.
		if cleanPath == "index.html" || !s.fileExists(cleanPath) {
			s.serveIndexHTML(c)
			return
		}

		// Try local override first
		if s.tryServeOverride(c, cleanPath) {
			return
		}

		// Serve static files normally (hashed assets get long-lived cache headers)
		applyStaticAssetCacheHeaders(c.Writer.Header(), cleanPath)
		s.fileServer.ServeHTTP(c.Writer, c.Request)
		c.Abort()
	}
}

func (s *FrontendServer) fileExists(path string) bool {
	file, err := s.distFS.Open(path)
	if err != nil {
		return false
	}
	_ = file.Close()
	return true
}

// tryServeOverride checks if a local override file exists and serves it.
// Files in overrideDir take precedence over embedded files.
func (s *FrontendServer) tryServeOverride(c *gin.Context, cleanPath string) bool {
	if s.overrideDir == "" {
		return false
	}
	filePath := filepath.Join(s.overrideDir, filepath.Clean("/"+cleanPath))
	info, err := os.Stat(filePath)
	if err != nil || info.IsDir() {
		return false
	}
	c.File(filePath)
	c.Abort()
	return true
}

func (s *FrontendServer) serveIndexHTML(c *gin.Context) {
	// Get nonce from context (generated by SecurityHeaders middleware)
	nonce := middleware.GetNonceFromContext(c)
	cached := s.cache.Get()

	if cached == nil {
		ctx, cancel := context.WithTimeout(c.Request.Context(), 2*time.Second)
		defer cancel()

		settings, err := s.settings.GetPublicSettingsForInjection(ctx)
		if err != nil {
			s.writeIndexFallback(c, nonce)
			return
		}

		settingsJSON, err := json.Marshal(settings)
		if err != nil {
			s.writeIndexFallback(c, nonce)
			return
		}

		rendered := s.injectSettings(settingsJSON)
		s.cache.Set(rendered, settingsJSON)
		cached = &CachedHTML{Content: rendered, SettingsJSON: settingsJSON}
	}

	content := s.renderHTMLForRequest(cached.Content, cached.SettingsJSON, c.Request)
	etag := generateHTMLResponseETag(content)
	if match := c.GetHeader("If-None-Match"); match == etag {
		c.Header("ETag", etag)
		c.Status(http.StatusNotModified)
		c.Abort()
		return
	}

	content = replaceNoncePlaceholder(content, nonce)
	c.Header("ETag", etag)
	c.Header("Cache-Control", "no-cache")
	c.Data(http.StatusOK, "text/html; charset=utf-8", content)
	c.Abort()
}

func (s *FrontendServer) writeIndexFallback(c *gin.Context, nonce string) {
	content := injectSEO(s.baseHTML, nil, c.Request)
	content = replaceNoncePlaceholder(content, nonce)
	c.Header("Cache-Control", "no-cache")
	c.Data(http.StatusOK, "text/html; charset=utf-8", content)
	c.Abort()
}

func (s *FrontendServer) renderHTMLForRequest(html, settingsJSON []byte, request *http.Request) []byte {
	return injectSEO(html, settingsJSON, request)
}

func generateHTMLResponseETag(content []byte) string {
	hash := sha256.Sum256(content)
	return `"` + hex.EncodeToString(hash[:8]) + `"`
}

func (s *FrontendServer) injectSettings(settingsJSON []byte) []byte {
	// Create the script tag to inject with nonce placeholder
	// The placeholder will be replaced with actual nonce at request time
	script := []byte(`<script nonce="` + NonceHTMLPlaceholder + `">window.__APP_CONFIG__=` + string(settingsJSON) + `;</script>`)

	// Inject before </head>
	headClose := []byte("</head>")
	result := bytes.Replace(s.baseHTML, headClose, append(script, headClose...), 1)

	// Apply custom branding before the browser paints the static defaults.
	result = injectSiteTitle(result, settingsJSON)
	result = injectSiteFavicon(result, settingsJSON)

	return result
}

// injectSiteFavicon replaces the static favicon with a configured, browser-safe image URL.
func injectSiteFavicon(html, settingsJSON []byte) []byte {
	var cfg struct {
		SiteLogo string `json:"site_logo"`
	}
	if err := json.Unmarshal(settingsJSON, &cfg); err != nil {
		return html
	}

	logoURL := safeImageURL(cfg.SiteLogo)
	if logoURL == "" {
		return html
	}

	linkStart := bytes.Index(html, []byte(`<link rel="icon"`))
	if linkStart == -1 {
		return html
	}
	linkEndOffset := bytes.IndexByte(html[linkStart:], '>')
	if linkEndOffset == -1 {
		return html
	}
	linkEnd := linkStart + linkEndOffset + 1
	replacement := []byte(`<link rel="icon" href="` + htmlpkg.EscapeString(logoURL) + `" />`)

	var buf bytes.Buffer
	buf.Write(html[:linkStart])
	buf.Write(replacement)
	buf.Write(html[linkEnd:])
	return buf.Bytes()
}

func safeImageURL(value string) string {
	trimmed := strings.TrimSpace(value)
	if trimmed == "" {
		return ""
	}
	if strings.HasPrefix(trimmed, "/") && !strings.HasPrefix(trimmed, "//") {
		return trimmed
	}
	if strings.HasPrefix(strings.ToLower(trimmed), "data:image/") {
		return trimmed
	}

	parsed, err := url.Parse(trimmed)
	if err != nil || (parsed.Scheme != "http" && parsed.Scheme != "https") || parsed.Host == "" {
		return ""
	}
	return trimmed
}

// injectSiteTitle replaces the static <title> in HTML with the configured site name.
// This ensures the browser tab shows the correct title before JS executes.
func injectSiteTitle(html, settingsJSON []byte) []byte {
	var cfg struct {
		SiteName string `json:"site_name"`
	}
	if err := json.Unmarshal(settingsJSON, &cfg); err != nil || cfg.SiteName == "" {
		return html
	}

	// Find and replace the existing <title>...</title>
	titleStart := bytes.Index(html, []byte("<title>"))
	titleEnd := bytes.Index(html, []byte("</title>"))
	if titleStart == -1 || titleEnd == -1 || titleEnd <= titleStart {
		return html
	}

	newTitle := []byte("<title>" + htmlpkg.EscapeString(cfg.SiteName) + " - AI API Gateway</title>")
	var buf bytes.Buffer
	buf.Write(html[:titleStart])
	buf.Write(newTitle)
	buf.Write(html[titleEnd+len("</title>"):])
	return buf.Bytes()
}

type seoPageMetadata struct {
	Title       string
	Description string
	Image       string
	Indexable   bool
}

type publicSEOSettings struct {
	SiteName              string `json:"site_name"`
	SiteLogo              string `json:"site_logo"`
	BackendModeEnabled    bool   `json:"backend_mode_enabled"`
	ClientDownloadEnabled bool   `json:"client_download_enabled"`
	ModelPlazaEnabled     bool   `json:"model_plaza_enabled"`
	ModelPlazaRequireAuth bool   `json:"model_plaza_require_auth"`
	HomeContent           string `json:"home_content"`
}

func injectSEO(html, settingsJSON []byte, request *http.Request) []byte {
	cfg := parsePublicSEOSettings(settingsJSON)

	path := "/home"
	if request != nil && request.URL != nil && request.URL.Path != "" {
		path = request.URL.Path
	}
	if path == "/" {
		path = "/home"
	}
	origin := ""
	if request != nil {
		origin = requestOrigin(request)
	}
	metadata := seoMetadataForPath(path, cfg)
	canonical := absoluteSEOURL(origin, path)
	if metadata.Image != "" {
		metadata.Image = absoluteSEOURL(origin, metadata.Image)
	}
	if metadata.Indexable && metadata.Title != "" {
		html = replaceHTMLTitle(html, metadata.Title)
	}

	description := metadata.Description
	if description == "" {
		description = "Sub2API AI API gateway and model service."
	}
	robots := "noindex,nofollow"
	if metadata.Indexable {
		robots = "index,follow"
	}
	html = upsertMetaTag(html, "name", "description", description)
	html = upsertMetaTag(html, "name", "robots", robots)
	html = upsertMetaTag(html, "property", "og:type", "website")
	ogTitle := metadata.Title
	if ogTitle == "" {
		ogTitle = cfg.SiteName + " - AI API Gateway"
	}
	html = upsertMetaTag(html, "property", "og:title", ogTitle)
	html = upsertMetaTag(html, "property", "og:description", description)
	html = upsertMetaTag(html, "property", "og:url", canonical)
	html = upsertMetaTag(html, "name", "twitter:card", "summary")
	html = upsertMetaTag(html, "name", "twitter:title", ogTitle)
	html = upsertMetaTag(html, "name", "twitter:description", description)
	if metadata.Image != "" {
		html = upsertMetaTag(html, "property", "og:image", metadata.Image)
		html = upsertMetaTag(html, "name", "twitter:image", metadata.Image)
	}
	html = upsertCanonicalTag(html, canonical)

	if metadata.Indexable {
		html = upsertJSONLD(html, origin, cfg.SiteName, canonical, ogTitle, description, metadata.Image)
	} else {
		html = removeJSONLD(html)
	}
	return html
}

func parsePublicSEOSettings(settingsJSON []byte) publicSEOSettings {
	cfg := publicSEOSettings{
		SiteName:              "Sub2API",
		ClientDownloadEnabled: true,
		ModelPlazaEnabled:     true,
	}
	if len(settingsJSON) > 0 {
		_ = json.Unmarshal(settingsJSON, &cfg)
	}
	if strings.TrimSpace(cfg.SiteName) == "" {
		cfg.SiteName = "Sub2API"
	}
	return cfg
}

func seoMetadataForPath(path string, cfg publicSEOSettings) seoPageMetadata {
	if path == "/" || path == "/home" {
		return seoPageMetadata{
			Title:       "Sub2API - AI API 聚合网关与模型 API 服务",
			Description: "统一接入 Claude、GPT、Gemini 等主流 AI 模型，提供兼容 OpenAI 的 API 网关、账号调度与用量管理。",
			Image:       "/gongfei-plane.svg",
			Indexable:   !cfg.BackendModeEnabled && !isExternalHomeContent(cfg.HomeContent),
		}
	}
	if path == "/model-plaza" {
		return seoPageMetadata{
			Title:       "AI 模型广场 - Claude、GPT、Gemini API",
			Description: "浏览 Claude、GPT、Gemini 等 AI 模型，查看可用模型与价格，选择适合开发和团队使用的 API 服务。",
			Image:       "/gongfei-plane.svg",
			Indexable:   !cfg.BackendModeEnabled && cfg.ModelPlazaEnabled && !cfg.ModelPlazaRequireAuth,
		}
	}
	if path == "/download" {
		return seoPageMetadata{
			Title:       "Sub2API 客户端下载",
			Description: "下载 Sub2API 客户端，快速配置 AI API 服务，支持 Windows、macOS 等平台。",
			Image:       "/gongfei-plane.svg",
			Indexable:   !cfg.BackendModeEnabled && cfg.ClientDownloadEnabled,
		}
	}
	if strings.HasPrefix(path, "/legal/") {
		return seoPageMetadata{
			Title:       legalDocumentTitle(strings.TrimPrefix(path, "/legal/")) + " - Sub2API",
			Description: "Read the legal documents and service terms for Sub2API.",
			Indexable:   true,
		}
	}
	return seoPageMetadata{}
}

// legalDocumentTitle turns a legal document slug (e.g. "privacy-policy") into a
// human-readable title (e.g. "Privacy Policy"). It's a best-effort fallback —
// the real per-document title lives in the frontend's document store and isn't
// reachable from this HTTP middleware — but it at least avoids serving the
// exact same <title>/description on every distinct /legal/:documentId URL,
// which search engines flag as duplicate content.
func legalDocumentTitle(documentID string) string {
	documentID = strings.TrimSuffix(documentID, "/")
	if documentID == "" {
		return "Legal Document"
	}
	words := strings.FieldsFunc(documentID, func(r rune) bool {
		return r == '-' || r == '_'
	})
	if len(words) == 0 {
		return "Legal Document"
	}
	for i, w := range words {
		if w == "" {
			continue
		}
		runes := []rune(w)
		runes[0] = []rune(strings.ToUpper(string(runes[0])))[0]
		words[i] = string(runes)
	}
	return strings.Join(words, " ")
}

func isExternalHomeContent(content string) bool {
	trimmed := strings.TrimSpace(content)
	return strings.HasPrefix(strings.ToLower(trimmed), "http://") || strings.HasPrefix(strings.ToLower(trimmed), "https://")
}

func requestOrigin(request *http.Request) string {
	if request == nil {
		return ""
	}
	scheme := "http"
	if request.TLS != nil {
		scheme = "https"
	}
	if forwarded := strings.TrimSpace(strings.Split(request.Header.Get("X-Forwarded-Proto"), ",")[0]); forwarded == "http" || forwarded == "https" {
		scheme = forwarded
	}
	host := strings.TrimSpace(request.Host)
	if host == "" && request.URL != nil {
		host = strings.TrimSpace(request.URL.Host)
	}
	if host == "" || strings.ContainsAny(host, "\r\n") {
		return ""
	}
	return scheme + "://" + host
}

func absoluteSEOURL(origin, path string) string {
	if strings.HasPrefix(path, "http://") || strings.HasPrefix(path, "https://") {
		return path
	}
	if origin == "" {
		return path
	}
	return strings.TrimRight(origin, "/") + "/" + strings.TrimLeft(path, "/")
}

func upsertMetaTag(html []byte, attribute, key, content string) []byte {
	lowerHTML := bytes.ToLower(html)
	marker := []byte(strings.ToLower(attribute + `="` + key + `"`))
	searchFrom := 0
	for searchFrom < len(html) {
		relativeStart := bytes.Index(lowerHTML[searchFrom:], []byte("<meta"))
		if relativeStart == -1 {
			break
		}
		start := searchFrom + relativeStart
		relativeEnd := bytes.IndexByte(html[start:], '>')
		if relativeEnd == -1 {
			break
		}
		end := start + relativeEnd + 1
		if bytes.Contains(lowerHTML[start:end], marker) {
			replacement := []byte(`<meta ` + attribute + `="` + htmlpkg.EscapeString(key) + `" content="` + htmlpkg.EscapeString(content) + `" />`)
			return append(append(append([]byte{}, html[:start]...), replacement...), html[end:]...)
		}
		searchFrom = end
	}
	return insertBeforeHeadClose(html, []byte(`<meta `+attribute+`="`+htmlpkg.EscapeString(key)+`" content="`+htmlpkg.EscapeString(content)+`" />`))
}

func upsertCanonicalTag(html []byte, href string) []byte {
	lowerHTML := bytes.ToLower(html)
	searchFrom := 0
	for searchFrom < len(html) {
		relativeStart := bytes.Index(lowerHTML[searchFrom:], []byte(`<link rel="canonical"`))
		if relativeStart == -1 {
			break
		}
		start := searchFrom + relativeStart
		relativeEnd := bytes.IndexByte(html[start:], '>')
		if relativeEnd == -1 {
			break
		}
		end := start + relativeEnd + 1
		replacement := []byte(`<link rel="canonical" href="` + htmlpkg.EscapeString(href) + `" />`)
		return append(append(append([]byte{}, html[:start]...), replacement...), html[end:]...)
	}
	return insertBeforeHeadClose(html, []byte(`<link rel="canonical" href="`+htmlpkg.EscapeString(href)+`" />`))
}

func replaceHTMLTitle(html []byte, title string) []byte {
	start := bytes.Index(html, []byte("<title>"))
	if start == -1 {
		return insertBeforeHeadClose(html, []byte("<title>"+htmlpkg.EscapeString(title)+"</title>"))
	}
	contentStart := start + len("<title>")
	relativeEnd := bytes.Index(html[contentStart:], []byte("</title>"))
	if relativeEnd == -1 {
		return html
	}
	end := contentStart + relativeEnd + len("</title>")
	replacement := []byte("<title>" + htmlpkg.EscapeString(title) + "</title>")
	return append(append(append([]byte{}, html[:start]...), replacement...), html[end:]...)
}

func insertBeforeHeadClose(html, addition []byte) []byte {
	marker := []byte("</head>")
	index := bytes.Index(bytes.ToLower(html), marker)
	if index == -1 {
		return append(append([]byte{}, html...), addition...)
	}
	return append(append(append([]byte{}, html[:index]...), addition...), html[index:]...)
}

func upsertJSONLD(html []byte, origin, siteName, canonical, title, description, image string) []byte {
	graph := []map[string]any{
		{"@type": "Organization", "name": siteName, "url": absoluteSEOURL(origin, "/")},
		{"@type": "WebSite", "name": siteName, "url": absoluteSEOURL(origin, "/")},
		{"@type": "SoftwareApplication", "name": siteName, "applicationCategory": "DeveloperApplication", "operatingSystem": "Windows, macOS, Linux", "url": absoluteSEOURL(origin, "/")},
		{"@type": "WebPage", "name": title, "description": description, "url": canonical},
	}
	if image != "" {
		graph[0]["logo"] = image
	}
	payload, err := json.Marshal(map[string]any{"@context": "https://schema.org", "@graph": graph})
	if err != nil {
		return html
	}
	return replaceJSONLDElement(html, append([]byte(`<script id="sub2api-seo-jsonld" type="application/ld+json">`), append(payload, []byte(`</script>`)...)...))
}

func replaceJSONLDElement(html, replacement []byte) []byte {
	lowerHTML := bytes.ToLower(html)
	start := bytes.Index(lowerHTML, []byte(`<script id="sub2api-seo-jsonld"`))
	if start == -1 {
		return insertBeforeHeadClose(html, replacement)
	}
	endMarker := []byte("</script>")
	relativeEnd := bytes.Index(lowerHTML[start:], endMarker)
	if relativeEnd == -1 {
		return html
	}
	end := start + relativeEnd + len(endMarker)
	return append(append(append([]byte{}, html[:start]...), replacement...), html[end:]...)
}

func removeJSONLD(html []byte) []byte {
	lowerHTML := bytes.ToLower(html)
	start := bytes.Index(lowerHTML, []byte(`<script id="sub2api-seo-jsonld"`))
	if start == -1 {
		return html
	}
	relativeEnd := bytes.Index(lowerHTML[start:], []byte("</script>"))
	if relativeEnd == -1 {
		return html
	}
	end := start + relativeEnd + len("</script>")
	return append(append([]byte{}, html[:start]...), html[end:]...)
}

func (s *FrontendServer) serveRobotsTxt(c *gin.Context) {
	origin := requestOrigin(c.Request)
	body := "User-agent: *\nAllow: /\nDisallow: /admin/\nDisallow: /dashboard\nDisallow: /keys\nDisallow: /playground/\nDisallow: /usage\nDisallow: /tickets\nDisallow: /redeem\nDisallow: /affiliate\nDisallow: /profile\nDisallow: /subscriptions\nDisallow: /purchase\nDisallow: /orders\nDisallow: /payment/\nDisallow: /custom/\nDisallow: /setup\n"
	if origin != "" {
		body += "\nSitemap: " + origin + "/sitemap.xml\n"
	}
	c.Header("Cache-Control", "public, max-age=3600")
	c.Data(http.StatusOK, "text/plain; charset=utf-8", []byte(body))
	c.Abort()
}

func (s *FrontendServer) serveSitemapXML(c *gin.Context) {
	origin := requestOrigin(c.Request)
	if origin == "" {
		origin = "http://localhost"
	}

	type sitemapPage struct {
		path     string
		priority string
		freq     string
	}
	candidates := []sitemapPage{
		{"/home", "1.0", "weekly"},
		{"/model-plaza", "0.8", "weekly"},
		{"/download", "0.6", "monthly"},
	}
	pages := make([]sitemapPage, 0, len(candidates))
	if cfg, ok := s.publicSEOSettings(c.Request.Context()); ok {
		for _, candidate := range candidates {
			if seoMetadataForPath(candidate.path, cfg).Indexable {
				pages = append(pages, candidate)
			}
		}
	}

	var body strings.Builder
	body.WriteString("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<urlset xmlns=\"http://www.sitemaps.org/schemas/sitemap/0.9\">")
	for _, page := range pages {
		body.WriteString("\n  <url>\n    <loc>")
		body.WriteString(htmlpkg.EscapeString(origin + page.path))
		body.WriteString("</loc>\n    <changefreq>")
		body.WriteString(page.freq)
		body.WriteString("</changefreq>\n    <priority>")
		body.WriteString(page.priority)
		body.WriteString("</priority>\n  </url>")
	}
	body.WriteString("\n</urlset>\n")
	c.Header("Cache-Control", "public, max-age=3600")
	c.Data(http.StatusOK, "application/xml; charset=utf-8", []byte(body.String()))
	c.Abort()
}

func (s *FrontendServer) publicSEOSettings(ctx context.Context) (publicSEOSettings, bool) {
	if cached := s.cache.Get(); cached != nil && len(cached.SettingsJSON) > 0 {
		return parsePublicSEOSettings(cached.SettingsJSON), true
	}

	ctx, cancel := context.WithTimeout(ctx, 2*time.Second)
	defer cancel()
	settings, err := s.settings.GetPublicSettingsForInjection(ctx)
	if err != nil {
		return publicSEOSettings{}, false
	}
	settingsJSON, err := json.Marshal(settings)
	if err != nil {
		return publicSEOSettings{}, false
	}
	return parsePublicSEOSettings(settingsJSON), true
}

// replaceNoncePlaceholder replaces the nonce placeholder with actual nonce value
func replaceNoncePlaceholder(html []byte, nonce string) []byte {
	return bytes.ReplaceAll(html, []byte(NonceHTMLPlaceholder), []byte(nonce))
}

// ServeEmbeddedFrontend returns a middleware for serving embedded frontend
// This is the legacy function for backward compatibility when no settings provider is available
func ServeEmbeddedFrontend() gin.HandlerFunc {
	distFS, err := fs.Sub(frontendFS, "dist")
	if err != nil {
		panic("failed to get dist subdirectory: " + err.Error())
	}
	fileServer := http.FileServer(http.FS(distFS))
	overrideDir := filepath.Join("data", "public")

	return func(c *gin.Context) {
		path := c.Request.URL.Path

		if shouldBypassEmbeddedFrontend(path) {
			c.Next()
			return
		}

		cleanPath := strings.TrimPrefix(path, "/")
		if cleanPath == "" {
			cleanPath = "index.html"
		}

		if file, err := distFS.Open(cleanPath); err == nil {
			_ = file.Close()
			// Try local override first
			if tryServeOverrideFile(c, overrideDir, cleanPath) {
				return
			}
			applyStaticAssetCacheHeaders(c.Writer.Header(), cleanPath)
			fileServer.ServeHTTP(c.Writer, c.Request)
			c.Abort()
			return
		}

		serveIndexHTML(c, distFS)
	}
}

// tryServeOverrideFile is a standalone version of tryServeOverride for legacy usage.
func tryServeOverrideFile(c *gin.Context, overrideDir, cleanPath string) bool {
	if overrideDir == "" {
		return false
	}
	filePath := filepath.Join(overrideDir, filepath.Clean("/"+cleanPath))
	info, err := os.Stat(filePath)
	if err != nil || info.IsDir() {
		return false
	}
	c.File(filePath)
	c.Abort()
	return true
}

func shouldBypassEmbeddedFrontend(path string) bool {
	trimmed := strings.TrimSpace(path)
	return strings.HasPrefix(trimmed, "/api/") ||
		trimmed == "/paw" ||
		strings.HasPrefix(trimmed, "/paw/") ||
		strings.HasPrefix(trimmed, "/v1/") ||
		strings.HasPrefix(trimmed, "/v1beta/") ||
		strings.HasPrefix(trimmed, "/backend-api/") ||
		strings.HasPrefix(trimmed, "/antigravity/") ||
		strings.HasPrefix(trimmed, "/setup/") ||
		trimmed == "/health" ||
		trimmed == "/models" ||
		trimmed == "/responses" ||
		strings.HasPrefix(trimmed, "/responses/") ||
		trimmed == "/alpha/search" ||
		strings.HasPrefix(trimmed, "/images/") ||
		strings.HasPrefix(trimmed, "/videos/")
}

func serveIndexHTML(c *gin.Context, fsys fs.FS) {
	file, err := fsys.Open("index.html")
	if err != nil {
		c.String(http.StatusNotFound, "Frontend not found")
		c.Abort()
		return
	}
	defer func() { _ = file.Close() }()

	content, err := io.ReadAll(file)
	if err != nil {
		c.String(http.StatusInternalServerError, "Failed to read index.html")
		c.Abort()
		return
	}

	c.Data(http.StatusOK, "text/html; charset=utf-8", content)
	c.Abort()
}

func HasEmbeddedFrontend() bool {
	_, err := frontendFS.ReadFile("dist/index.html")
	return err == nil
}
