// Code generated by ent, DO NOT EDIT.

package contributionaccountverification

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.ContributionAccountVerification {
	return predicate.ContributionAccountVerification(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.ContributionAccountVerification {
	return predicate.ContributionAccountVerification(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.ContributionAccountVerification {
	return predicate.ContributionAccountVerification(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.ContributionAccountVerification {
	return predicate.ContributionAccountVerification(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.ContributionAccountVerification {
	return predicate.ContributionAccountVerification(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.ContributionAccountVerification {
	return predicate.ContributionAccountVerification(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.ContributionAccountVerification {
	return predicate.ContributionAccountVerification(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.ContributionAccountVerification {
	return predicate.ContributionAccountVerification(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.ContributionAccountVerification {
	return predicate.ContributionAccountVerification(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ContributionAccountVerification {
	return predicate.ContributionAccountVerification(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ContributionAccountVerification {
	return predicate.ContributionAccountVerification(sql.FieldEQ(FieldUpdatedAt, v))
}

// AccountID applies equality check predicate on the "account_id" field. It's identical to AccountIDEQ.
func AccountID(v int64) predicate.ContributionAccountVerification {
	return predicate.ContributionAccountVerification(sql.FieldEQ(FieldAccountID, v))
}

// Platform applies equality check predicate on the "platform" field. It's identical to PlatformEQ.
func Platform(v string) predicate.ContributionAccountVerification {
	return predicate.ContributionAccountVerification(sql.FieldEQ(FieldPlatform, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.ContributionAccountVerification {
	return predicate.ContributionAccountVerification(sql.FieldEQ(FieldStatus, v))
}

// ModelFamily applies equality check predicate on the "model_family" field. It's identical to ModelFamilyEQ.
func ModelFamily(v string) predicate.ContributionAccountVerification {
	return predicate.ContributionAccountVerification(sql.FieldEQ(FieldModelFamily, v))
}

// SourceKind applies equality check predicate on the "source_kind" field. It's identical to SourceKindEQ.
func SourceKind(v string) predicate.ContributionAccountVerification {
	return predicate.ContributionAccountVerification(sql.FieldEQ(FieldSourceKind, v))
}

// TestedModel applies equality check predicate on the "tested_model" field. It's identical to TestedModelEQ.
func TestedModel(v string) predicate.ContributionAccountVerification {
	return predicate.ContributionAccountVerification(sql.FieldEQ(FieldTestedModel, v))
}

// TestedAt applies equality check predicate on the "tested_at" field. It's identical to TestedAtEQ.
func TestedAt(v time.Time) predicate.ContributionAccountVerification {
	return predicate.ContributionAccountVerification(sql.FieldEQ(FieldTestedAt, v))
}

// RedactedErrorSummary applies equality check predicate on the "redacted_error_summary" field. It's identical to RedactedErrorSummaryEQ.
func RedactedErrorSummary(v string) predicate.ContributionAccountVerification {
	return predicate.ContributionAccountVerification(sql.FieldEQ(FieldRedactedErrorSummary, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ContributionAccountVerification {
	return predicate.ContributionAccountVerification(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ContributionAccountVerification {
	return predicate.ContributionAccountVerification(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ContributionAccountVerification {
	return predicate.ContributionAccountVerification(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ContributionAccountVerification {
	return predicate.ContributionAccountVerification(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ContributionAccountVerification {
	return predicate.ContributionAccountVerification(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ContributionAccountVerification {
	return predicate.ContributionAccountVerification(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ContributionAccountVerification {
	return predicate.ContributionAccountVerification(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ContributionAccountVerification {
	return predicate.ContributionAccountVerification(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ContributionAccountVerification {
	return predicate.ContributionAccountVerification(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ContributionAccountVerification {
	return predicate.ContributionAccountVerification(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ContributionAccountVerification {
	return predicate.ContributionAccountVerification(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ContributionAccountVerification {
	return predicate.ContributionAccountVerification(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ContributionAccountVerification {
	return predicate.ContributionAccountVerification(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ContributionAccountVerification {
	return predicate.ContributionAccountVerification(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ContributionAccountVerification {
	return predicate.ContributionAccountVerification(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ContributionAccountVerification {
	return predicate.ContributionAccountVerification(sql.FieldLTE(FieldUpdatedAt, v))
}

// AccountIDEQ applies the EQ predicate on the "account_id" field.
func AccountIDEQ(v int64) predicate.ContributionAccountVerification {
	return predicate.ContributionAccountVerification(sql.FieldEQ(FieldAccountID, v))
}

// AccountIDNEQ applies the NEQ predicate on the "account_id" field.
func AccountIDNEQ(v int64) predicate.ContributionAccountVerification {
	return predicate.ContributionAccountVerification(sql.FieldNEQ(FieldAccountID, v))
}

// AccountIDIn applies the In predicate on the "account_id" field.
func AccountIDIn(vs ...int64) predicate.ContributionAccountVerification {
	return predicate.ContributionAccountVerification(sql.FieldIn(FieldAccountID, vs...))
}

// AccountIDNotIn applies the NotIn predicate on the "account_id" field.
func AccountIDNotIn(vs ...int64) predicate.ContributionAccountVerification {
	return predicate.ContributionAccountVerification(sql.FieldNotIn(FieldAccountID, vs...))
}

// PlatformEQ applies the EQ predicate on the "platform" field.
func PlatformEQ(v string) predicate.ContributionAccountVerification {
	return predicate.ContributionAccountVerification(sql.FieldEQ(FieldPlatform, v))
}

// PlatformNEQ applies the NEQ predicate on the "platform" field.
func PlatformNEQ(v string) predicate.ContributionAccountVerification {
	return predicate.ContributionAccountVerification(sql.FieldNEQ(FieldPlatform, v))
}

// PlatformIn applies the In predicate on the "platform" field.
func PlatformIn(vs ...string) predicate.ContributionAccountVerification {
	return predicate.ContributionAccountVerification(sql.FieldIn(FieldPlatform, vs...))
}

// PlatformNotIn applies the NotIn predicate on the "platform" field.
func PlatformNotIn(vs ...string) predicate.ContributionAccountVerification {
	return predicate.ContributionAccountVerification(sql.FieldNotIn(FieldPlatform, vs...))
}

// PlatformGT applies the GT predicate on the "platform" field.
func PlatformGT(v string) predicate.ContributionAccountVerification {
	return predicate.ContributionAccountVerification(sql.FieldGT(FieldPlatform, v))
}

// PlatformGTE applies the GTE predicate on the "platform" field.
func PlatformGTE(v string) predicate.ContributionAccountVerification {
	return predicate.ContributionAccountVerification(sql.FieldGTE(FieldPlatform, v))
}

// PlatformLT applies the LT predicate on the "platform" field.
func PlatformLT(v string) predicate.ContributionAccountVerification {
	return predicate.ContributionAccountVerification(sql.FieldLT(FieldPlatform, v))
}

// PlatformLTE applies the LTE predicate on the "platform" field.
func PlatformLTE(v string) predicate.ContributionAccountVerification {
	return predicate.ContributionAccountVerification(sql.FieldLTE(FieldPlatform, v))
}

// PlatformContains applies the Contains predicate on the "platform" field.
func PlatformContains(v string) predicate.ContributionAccountVerification {
	return predicate.ContributionAccountVerification(sql.FieldContains(FieldPlatform, v))
}

// PlatformHasPrefix applies the HasPrefix predicate on the "platform" field.
func PlatformHasPrefix(v string) predicate.ContributionAccountVerification {
	return predicate.ContributionAccountVerification(sql.FieldHasPrefix(FieldPlatform, v))
}

// PlatformHasSuffix applies the HasSuffix predicate on the "platform" field.
func PlatformHasSuffix(v string) predicate.ContributionAccountVerification {
	return predicate.ContributionAccountVerification(sql.FieldHasSuffix(FieldPlatform, v))
}

// PlatformEqualFold applies the EqualFold predicate on the "platform" field.
func PlatformEqualFold(v string) predicate.ContributionAccountVerification {
	return predicate.ContributionAccountVerification(sql.FieldEqualFold(FieldPlatform, v))
}

// PlatformContainsFold applies the ContainsFold predicate on the "platform" field.
func PlatformContainsFold(v string) predicate.ContributionAccountVerification {
	return predicate.ContributionAccountVerification(sql.FieldContainsFold(FieldPlatform, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.ContributionAccountVerification {
	return predicate.ContributionAccountVerification(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.ContributionAccountVerification {
	return predicate.ContributionAccountVerification(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.ContributionAccountVerification {
	return predicate.ContributionAccountVerification(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.ContributionAccountVerification {
	return predicate.ContributionAccountVerification(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.ContributionAccountVerification {
	return predicate.ContributionAccountVerification(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.ContributionAccountVerification {
	return predicate.ContributionAccountVerification(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.ContributionAccountVerification {
	return predicate.ContributionAccountVerification(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.ContributionAccountVerification {
	return predicate.ContributionAccountVerification(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.ContributionAccountVerification {
	return predicate.ContributionAccountVerification(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.ContributionAccountVerification {
	return predicate.ContributionAccountVerification(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.ContributionAccountVerification {
	return predicate.ContributionAccountVerification(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.ContributionAccountVerification {
	return predicate.ContributionAccountVerification(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.ContributionAccountVerification {
	return predicate.ContributionAccountVerification(sql.FieldContainsFold(FieldStatus, v))
}

// ModelFamilyEQ applies the EQ predicate on the "model_family" field.
func ModelFamilyEQ(v string) predicate.ContributionAccountVerification {
	return predicate.ContributionAccountVerification(sql.FieldEQ(FieldModelFamily, v))
}

// ModelFamilyNEQ applies the NEQ predicate on the "model_family" field.
func ModelFamilyNEQ(v string) predicate.ContributionAccountVerification {
	return predicate.ContributionAccountVerification(sql.FieldNEQ(FieldModelFamily, v))
}

// ModelFamilyIn applies the In predicate on the "model_family" field.
func ModelFamilyIn(vs ...string) predicate.ContributionAccountVerification {
	return predicate.ContributionAccountVerification(sql.FieldIn(FieldModelFamily, vs...))
}

// ModelFamilyNotIn applies the NotIn predicate on the "model_family" field.
func ModelFamilyNotIn(vs ...string) predicate.ContributionAccountVerification {
	return predicate.ContributionAccountVerification(sql.FieldNotIn(FieldModelFamily, vs...))
}

// ModelFamilyGT applies the GT predicate on the "model_family" field.
func ModelFamilyGT(v string) predicate.ContributionAccountVerification {
	return predicate.ContributionAccountVerification(sql.FieldGT(FieldModelFamily, v))
}

// ModelFamilyGTE applies the GTE predicate on the "model_family" field.
func ModelFamilyGTE(v string) predicate.ContributionAccountVerification {
	return predicate.ContributionAccountVerification(sql.FieldGTE(FieldModelFamily, v))
}

// ModelFamilyLT applies the LT predicate on the "model_family" field.
func ModelFamilyLT(v string) predicate.ContributionAccountVerification {
	return predicate.ContributionAccountVerification(sql.FieldLT(FieldModelFamily, v))
}

// ModelFamilyLTE applies the LTE predicate on the "model_family" field.
func ModelFamilyLTE(v string) predicate.ContributionAccountVerification {
	return predicate.ContributionAccountVerification(sql.FieldLTE(FieldModelFamily, v))
}

// ModelFamilyContains applies the Contains predicate on the "model_family" field.
func ModelFamilyContains(v string) predicate.ContributionAccountVerification {
	return predicate.ContributionAccountVerification(sql.FieldContains(FieldModelFamily, v))
}

// ModelFamilyHasPrefix applies the HasPrefix predicate on the "model_family" field.
func ModelFamilyHasPrefix(v string) predicate.ContributionAccountVerification {
	return predicate.ContributionAccountVerification(sql.FieldHasPrefix(FieldModelFamily, v))
}

// ModelFamilyHasSuffix applies the HasSuffix predicate on the "model_family" field.
func ModelFamilyHasSuffix(v string) predicate.ContributionAccountVerification {
	return predicate.ContributionAccountVerification(sql.FieldHasSuffix(FieldModelFamily, v))
}

// ModelFamilyEqualFold applies the EqualFold predicate on the "model_family" field.
func ModelFamilyEqualFold(v string) predicate.ContributionAccountVerification {
	return predicate.ContributionAccountVerification(sql.FieldEqualFold(FieldModelFamily, v))
}

// ModelFamilyContainsFold applies the ContainsFold predicate on the "model_family" field.
func ModelFamilyContainsFold(v string) predicate.ContributionAccountVerification {
	return predicate.ContributionAccountVerification(sql.FieldContainsFold(FieldModelFamily, v))
}

// SourceKindEQ applies the EQ predicate on the "source_kind" field.
func SourceKindEQ(v string) predicate.ContributionAccountVerification {
	return predicate.ContributionAccountVerification(sql.FieldEQ(FieldSourceKind, v))
}

// SourceKindNEQ applies the NEQ predicate on the "source_kind" field.
func SourceKindNEQ(v string) predicate.ContributionAccountVerification {
	return predicate.ContributionAccountVerification(sql.FieldNEQ(FieldSourceKind, v))
}

// SourceKindIn applies the In predicate on the "source_kind" field.
func SourceKindIn(vs ...string) predicate.ContributionAccountVerification {
	return predicate.ContributionAccountVerification(sql.FieldIn(FieldSourceKind, vs...))
}

// SourceKindNotIn applies the NotIn predicate on the "source_kind" field.
func SourceKindNotIn(vs ...string) predicate.ContributionAccountVerification {
	return predicate.ContributionAccountVerification(sql.FieldNotIn(FieldSourceKind, vs...))
}

// SourceKindGT applies the GT predicate on the "source_kind" field.
func SourceKindGT(v string) predicate.ContributionAccountVerification {
	return predicate.ContributionAccountVerification(sql.FieldGT(FieldSourceKind, v))
}

// SourceKindGTE applies the GTE predicate on the "source_kind" field.
func SourceKindGTE(v string) predicate.ContributionAccountVerification {
	return predicate.ContributionAccountVerification(sql.FieldGTE(FieldSourceKind, v))
}

// SourceKindLT applies the LT predicate on the "source_kind" field.
func SourceKindLT(v string) predicate.ContributionAccountVerification {
	return predicate.ContributionAccountVerification(sql.FieldLT(FieldSourceKind, v))
}

// SourceKindLTE applies the LTE predicate on the "source_kind" field.
func SourceKindLTE(v string) predicate.ContributionAccountVerification {
	return predicate.ContributionAccountVerification(sql.FieldLTE(FieldSourceKind, v))
}

// SourceKindContains applies the Contains predicate on the "source_kind" field.
func SourceKindContains(v string) predicate.ContributionAccountVerification {
	return predicate.ContributionAccountVerification(sql.FieldContains(FieldSourceKind, v))
}

// SourceKindHasPrefix applies the HasPrefix predicate on the "source_kind" field.
func SourceKindHasPrefix(v string) predicate.ContributionAccountVerification {
	return predicate.ContributionAccountVerification(sql.FieldHasPrefix(FieldSourceKind, v))
}

// SourceKindHasSuffix applies the HasSuffix predicate on the "source_kind" field.
func SourceKindHasSuffix(v string) predicate.ContributionAccountVerification {
	return predicate.ContributionAccountVerification(sql.FieldHasSuffix(FieldSourceKind, v))
}

// SourceKindEqualFold applies the EqualFold predicate on the "source_kind" field.
func SourceKindEqualFold(v string) predicate.ContributionAccountVerification {
	return predicate.ContributionAccountVerification(sql.FieldEqualFold(FieldSourceKind, v))
}

// SourceKindContainsFold applies the ContainsFold predicate on the "source_kind" field.
func SourceKindContainsFold(v string) predicate.ContributionAccountVerification {
	return predicate.ContributionAccountVerification(sql.FieldContainsFold(FieldSourceKind, v))
}

// TestedModelEQ applies the EQ predicate on the "tested_model" field.
func TestedModelEQ(v string) predicate.ContributionAccountVerification {
	return predicate.ContributionAccountVerification(sql.FieldEQ(FieldTestedModel, v))
}

// TestedModelNEQ applies the NEQ predicate on the "tested_model" field.
func TestedModelNEQ(v string) predicate.ContributionAccountVerification {
	return predicate.ContributionAccountVerification(sql.FieldNEQ(FieldTestedModel, v))
}

// TestedModelIn applies the In predicate on the "tested_model" field.
func TestedModelIn(vs ...string) predicate.ContributionAccountVerification {
	return predicate.ContributionAccountVerification(sql.FieldIn(FieldTestedModel, vs...))
}

// TestedModelNotIn applies the NotIn predicate on the "tested_model" field.
func TestedModelNotIn(vs ...string) predicate.ContributionAccountVerification {
	return predicate.ContributionAccountVerification(sql.FieldNotIn(FieldTestedModel, vs...))
}

// TestedModelGT applies the GT predicate on the "tested_model" field.
func TestedModelGT(v string) predicate.ContributionAccountVerification {
	return predicate.ContributionAccountVerification(sql.FieldGT(FieldTestedModel, v))
}

// TestedModelGTE applies the GTE predicate on the "tested_model" field.
func TestedModelGTE(v string) predicate.ContributionAccountVerification {
	return predicate.ContributionAccountVerification(sql.FieldGTE(FieldTestedModel, v))
}

// TestedModelLT applies the LT predicate on the "tested_model" field.
func TestedModelLT(v string) predicate.ContributionAccountVerification {
	return predicate.ContributionAccountVerification(sql.FieldLT(FieldTestedModel, v))
}

// TestedModelLTE applies the LTE predicate on the "tested_model" field.
func TestedModelLTE(v string) predicate.ContributionAccountVerification {
	return predicate.ContributionAccountVerification(sql.FieldLTE(FieldTestedModel, v))
}

// TestedModelContains applies the Contains predicate on the "tested_model" field.
func TestedModelContains(v string) predicate.ContributionAccountVerification {
	return predicate.ContributionAccountVerification(sql.FieldContains(FieldTestedModel, v))
}

// TestedModelHasPrefix applies the HasPrefix predicate on the "tested_model" field.
func TestedModelHasPrefix(v string) predicate.ContributionAccountVerification {
	return predicate.ContributionAccountVerification(sql.FieldHasPrefix(FieldTestedModel, v))
}

// TestedModelHasSuffix applies the HasSuffix predicate on the "tested_model" field.
func TestedModelHasSuffix(v string) predicate.ContributionAccountVerification {
	return predicate.ContributionAccountVerification(sql.FieldHasSuffix(FieldTestedModel, v))
}

// TestedModelIsNil applies the IsNil predicate on the "tested_model" field.
func TestedModelIsNil() predicate.ContributionAccountVerification {
	return predicate.ContributionAccountVerification(sql.FieldIsNull(FieldTestedModel))
}

// TestedModelNotNil applies the NotNil predicate on the "tested_model" field.
func TestedModelNotNil() predicate.ContributionAccountVerification {
	return predicate.ContributionAccountVerification(sql.FieldNotNull(FieldTestedModel))
}

// TestedModelEqualFold applies the EqualFold predicate on the "tested_model" field.
func TestedModelEqualFold(v string) predicate.ContributionAccountVerification {
	return predicate.ContributionAccountVerification(sql.FieldEqualFold(FieldTestedModel, v))
}

// TestedModelContainsFold applies the ContainsFold predicate on the "tested_model" field.
func TestedModelContainsFold(v string) predicate.ContributionAccountVerification {
	return predicate.ContributionAccountVerification(sql.FieldContainsFold(FieldTestedModel, v))
}

// TestedAtEQ applies the EQ predicate on the "tested_at" field.
func TestedAtEQ(v time.Time) predicate.ContributionAccountVerification {
	return predicate.ContributionAccountVerification(sql.FieldEQ(FieldTestedAt, v))
}

// TestedAtNEQ applies the NEQ predicate on the "tested_at" field.
func TestedAtNEQ(v time.Time) predicate.ContributionAccountVerification {
	return predicate.ContributionAccountVerification(sql.FieldNEQ(FieldTestedAt, v))
}

// TestedAtIn applies the In predicate on the "tested_at" field.
func TestedAtIn(vs ...time.Time) predicate.ContributionAccountVerification {
	return predicate.ContributionAccountVerification(sql.FieldIn(FieldTestedAt, vs...))
}

// TestedAtNotIn applies the NotIn predicate on the "tested_at" field.
func TestedAtNotIn(vs ...time.Time) predicate.ContributionAccountVerification {
	return predicate.ContributionAccountVerification(sql.FieldNotIn(FieldTestedAt, vs...))
}

// TestedAtGT applies the GT predicate on the "tested_at" field.
func TestedAtGT(v time.Time) predicate.ContributionAccountVerification {
	return predicate.ContributionAccountVerification(sql.FieldGT(FieldTestedAt, v))
}

// TestedAtGTE applies the GTE predicate on the "tested_at" field.
func TestedAtGTE(v time.Time) predicate.ContributionAccountVerification {
	return predicate.ContributionAccountVerification(sql.FieldGTE(FieldTestedAt, v))
}

// TestedAtLT applies the LT predicate on the "tested_at" field.
func TestedAtLT(v time.Time) predicate.ContributionAccountVerification {
	return predicate.ContributionAccountVerification(sql.FieldLT(FieldTestedAt, v))
}

// TestedAtLTE applies the LTE predicate on the "tested_at" field.
func TestedAtLTE(v time.Time) predicate.ContributionAccountVerification {
	return predicate.ContributionAccountVerification(sql.FieldLTE(FieldTestedAt, v))
}

// TestedAtIsNil applies the IsNil predicate on the "tested_at" field.
func TestedAtIsNil() predicate.ContributionAccountVerification {
	return predicate.ContributionAccountVerification(sql.FieldIsNull(FieldTestedAt))
}

// TestedAtNotNil applies the NotNil predicate on the "tested_at" field.
func TestedAtNotNil() predicate.ContributionAccountVerification {
	return predicate.ContributionAccountVerification(sql.FieldNotNull(FieldTestedAt))
}

// RedactedErrorSummaryEQ applies the EQ predicate on the "redacted_error_summary" field.
func RedactedErrorSummaryEQ(v string) predicate.ContributionAccountVerification {
	return predicate.ContributionAccountVerification(sql.FieldEQ(FieldRedactedErrorSummary, v))
}

// RedactedErrorSummaryNEQ applies the NEQ predicate on the "redacted_error_summary" field.
func RedactedErrorSummaryNEQ(v string) predicate.ContributionAccountVerification {
	return predicate.ContributionAccountVerification(sql.FieldNEQ(FieldRedactedErrorSummary, v))
}

// RedactedErrorSummaryIn applies the In predicate on the "redacted_error_summary" field.
func RedactedErrorSummaryIn(vs ...string) predicate.ContributionAccountVerification {
	return predicate.ContributionAccountVerification(sql.FieldIn(FieldRedactedErrorSummary, vs...))
}

// RedactedErrorSummaryNotIn applies the NotIn predicate on the "redacted_error_summary" field.
func RedactedErrorSummaryNotIn(vs ...string) predicate.ContributionAccountVerification {
	return predicate.ContributionAccountVerification(sql.FieldNotIn(FieldRedactedErrorSummary, vs...))
}

// RedactedErrorSummaryGT applies the GT predicate on the "redacted_error_summary" field.
func RedactedErrorSummaryGT(v string) predicate.ContributionAccountVerification {
	return predicate.ContributionAccountVerification(sql.FieldGT(FieldRedactedErrorSummary, v))
}

// RedactedErrorSummaryGTE applies the GTE predicate on the "redacted_error_summary" field.
func RedactedErrorSummaryGTE(v string) predicate.ContributionAccountVerification {
	return predicate.ContributionAccountVerification(sql.FieldGTE(FieldRedactedErrorSummary, v))
}

// RedactedErrorSummaryLT applies the LT predicate on the "redacted_error_summary" field.
func RedactedErrorSummaryLT(v string) predicate.ContributionAccountVerification {
	return predicate.ContributionAccountVerification(sql.FieldLT(FieldRedactedErrorSummary, v))
}

// RedactedErrorSummaryLTE applies the LTE predicate on the "redacted_error_summary" field.
func RedactedErrorSummaryLTE(v string) predicate.ContributionAccountVerification {
	return predicate.ContributionAccountVerification(sql.FieldLTE(FieldRedactedErrorSummary, v))
}

// RedactedErrorSummaryContains applies the Contains predicate on the "redacted_error_summary" field.
func RedactedErrorSummaryContains(v string) predicate.ContributionAccountVerification {
	return predicate.ContributionAccountVerification(sql.FieldContains(FieldRedactedErrorSummary, v))
}

// RedactedErrorSummaryHasPrefix applies the HasPrefix predicate on the "redacted_error_summary" field.
func RedactedErrorSummaryHasPrefix(v string) predicate.ContributionAccountVerification {
	return predicate.ContributionAccountVerification(sql.FieldHasPrefix(FieldRedactedErrorSummary, v))
}

// RedactedErrorSummaryHasSuffix applies the HasSuffix predicate on the "redacted_error_summary" field.
func RedactedErrorSummaryHasSuffix(v string) predicate.ContributionAccountVerification {
	return predicate.ContributionAccountVerification(sql.FieldHasSuffix(FieldRedactedErrorSummary, v))
}

// RedactedErrorSummaryIsNil applies the IsNil predicate on the "redacted_error_summary" field.
func RedactedErrorSummaryIsNil() predicate.ContributionAccountVerification {
	return predicate.ContributionAccountVerification(sql.FieldIsNull(FieldRedactedErrorSummary))
}

// RedactedErrorSummaryNotNil applies the NotNil predicate on the "redacted_error_summary" field.
func RedactedErrorSummaryNotNil() predicate.ContributionAccountVerification {
	return predicate.ContributionAccountVerification(sql.FieldNotNull(FieldRedactedErrorSummary))
}

// RedactedErrorSummaryEqualFold applies the EqualFold predicate on the "redacted_error_summary" field.
func RedactedErrorSummaryEqualFold(v string) predicate.ContributionAccountVerification {
	return predicate.ContributionAccountVerification(sql.FieldEqualFold(FieldRedactedErrorSummary, v))
}

// RedactedErrorSummaryContainsFold applies the ContainsFold predicate on the "redacted_error_summary" field.
func RedactedErrorSummaryContainsFold(v string) predicate.ContributionAccountVerification {
	return predicate.ContributionAccountVerification(sql.FieldContainsFold(FieldRedactedErrorSummary, v))
}

// HasAccount applies the HasEdge predicate on the "account" edge.
func HasAccount() predicate.ContributionAccountVerification {
	return predicate.ContributionAccountVerification(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, AccountTable, AccountColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAccountWith applies the HasEdge predicate on the "account" edge with a given conditions (other predicates).
func HasAccountWith(preds ...predicate.Account) predicate.ContributionAccountVerification {
	return predicate.ContributionAccountVerification(func(s *sql.Selector) {
		step := newAccountStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ContributionAccountVerification) predicate.ContributionAccountVerification {
	return predicate.ContributionAccountVerification(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ContributionAccountVerification) predicate.ContributionAccountVerification {
	return predicate.ContributionAccountVerification(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ContributionAccountVerification) predicate.ContributionAccountVerification {
	return predicate.ContributionAccountVerification(sql.NotPredicates(p))
}
